from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import FamilyViewSet, TaskListViewSet, TaskViewSet, ShoppingListViewSet, ShoppingItemViewSet, RoutineViewSet, IntegrationSourceViewSet, AutomationRuleViewSet
from .workflow_views import WorkflowColumnViewSet
from .birthday_views import BirthdayPersonViewSet, birthday_list, gift_plan
from .calendar_views import FamilyEventViewSet
from .message_views import FamilyMessageViewSet
from .health_views import health
from .dashboard_weather_views import dashboard
from .weather_views import weather
from .feature_views import LoyaltyCardViewSet, notification_preferences
from .invitation_views import FamilyInvitationViewSet, invitation_info, invitation_register, invitation_accept
from .membership_views import MembershipViewSet
from .memory_views import shopping_memory_suggestions, task_memory_suggestions
from .prediction_views import shopping_prediction_accept, shopping_prediction_accept_all, shopping_prediction_feedback, shopping_prediction_list
from .profile_views import profile_avatar, profile_avatar_file, profile_detail
from .push_views import push_config, push_subscribe, push_test, push_unsubscribe
from .superadmin_views import superadmin_families, superadmin_family_detail, superadmin_owner_invite
from .smart_views import integration_oauth_callback,integration_oauth_start,shopping_clear_checked,shopping_quick_add,shopping_toggle_favorite,smart_integration_catalog,smart_integration_connect,smart_integration_sync,smart_integration_sync_all,task_quick_add
router=DefaultRouter();router.register("birthday-people",BirthdayPersonViewSet,basename="birthday-person");router.register("task-workflow-columns",WorkflowColumnViewSet,basename="task-workflow-column");router.register("families",FamilyViewSet,basename="family");router.register("memberships",MembershipViewSet,basename="membership");router.register("task-lists",TaskListViewSet,basename="task-list");router.register("tasks",TaskViewSet,basename="task");router.register("shopping-lists",ShoppingListViewSet,basename="shopping-list");router.register("shopping-items",ShoppingItemViewSet,basename="shopping-item");router.register("routines",RoutineViewSet,basename="routine");router.register("integrations",IntegrationSourceViewSet,basename="integration");router.register("automation-rules",AutomationRuleViewSet,basename="automation-rule");router.register("events",FamilyEventViewSet,basename="event");router.register("inbox",FamilyMessageViewSet,basename="inbox");router.register("invitations",FamilyInvitationViewSet,basename="invitation");router.register("loyalty-cards",LoyaltyCardViewSet,basename="loyalty-card")
urlpatterns=[path("birthdays/",birthday_list),path("birthday-gift-plans/",gift_plan),path("health/",health),path("dashboard/",dashboard),path("weather/",weather),path("profile/",profile_detail),path("profile/avatar/",profile_avatar),path("profile/avatar/<int:user_id>/<int:size>/",profile_avatar_file),path("shopping-predictions/",shopping_prediction_list),path("shopping-predictions/accept/",shopping_prediction_accept),path("shopping-predictions/accept-all/",shopping_prediction_accept_all),path("shopping-predictions/feedback/",shopping_prediction_feedback),path("invite/<str:token>/",invitation_info),path("invite/<str:token>/register/",invitation_register),path("invite/<str:token>/accept/",invitation_accept),path("superadmin/families/",superadmin_families),path("superadmin/families/<uuid:family_id>/",superadmin_family_detail),path("superadmin/families/<uuid:family_id>/owner-invite/",superadmin_owner_invite),path("push/config/",push_config),path("push/preferences/",notification_preferences),path("push/subscribe/",push_subscribe),path("push/unsubscribe/",push_unsubscribe),path("push/test/",push_test),path("tasks/suggestions/",task_memory_suggestions),path("shopping-items/suggestions/",shopping_memory_suggestions),path("smart/tasks/quick-add/",task_quick_add),path("smart/shopping/quick-add/",shopping_quick_add),path("smart/shopping/<uuid:item_id>/favorite/",shopping_toggle_favorite),path("smart/shopping-lists/<uuid:list_id>/clear-checked/",shopping_clear_checked),path("integration-hub/catalog/",smart_integration_catalog),path("integration-hub/connect/",smart_integration_connect),path("integration-hub/sync-all/",smart_integration_sync_all),path("integration-hub/<uuid:source_id>/sync/",smart_integration_sync),path("integration-oauth/start/",integration_oauth_start),path("integration-oauth/callback/",integration_oauth_callback),path("",include(router.urls))]
