import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion as deletion


def base():
    return [("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))]


def family(related):
    return ("family", models.ForeignKey(on_delete=deletion.CASCADE, related_name=related, to="family.family"))


def pet(related):
    return ("pet", models.ForeignKey(on_delete=deletion.CASCADE, related_name=related, to="pets.petprofile"))


def user(related, blank=False):
    return ("created_by", models.ForeignKey(blank=blank, null=True, on_delete=deletion.SET_NULL, related_name=related, to=settings.AUTH_USER_MODEL))


class Migration(migrations.Migration):
    initial = True
    dependencies = [("family", "0206_travel"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="PetProfile", fields=base()+[
            ("name",models.CharField(max_length=100)),("species",models.CharField(max_length=80)),("breed",models.CharField(blank=True,max_length=120)),("sex",models.CharField(choices=[("female","Female"),("male","Male"),("unknown","Unknown")],default="unknown",max_length=12)),("birth_date",models.DateField(blank=True,null=True)),("adoption_date",models.DateField(blank=True,null=True)),("photo_key",models.CharField(blank=True,max_length=160)),("color_description",models.CharField(blank=True,max_length=240)),("microchip_id",models.CharField(blank=True,max_length=120)),("insurance_provider",models.CharField(blank=True,max_length=160)),("insurance_number",models.CharField(blank=True,max_length=160)),("primary_vet_name",models.CharField(blank=True,max_length=160)),("primary_vet_phone",models.CharField(blank=True,max_length=80)),("emergency_contact_name",models.CharField(blank=True,max_length=160)),("emergency_contact_phone",models.CharField(blank=True,max_length=80)),("allergies",models.TextField(blank=True)),("important_notes",models.TextField(blank=True)),("quick_actions",models.JSONField(blank=True,default=list)),("active",models.BooleanField(db_index=True,default=True)),user("pet_profiles_created"),family("pet_profiles")], options={"ordering":["name","created_at"]}),
        migrations.AddIndex(model_name="petprofile",index=models.Index(fields=["family","active"],name="pet_profile_active_idx")),
        migrations.CreateModel(name="PetCareAccess", fields=base()+[("can_care",models.BooleanField(default=True)),("health_manage",models.BooleanField(default=False)),("remind_medications",models.BooleanField(default=True)),("remind_prevention",models.BooleanField(default=True)),family("pet_care_circle"),("membership",models.ForeignKey(on_delete=deletion.CASCADE,related_name="pet_care_access",to="family.membership"))]),
        migrations.AddConstraint(model_name="petcareaccess",constraint=models.UniqueConstraint(fields=("family","membership"),name="pet_care_circle_member_unique")),
        migrations.CreateModel(name="PetCareLog", fields=base()+[("kind",models.CharField(choices=[("feed","Feed"),("water","Water"),("walk","Walk / activity"),("toilet","Toilet"),("grooming","Grooming"),("training","Training"),("medication","Medication"),("note","Note")],max_length=20)),("occurred_at",models.DateTimeField(db_index=True)),("ended_at",models.DateTimeField(blank=True,null=True)),("value",models.JSONField(blank=True,default=dict)),("external_caregiver",models.CharField(blank=True,max_length=120)),("client_event_id",models.UUIDField(blank=True,null=True)),user("pet_care_logs_created",True),family("pet_care_logs"),pet("care_logs")], options={"ordering":["-occurred_at","-created_at"]}),
        migrations.AddConstraint(model_name="petcarelog",constraint=models.UniqueConstraint(fields=("pet","client_event_id"),name="pet_care_client_event_unique")),
        migrations.AddIndex(model_name="petcarelog",index=models.Index(fields=["pet","kind","occurred_at"],name="pet_care_kind_time_idx")),
        migrations.CreateModel(name="PetDocument", fields=base()+[("kind",models.CharField(choices=[("vaccination_record","Vaccination record"),("vet_report","Vet report"),("lab","Lab"),("prescription","Prescription"),("invoice","Invoice"),("insurance","Insurance"),("registration","Registration"),("other","Other")],default="other",max_length=32)),("title",models.CharField(max_length=180)),("filename",models.CharField(max_length=240)),("content_type",models.CharField(max_length=80)),("content",models.BinaryField(editable=False)),("sha256",models.CharField(db_index=True,max_length=64)),("occurred_at",models.DateField(blank=True,null=True)),("provider_name",models.CharField(blank=True,max_length=180)),("extraction_status",models.CharField(choices=[("queued","Queued"),("processing","Processing"),("review","Review"),("ready","Ready"),("failed","Failed")],db_index=True,default="queued",max_length=16)),("extraction_text",models.TextField(blank=True)),("extraction_error",models.TextField(blank=True)),("extraction_data",models.JSONField(blank=True,default=dict)),("field_confidences",models.JSONField(blank=True,default=dict)),("pinned",models.BooleanField(default=False)),user("pet_documents_created"),family("pet_documents"),pet("documents")], options={"ordering":["-pinned","-occurred_at","-created_at"]}),
        migrations.AddIndex(model_name="petdocument",index=models.Index(fields=["pet","kind","occurred_at"],name="pet_document_kind_idx")),
        migrations.CreateModel(name="PetHealthEvent", fields=base()+[("kind",models.CharField(choices=[("vaccination","Vaccination"),("deworming","Deworming"),("parasite_prevention","Parasite prevention"),("vet_visit","Vet visit"),("dental","Dental"),("procedure","Procedure"),("lab","Lab"),("other","Other")],default="other",max_length=32)),("title",models.CharField(max_length=180)),("occurred_at",models.DateTimeField(blank=True,null=True)),("next_due_at",models.DateTimeField(blank=True,db_index=True,null=True)),("provider_name",models.CharField(blank=True,max_length=180)),("note",models.TextField(blank=True)),("source",models.CharField(choices=[("manual","Manual"),("document_import","Document import"),("calendar","Calendar")],default="manual",max_length=24)),user("pet_health_events_created"),family("pet_health_events"),pet("health_events"),("source_document",models.ForeignKey(blank=True,null=True,on_delete=deletion.SET_NULL,related_name="health_events",to="pets.petdocument"))], options={"ordering":["next_due_at","-occurred_at","-created_at"]}),
        migrations.AddIndex(model_name="pethealthevent",index=models.Index(fields=["pet","kind","next_due_at"],name="pet_health_due_idx")),
        migrations.CreateModel(name="PetMedication", fields=base()+[("name",models.CharField(max_length=180)),("instruction_text",models.TextField(blank=True)),("dose_value",models.DecimalField(blank=True,decimal_places=3,max_digits=10,null=True)),("dose_unit",models.CharField(blank=True,max_length=40)),("schedule",models.JSONField(blank=True,default=dict)),("starts_at",models.DateTimeField()),("ends_at",models.DateTimeField(blank=True,null=True)),("active",models.BooleanField(db_index=True,default=True)),("prescribing_provider",models.CharField(blank=True,max_length=180)),("note",models.TextField(blank=True)),user("pet_medications_created"),family("pet_medications"),pet("medications"),("source_document",models.ForeignKey(blank=True,null=True,on_delete=deletion.SET_NULL,related_name="medications",to="pets.petdocument"))], options={"ordering":["-active","name","created_at"]}),
        migrations.CreateModel(name="PetMedicationDose", fields=base()+[("scheduled_for",models.DateTimeField(blank=True,null=True)),("given_at",models.DateTimeField(blank=True,null=True)),("state",models.CharField(choices=[("given","Given"),("skipped","Skipped"),("missed","Missed"),("canceled","Canceled")],max_length=16)),("note",models.TextField(blank=True)),("given_by",models.ForeignKey(blank=True,null=True,on_delete=deletion.SET_NULL,related_name="pet_medication_doses",to=settings.AUTH_USER_MODEL)),("medication",models.ForeignKey(on_delete=deletion.CASCADE,related_name="doses",to="pets.petmedication"))], options={"ordering":["-given_at","-scheduled_for","-created_at"]}),
        migrations.AddIndex(model_name="petmedicationdose",index=models.Index(fields=["medication","scheduled_for"],name="pet_med_dose_time_idx")),
        migrations.CreateModel(name="PetWeightMeasurement", fields=base()+[("measured_at",models.DateTimeField(db_index=True)),("weight_kg",models.DecimalField(decimal_places=3,max_digits=8)),("source",models.CharField(blank=True,max_length=120)),("note",models.TextField(blank=True)),user("pet_weights_created"),family("pet_weights"),pet("weights"),("source_document",models.ForeignKey(blank=True,null=True,on_delete=deletion.SET_NULL,related_name="weights",to="pets.petdocument"))], options={"ordering":["measured_at","created_at"]}),
        migrations.AddIndex(model_name="petweightmeasurement",index=models.Index(fields=["pet","measured_at"],name="pet_weight_time_idx")),
        migrations.CreateModel(name="PetObservation", fields=base()+[("observed_at",models.DateTimeField(db_index=True)),("category",models.CharField(choices=[("appetite","Appetite"),("energy","Energy"),("stool","Stool"),("vomiting","Vomiting"),("mobility","Mobility"),("skin","Skin"),("behavior","Behavior"),("other","Other")],default="other",max_length=24)),("severity",models.CharField(blank=True,choices=[("mild","Mild"),("moderate","Moderate"),("severe","Severe")],max_length=16)),("note",models.TextField()),user("pet_observations_created"),family("pet_observations"),pet("observations")], options={"ordering":["-observed_at","-created_at"]}),
        migrations.CreateModel(name="PetHandoverNote", fields=base()+[("from_at",models.DateTimeField()),("to_at",models.DateTimeField()),("note",models.TextField(blank=True)),user("pet_handover_notes_created"),family("pet_handover_notes"),pet("handover_notes")], options={"ordering":["-to_at","-created_at"]}),
        migrations.CreateModel(name="PetCareShare", fields=base()+[("token_hash",models.CharField(editable=False,max_length=64,unique=True)),("permissions",models.JSONField(blank=True,default=dict)),("label",models.CharField(blank=True,max_length=120)),("starts_at",models.DateTimeField()),("expires_at",models.DateTimeField()),("revoked_at",models.DateTimeField(blank=True,null=True)),("last_access_at",models.DateTimeField(blank=True,null=True)),user("pet_care_shares_created"),family("pet_care_shares"),pet("care_shares")], options={"ordering":["-created_at"]}),
        migrations.AddIndex(model_name="petcareshare",index=models.Index(fields=["pet","expires_at","revoked_at"],name="pet_share_active_idx")),
        migrations.CreateModel(name="PetVetQuestion", fields=base()+[("question",models.TextField()),("answered_at",models.DateTimeField(blank=True,null=True)),("answer_note",models.TextField(blank=True)),user("pet_vet_questions_created"),family("pet_vet_questions"),pet("vet_questions")], options={"ordering":["answered_at","created_at"]}),
        migrations.CreateModel(name="PetReminderDelivery", fields=base()+[("topic_key",models.CharField(max_length=180)),("scheduled_for",models.DateTimeField()),("sent_at",models.DateTimeField(blank=True,null=True)),family("pet_reminder_deliveries"),("membership",models.ForeignKey(on_delete=deletion.CASCADE,related_name="pet_reminder_deliveries",to="family.membership")),pet("reminder_deliveries")]),
        migrations.AddConstraint(model_name="petreminderdelivery",constraint=models.UniqueConstraint(fields=("membership","topic_key","scheduled_for"),name="pet_reminder_delivery_unique")),
        migrations.AddIndex(model_name="petreminderdelivery",index=models.Index(fields=["scheduled_for","sent_at"],name="pet_reminder_due_idx")),
        migrations.CreateModel(name="PetReportExportAudit", fields=base()+[("export_format",models.CharField(max_length=16)),("sections",models.JSONField(default=list)),("range_start",models.DateTimeField()),("range_end",models.DateTimeField()),family("pet_report_exports"),("membership",models.ForeignKey(on_delete=deletion.CASCADE,related_name="pet_report_exports",to="family.membership")),pet("report_exports")]),
    ]
