# Generated by Django 5.2.18 on 2026-10-09 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_user_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_position',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='workflow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskWorkflowColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('key', models.SlugField(max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('waiting', 'Waiting'), ('done', 'Done')], default='open', max_length=16)),
                ('is_terminal', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_columns', to='family.tasklist')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('task_list', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TaskStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='api', max_length=16)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='family.task')),
                ('from_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='family.taskworkflowcolumn')),
                ('to_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='family.taskworkflowcolumn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='family.taskworkflowcolumn'),
        ),
    ]
