# Generated by Django 5.2.18 on 2026-10-09 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0015_task_workflow_position_tasklist_workflow_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='birthday_prepare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='birthdays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='birthday_context',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='hidden_from_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_gift_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='birthday_context',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hidden_from_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_gift_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BirthdayPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('birth_month', models.PositiveSmallIntegerField()),
                ('birth_day', models.PositiveSmallIntegerField()),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_people', to='family.family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BirthdayGiftPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('none', 'none'), ('idea', 'idea'), ('planned', 'planned'), ('ordered', 'ordered'), ('ready', 'ready'), ('given', 'given')], default='none', max_length=16)),
                ('idea_text', models.TextField(blank=True)),
                ('hidden_from_birthday_person', models.BooleanField(default=True, editable=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_gift_plans', to='family.family')),
                ('linked_shopping_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.shoppingitem')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_gift_plans', to='family.task')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday_gift_plans', to='family.membership')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_plans', to='family.birthdayperson')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('membership__isnull', False), ('person__isnull', True)), models.Q(('membership__isnull', True), ('person__isnull', False)), _connector='OR'), name='gift_exactly_one_person'), models.UniqueConstraint(fields=('membership', 'occurrence_year'), name='gift_member_year_unique'), models.UniqueConstraint(fields=('person', 'occurrence_year'), name='gift_person_year_unique')],
            },
        ),
        migrations.CreateModel(
            name='BirthdayReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_key', models.CharField(max_length=64)),
                ('occurrence_year', models.PositiveSmallIntegerField()),
                ('stage', models.PositiveSmallIntegerField()),
                ('delivered_at', models.DateTimeField(null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'target_key', 'occurrence_year', 'stage'), name='birthday_reminder_once')],
            },
        ),
    ]
