# Generated by Django 5.2.18 on 2026-10-09 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0016_notificationpreference_birthday_prepare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineReminderState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_cycle_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='routinelog',
            options={'ordering': ['-done_at', '-id']},
        ),
        migrations.AddField(
            model_name='routine',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='target_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='target_period_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='routinelog',
            index=models.Index(fields=['routine', 'done_at'], name='routine_log_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinelog',
            constraint=models.UniqueConstraint(fields=('routine', 'request_id'), name='routine_log_request_unique'),
        ),
        migrations.AddField(
            model_name='routinereminderstate',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_reminder_states', to='family.membership'),
        ),
        migrations.AddField(
            model_name='routinereminderstate',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_states', to='family.routine'),
        ),
        migrations.AddConstraint(
            model_name='routinereminderstate',
            constraint=models.UniqueConstraint(fields=('routine', 'membership'), name='routine_member_reminder_unique'),
        ),
    ]
