# Generated by Django 5.2.18 on 2026-10-09 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0017_routinereminderstate_alter_routine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_list', 'workflow_column', 'workflow_position'], name='task_workflow_order_idx'),
        ),
    ]
