# Generated by Django 5.2.18 on 2026-10-09 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0018_task_task_workflow_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='detail_level',
            field=models.CharField(choices=[('important', 'Important only'), ('summary', 'Summaries'), ('all', 'All details')], default='summary', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_end',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_start',
            field=models.TimeField(default='22:00'),
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(max_length=180)),
                ('events', models.JSONField(default=dict)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to='family.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'bucket'), name='notification_member_bucket_unique')],
            },
        ),
    ]
