# Generated by Django 5.2.18 on 2026-10-09 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0203_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widgets', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_layouts', to='family.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'family'), name='unique_personal_today_layout')],
            },
        ),
    ]
