import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,isAuthenticated,login,logout} from './api';
import {Icon} from './icons';
import {SmartTasks,SmartShopping} from './SmartLists';
import IntegrationHub from './IntegrationHub';
import FamilyMembers from './FamilyMembers';
import AutomationHub from './AutomationHub';

const demo={tasks:[],task_lists:[],events:[],routines:[],shopping_lists:[],inbox_count:0,automation_count:0};
const unwrap=x=>x?.results||x||[];
function Card({children,className=''}){return <section className={`card ${className}`}>{children}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function Toggle({checked,onClick,label}){return <button className={`check ${checked?'checked':''}`} aria-label={label} onClick={onClick}>{checked&&<Icon name="check" size={13}/>}</button>}
function BackHead({title,onBack,action}){return <div className="page-head"><button className="back-button" onClick={onBack} aria-label="Zurück"><Icon name="back"/></button><h1 className="grow">{title}</h1>{action}</div>}
function PageHead({title,action}){return <div className="page-head"><h1>{title}</h1>{action&&<button className="fab-inline" onClick={action} aria-label={title}><Icon name="plus"/></button>}</div>}
function SectionTitle({children,action}){return <div className="section-title"><h2>{children}</h2>{action}</div>}

function Login({onDone}){const {t,i18n}=useTranslation();const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(false);const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setError(false);setBusy(true);try{await login(username,password);onDone()}catch{setError(true)}finally{setBusy(false)}}return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="fam-uh-le"/><Card className="login-card"><h1>{t('login')}</h1><form onSubmit={submit}><label>{t('username')}<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required autoFocus/></label><label>{t('password')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{t('loginFailed')}</p>}<button className="primary" type="submit" disabled={busy}>{busy?t('pleaseWait'):t('login')}</button></form><button className="text-button" onClick={()=>switchLanguage(i18n)}><Icon name="language"/> Deutsch / English</button></Card></main>}

export default function App(){
 const {t,i18n}=useTranslation();const queryAtBoot=new URLSearchParams(location.search);const [authed,setAuthed]=useState(isAuthenticated());const [active,setActive]=useState(queryAtBoot.has('integration_connected')||queryAtBoot.has('integration_error')?'integrations':'home');const [data,setData]=useState(demo);const [families,setFamilies]=useState([]);const [loading,setLoading]=useState(false);const [online,setOnline]=useState(navigator.onLine);const [installPrompt,setInstallPrompt]=useState(null);const family=families[0];
 async function load(){if(!isAuthenticated())return;setLoading(true);try{const [d,f]=await Promise.all([api('/dashboard/'),api('/families/')]);setData(d);setFamilies(unwrap(f))}catch(e){if(e.message==='unauthorized')setAuthed(false)}finally{setLoading(false)}}
 useEffect(()=>{load();const on=()=>setOnline(true),off=()=>setOnline(false),install=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',install);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',install)}},[authed]);
 if(!authed)return <Login onDone={()=>{setAuthed(true);load()}}/>;
 async function installApp(){if(!installPrompt)return;await installPrompt.prompt();try{await installPrompt.userChoice}finally{setInstallPrompt(null)}}
 async function toggleTask(x){await api(`/tasks/${x.id}/toggle/`,{method:'POST'});load()}
 async function toggleItem(x){await api(`/shopping-items/${x.id}/toggle/`,{method:'POST'});load()}
 async function routineDone(x){await api(`/routines/${x.id}/done/`,{method:'POST',body:'{}'});load()}
 const detail=['calendar','inbox','integrations','members','automations'].includes(active);
 const pages={
  home:<HomePage data={data} t={t} onTask={toggleTask} open={setActive}/>,
  tasks:<SmartTasks family={family} onChanged={load}/>,
  shopping:<SmartShopping family={family} onChanged={load}/>,
  routines:<RoutinesPage routines={data.routines||[]} t={t} done={routineDone}/>,
  more:<MorePage family={family} data={data} t={t} i18n={i18n} open={setActive} onLogout={()=>{logout();setAuthed(false)}} installable={!!installPrompt} onInstall={installApp}/>,
  calendar:<CalendarPage t={t} onBack={()=>setActive('more')}/>,
  inbox:<InboxPage t={t} onBack={()=>setActive('more')} onChanged={load}/>,
  integrations:<IntegrationHub family={family} onBack={()=>setActive('more')}/>,
  automations:<AutomationHub family={family} onBack={()=>setActive('more')}/>,
  members:<FamilyMembers family={family} onBack={()=>setActive('more')}/>
 };
 const nav=[['home','home',t('today')],['tasks','tasks',t('tasks')],['shopping','shopping',t('shopping')],['routines','history',t('routines')],['more','more',t('more')]];
 return <div className="app-shell"><header className="topbar"><button className="brand-mini" onClick={()=>setActive('home')}><img src="/brand/icon.svg" alt=""/><span>fam-uh-le</span></button><div className="status-pill"><Icon name={online?'online':'offline'} size={14}/> {online?t('online'):t('offline')}</div></header><main className="content">{loading&&<div className="loading" role="status"><Icon name="refresh"/> {t('syncing')}</div>}{pages[active]}</main>{!detail&&<nav className="bottom-nav">{nav.map(([id,icon,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon name={icon} size={21}/><span>{label}</span>{id==='more'&&data.inbox_count>0&&<i>{data.inbox_count}</i>}</button>)}</nav>}</div>
}

function HomePage({data,t,onTask,open}){const openTasks=(data.tasks||[]).filter(x=>!x.completed_at);const shopping=(data.shopping_lists||[]).flatMap(x=>x.items||[]).filter(x=>!x.checked);const upcoming=(data.events||[]).slice(0,3);return <><div className="hero smart-hero"><div><p>{new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{t('greeting')}</h1><span>{openTasks.length} Aufgaben · {shopping.length} Einkaufsartikel · {data.automation_count||0} Regeln aktiv</span></div><button className="hero-action" onClick={()=>open('automations')}><Icon name="automation"/><span>Automationen</span></button></div>{upcoming.length>0&&<div className="alert-grid">{upcoming.map(e=><Card key={e.id} className="alert-card"><div className={`event-icon ${e.type?.includes('weather')?'weather':'waste'}`}><Icon name={e.type?.includes('warning')?'warning':e.type?.includes('weather')?'weather':e.type?.includes('transit')?'transit':e.type?.includes('school')?'school':'waste'}/></div><div><small>{e.type==='public.warning'?t('publicWarning'):e.type==='weather.warning'?t('weatherWarning'):t('nextUp')}</small><strong>{e.title}</strong><span>{formatDate(e.starts_at)}</span></div></Card>)}</div>}<div className="home-smart-grid"><section><SectionTitle>Heute <button className="text-button" onClick={()=>open('tasks')}>Alle <Icon name="next"/></button></SectionTitle><Card>{openTasks.length?openTasks.slice(0,5).map(x=><div className="row" key={x.id}><Toggle checked={!!x.completed_at} onClick={()=>onTask(x)} label={x.title}/><div className="grow"><strong>{x.title}</strong><span>{[x.list_name,x.due_at?formatDate(x.due_at):null].filter(Boolean).join(' · ')}</span></div>{x.priority==='high'&&<span className="badge danger"><Icon name="priority"/></span>}</div>):<Empty text="Alles erledigt."/>}</Card></section><section><SectionTitle>{t('shopping')} <button className="text-button" onClick={()=>open('shopping')}>Liste <Icon name="next"/></button></SectionTitle><Card><div className="chips">{shopping.slice(0,10).map(x=><span className="chip" key={x.id}>{x.quantity&&<b>{x.quantity}</b>} {x.name}</span>)}{!shopping.length&&<span className="empty-inline">Einkaufsliste leer</span>}</div></Card></section></div><SectionTitle>{t('recentlyDone')}</SectionTitle><div className="routine-strip">{(data.routines||[]).slice(0,4).map(r=><Card key={r.id} className="routine-card"><Icon name="history"/><strong>{r.name}</strong><span>{distance(r.last_done_at)}</span></Card>)}</div></>}

function RoutinesPage({routines,t,done}){return <><PageHead title={t('recentlyDone')}/><p className="page-intro">Wiederkehrende Dinge bleiben sichtbar, ohne dass sie wie klassische Aufgaben ständig nerven.</p><div className="stack">{routines.length?routines.map(r=><Card key={r.id}><div className="row"><div className="round-icon"><Icon name="history"/></div><div className="grow"><strong>{r.name}</strong><span>{distance(r.last_done_at)} {r.suggested_interval_days?`· ≈ ${r.suggested_interval_days} Tage`:''}</span></div><button className="icon-button positive" onClick={()=>done(r)}><Icon name="check"/></button></div></Card>):<Empty text={t('noData')}/>}</div></>}

function MorePage({family,data,t,i18n,open,onLogout,installable,onInstall}){const items=[['calendar',t('calendar'),'calendar',''],['inbox',t('inbox'),'inbox',data.inbox_count||''],['integrations',t('integrations'),'integrations',''],['automations','Wenn → Dann','automation',data.automation_count||''],['members',t('members'),'members','']];return <><PageHead title={t('more')}/>{installable&&<Card><button className="menu-row install-row" onClick={onInstall}><Icon name="install"/><span><strong>{t('installApp')}</strong><small>{t('pwaHint')}</small></span><Icon name="next"/></button></Card>}<Card>{items.map(([id,label,icon,count])=><button className="menu-row" key={id} onClick={()=>open(id)}><Icon name={icon}/><span>{label}</span><span className="menu-tail">{count?<b className="count-badge">{count}</b>:null}<Icon name="next"/></span></button>)}</Card><Card><button className="menu-row" onClick={()=>switchLanguage(i18n)}><Icon name="language"/><span>{t('language')}</span><strong>{i18n.language.toUpperCase()}</strong></button><button className="menu-row danger-text" onClick={onLogout}><Icon name="logout"/><span>{t('logout')}</span></button></Card>{family&&<p className="family-note">{family.name} · {family.timezone}</p>}</>}

function CalendarPage({t,onBack}){const [events,setEvents]=useState([]);const [busy,setBusy]=useState(true);useEffect(()=>{api('/events/').then(x=>setEvents(unwrap(x))).finally(()=>setBusy(false))},[]);return <><BackHead title={t('calendar')} onBack={onBack}/><p className="page-intro">{t('calendarHint')}</p><div className="timeline">{busy?<Empty text="…"/>:events.length?events.map(e=><Card key={e.id} className={`event-row ${e.type?.includes('warning')?'warning-card':''}`}><div className="date-tile"><strong>{e.starts_at?new Date(e.starts_at).getDate():'–'}</strong><span>{e.starts_at?new Intl.DateTimeFormat(undefined,{month:'short'}).format(new Date(e.starts_at)):''}</span></div><div className="grow"><strong>{e.title}</strong><span>{formatDate(e.starts_at)}{e.payload?.location?` · ${e.payload.location}`:''}</span>{e.payload?.description&&<small>{e.payload.description}</small>}<small>{e.payload?.provider||e.type}{e.payload?.delay_minutes?` · +${e.payload.delay_minutes} min`:''}</small></div><Icon name={e.type?.includes('warning')?'warning':e.type?.includes('weather')?'weather':e.type?.includes('waste')?'waste':e.type?.includes('transit')?'transit':e.type?.includes('school')?'school':'calendar'}/></Card>):<Empty text={t('noUpcoming')}/>}</div></>}

function InboxPage({t,onBack,onChanged}){const [items,setItems]=useState([]);const load=()=>api('/inbox/').then(x=>setItems(unwrap(x)));useEffect(()=>{load()},[]);async function act(id,kind){await api(`/inbox/${id}/${kind}/`,{method:'POST',body:'{}'});await load();onChanged()}const pending=items.filter(x=>x.status==='new');return <><BackHead title={t('inbox')} onBack={onBack}/><p className="page-intro">{t('inboxHint')}</p><div className="stack">{pending.length?pending.map(x=><Card key={x.id}><div className="inbox-head"><Icon name="inbox"/><div className="grow"><strong>{x.title}</strong><span>{x.source}</span></div></div>{x.body&&<p className="body-copy">{x.body}</p>}<div className="action-row"><button onClick={()=>act(x.id,'to_task')}><Icon name="tasks"/>{t('toTask')}</button><button onClick={()=>act(x.id,'to_shopping')}><Icon name="shopping"/>{t('toShopping')}</button><button className="ghost-danger" onClick={()=>act(x.id,'dismiss')}><Icon name="close"/>{t('dismiss')}</button></div></Card>):<Empty text={t('noData')}/>}</div></>}

function switchLanguage(i18n){const l=i18n.language?.startsWith('de')?'en':'de';i18n.changeLanguage(l);localStorage.setItem('famuhle-language',l)}
function formatDate(date){if(!date)return '';return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(date))}
function distance(date){if(!date)return 'Noch nie';const d=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000));return d===0?'heute':`vor ${d} ${d===1?'Tag':'Tagen'}`}
