import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import './session-i18n';
import {api,isAuthenticated,login,logout} from './api';
import {Icon} from './icons';
import {SmartTasks,SmartShopping} from './SmartLists';
import IntegrationHub from './IntegrationHub';
import FamilyMembers from './FamilyMembers';
import FamilyInbox from './FamilyInbox';
import AutomationHub from './AutomationHub';
import CalendarHub from './CalendarHub';
import NotificationSettings from './NotificationSettings';
import LoyaltyCards from './LoyaltyCards';
import TodayHome from './TodayHome';
import GlobalCreate from './GlobalCreate';
import CreateFlowHost from './CreateFlowHost';
import RoutineEditor from './RoutineEditor';
import SuperAdmin from './SuperAdmin';
import {useFamilyPermissions} from './family-permissions';
import {toast} from './feedback';
import {APP_PAGES,pageFromLocation,pageHref} from './navigation';
import './family-context.css';
import './create-fab.css';

const demo={tasks:[],task_lists:[],events:[],routines:[],shopping_lists:[],inbox_count:0,automation_count:0};
const ACTIVE_FAMILY_KEY='famuhle-active-family';
const unwrap=x=>x?.results||x||[];
const sameFamily=(row,familyId)=>String(row?.family||'')===String(familyId||'');
function scopedDashboard(raw,familyId,inboxRows=[],rules=[]){return {...raw,tasks:(raw.tasks||[]).filter(row=>sameFamily(row,familyId)),task_lists:(raw.task_lists||[]).filter(row=>sameFamily(row,familyId)),events:(raw.events||[]).filter(row=>sameFamily(row,familyId)),routines:(raw.routines||[]).filter(row=>sameFamily(row,familyId)),shopping_lists:(raw.shopping_lists||[]).filter(row=>sameFamily(row,familyId)),inbox_count:inboxRows.filter(row=>sameFamily(row,familyId)&&row.status==='new').length,automation_count:rules.filter(row=>sameFamily(row,familyId)&&row.enabled).length}}
function Card({children,className=''}){return <section className={`card ${className}`}>{children}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function PageHead({title}){return <div className="page-head"><h1>{title}</h1></div>}

function Login({onDone,expired=false}){const {t,i18n}=useTranslation();const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(false);const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setError(false);setBusy(true);try{await login(username,password);onDone()}catch{setError(true)}finally{setBusy(false)}}return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="FamilyOS"/><Card className="login-card">{expired&&<div className="integration-notice" role="status"><Icon name="info"/><div><strong>{t('sessionUi.expiredTitle')}</strong><span>{t('sessionUi.expiredMessage')}</span></div></div>}<h1>{t('login')}</h1><form onSubmit={submit}><label>{t('username')}<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required autoFocus/></label><label>{t('password')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{t('loginFailed')}</p>}<button className="primary" type="submit" disabled={busy}>{busy?t('pleaseWait'):t('login')}</button></form><button className="text-button" onClick={()=>switchLanguage(i18n)}><Icon name="language"/> Deutsch / English</button></Card></main>}
function DataState({t,error,onRetry}){if(error)return <div className="smart-empty app-load-state" role="alert"><Icon name="warning" size={34}/><strong>{t('sessionUi.loadFailed')}</strong><span>{error}</span><button className="secondary compact" onClick={onRetry}><Icon name="refresh"/>{t('sessionUi.retry')}</button></div>;return <div className="smart-empty app-load-state" role="status"><Icon name="refresh" size={34}/><strong>{t('sessionUi.loading')}</strong></div>}

export default function App(){
 const {t,i18n}=useTranslation();const queryAtBoot=new URLSearchParams(location.search);const integrationCallbackAtBoot=queryAtBoot.has('integration_connected')||queryAtBoot.has('integration_error');const initial=pageFromLocation();const [authed,setAuthed]=useState(isAuthenticated());const [sessionExpired,setSessionExpired]=useState(false);const [sessionUser,setSessionUser]=useState(null);const [active,setActive]=useState(initial);const [data,setData]=useState(demo);const [families,setFamilies]=useState([]);const [activeFamilyId,setActiveFamilyId]=useState(()=>localStorage.getItem(ACTIVE_FAMILY_KEY)||'');const [loading,setLoading]=useState(false);const [loaded,setLoaded]=useState(false);const [loadError,setLoadError]=useState('');const [online,setOnline]=useState(navigator.onLine);const [installPrompt,setInstallPrompt]=useState(null);const [createFlow,setCreateFlow]=useState(null);const [createRevision,setCreateRevision]=useState(0);const family=families.find(row=>String(row.id)===String(activeFamilyId))||families[0];const {role}=useFamilyPermissions(family);
 function navigate(next,{replace=false}={}){const page=APP_PAGES.has(next)?next:'home';const href=pageHref(page);const current=`${location.pathname}${location.search}${location.hash}`;if(href!==current){const method=replace?'replaceState':'pushState';history[method]({page,appNavigation:!replace},'',href)}setActive(page)}
 function backTo(fallback='more'){if(history.state?.appNavigation)history.back();else navigate(fallback,{replace:true})}
 async function load(requestedFamilyId=activeFamilyId){if(!isAuthenticated())return;setLoading(true);setLoadError('');try{const session=await api('/auth/session/');setSessionUser(session.user||null);if(session.user?.is_superadmin){setFamilies([]);setActiveFamilyId('');setData(demo);setLoaded(true);return}const familyRows=unwrap(await api('/families/'));setFamilies(familyRows);const preferred=requestedFamilyId||localStorage.getItem(ACTIVE_FAMILY_KEY);const selected=familyRows.find(row=>String(row.id)===String(preferred))||familyRows[0];if(!selected){setActiveFamilyId('');setData(demo);localStorage.removeItem(ACTIVE_FAMILY_KEY);setLoaded(true);return}const selectedId=String(selected.id);setActiveFamilyId(selectedId);localStorage.setItem(ACTIVE_FAMILY_KEY,selectedId);const [d,inbox,rules]=await Promise.all([api(`/dashboard/?family=${encodeURIComponent(selectedId)}`),api('/inbox/'),api('/automation-rules/')]);setData(scopedDashboard(d,selectedId,unwrap(inbox),unwrap(rules)));setLoaded(true)}catch(e){if(e.message==='unauthorized')setAuthed(false);else setLoadError(e.message||t('sessionUi.loadFailed'))}finally{setLoading(false)}}
 useEffect(()=>{if(authed)load();const on=()=>setOnline(true),off=()=>setOnline(false),install=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',install);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',install)}},[authed]);
 useEffect(()=>{const expired=()=>{setSessionExpired(true);setSessionUser(null);setAuthed(false)};window.addEventListener('famuhle:session-expired',expired);return()=>window.removeEventListener('famuhle:session-expired',expired)},[]);
 useEffect(()=>{const pop=()=>{setActive(pageFromLocation());setCreateFlow(null)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 useEffect(()=>{if(integrationCallbackAtBoot)queueMicrotask(()=>history.replaceState({page:'integrations'},'',pageHref('integrations')))},[]);
 if(!authed)return <Login expired={sessionExpired} onDone={()=>{setSessionExpired(false);setSessionUser(null);setLoaded(false);setLoadError('');setAuthed(true)}}/>;
 const signOut=()=>{logout();setSessionUser(null);setFamilies([]);setLoaded(false);navigate('home',{replace:true});setSessionExpired(false);setAuthed(false)};
 if(loaded&&sessionUser?.is_superadmin)return <SuperAdmin user={sessionUser} onLogout={signOut}/>;
 async function switchFamily(nextId){if(!nextId||String(nextId)===String(family?.id))return;localStorage.setItem(ACTIVE_FAMILY_KEY,String(nextId));setActiveFamilyId(String(nextId));setCreateFlow(null);setCreateRevision(0);navigate('home');setData(demo);setLoaded(false);await load(String(nextId))}
 async function installApp(){if(!installPrompt)return;await installPrompt.prompt();try{await installPrompt.userChoice}finally{setInstallPrompt(null)}}
 async function toggleTask(x){try{await api(`/tasks/${x.id}/toggle/`,{method:'POST'});load()}catch(e){toast(e.message||t('saveFailed'),{type:'error'})}}
 async function routineDone(x){try{await api(`/routines/${x.id}/done/`,{method:'POST',body:'{}'});load();toast(`${x.name}: ${t('todayLower')}`,{type:'success'})}catch(e){toast(e.message||t('saveFailed'),{type:'error'})}}
 function showOnboarding(){if(family?.id)localStorage.removeItem(`famuhle-onboarding-dismissed:${family.id}`);navigate('home')}
 function openCreate(id,context={}){const href=`${location.pathname}${location.search}${location.hash}`;history.pushState({...history.state,createFlow:id},'',href);setCreateFlow({id,context})}
 function closeCreate(){if(history.state?.createFlow)history.back();else setCreateFlow(null)}
 async function refreshAfterCreate(){await load();setCreateRevision(value=>value+1)}
 const detail=['inbox','integrations','members','automations','notifications','loyalty'].includes(active);const familyKey=family?.id||'none';const contentKey=`${familyKey}-${createRevision}`;
 const pages={home:<TodayHome key={`home-${contentKey}`} data={data} family={family} t={t} onTask={toggleTask} open={navigate} onCreate={openCreate}/>,tasks:<SmartTasks key={`tasks-${contentKey}`} family={family} onChanged={load}/>,shopping:<SmartShopping key={`shopping-${contentKey}`} family={family} onChanged={load}/>,routines:<RoutinesPage key={`routines-${contentKey}`} routines={data.routines||[]} family={family} t={t} done={routineDone} onChanged={load}/>,more:<MorePage key={`more-${contentKey}`} family={family} data={data} t={t} i18n={i18n} open={navigate} onShowOnboarding={showOnboarding} onLogout={signOut} installable={!!installPrompt} onInstall={installApp}/>,calendar:<CalendarHub key={`calendar-${contentKey}`} family={family} t={t} onBack={()=>backTo('more')}/>,inbox:<FamilyInbox key={`inbox-${contentKey}`} family={family} t={t} onBack={()=>backTo('more')} onChanged={load}/>,integrations:<IntegrationHub key={`integrations-${contentKey}`} family={family} onBack={()=>backTo('more')}/>,automations:<AutomationHub key={`automations-${contentKey}`} family={family} onBack={()=>backTo('more')}/>,members:<FamilyMembers key={`members-${contentKey}`} family={family} onBack={()=>backTo('more')}/>,notifications:<NotificationSettings key={`notifications-${contentKey}`} family={family} t={t} onBack={()=>backTo('more')}/>,loyalty:<LoyaltyCards key={`loyalty-${contentKey}`} family={family} onBack={()=>backTo('more')}/>};
 const nav=[['home','home',t('today')],['tasks','tasks',t('tasks')],['shopping','shopping',t('shopping')],['calendar','calendar',t('calendar')],['more','more',t('more')]];const createContext={taskListId:data.task_lists?.[0]?.id||'',shoppingListId:data.shopping_lists?.[0]?.id||''};
 return <div className={`app-shell ${loaded&&family&&role?'global-create-enabled':''}`}><header className="topbar"><button className="brand-mini" onClick={()=>navigate('home')}><img src="/brand/icon.svg" alt=""/><span>FamilyOS</span></button><div className="topbar-context">{families.length>1&&<label className="family-switcher"><span className="sr-only">{t('members')}</span><Icon name="members" size={15}/><select value={family?.id||''} onChange={e=>switchFamily(e.target.value)} disabled={loading}>{families.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}<div className="status-pill"><Icon name={online?'online':'offline'} size={14}/> {online?t('online'):t('offline')}</div></div></header><main className="content">{loading&&loaded&&<div className="loading" role="status"><Icon name="refresh"/> {t('syncing')}</div>}{!loaded?<DataState t={t} error={loadError} onRetry={()=>load()}/>:family?pages[active]:<div className="smart-empty"><Icon name="members" size={34}/><strong>Keine aktive Familie</strong><span>Bitte wende dich an den FamilyOS-Administrator.</span></div>}</main>{loaded&&family&&!detail&&<nav className="bottom-nav" aria-label="Hauptnavigation">{nav.map(([id,icon,label])=><button key={id} className={active===id?'active':''} onClick={()=>navigate(id)} aria-current={active===id?'page':undefined}><Icon name={icon} size={21}/><span>{label}</span>{id==='more'&&data.inbox_count>0&&<i>{data.inbox_count}</i>}</button>)}</nav>}{loaded&&family&&<GlobalCreate page={active} family={family} role={role} context={createContext} onCreate={openCreate} suppressed={Boolean(createFlow)}/>}<CreateFlowHost action={createFlow?.id} family={family} data={data} context={createFlow?.context} onClose={closeCreate} onRefresh={refreshAfterCreate}/></div>
}

function RoutinesPage({routines,family,t,done,onChanged}){const [edit,setEdit]=useState(null);return <><PageHead title={t('recentlyDone')}/><p className="page-intro">{t('routinesHint')}</p><div className="stack">{routines.length?routines.map(r=><Card key={r.id}><div className="row"><div className="round-icon"><Icon name="history"/></div><button className="grow row-main-button" onClick={()=>setEdit(r)}><strong>{r.name}</strong><span>{distance(r.last_done_at,t)} {r.suggested_interval_days?`· ≈ ${r.suggested_interval_days} ${t('days')}`:''}</span></button><button className="icon-button positive" onClick={()=>done(r)} aria-label={`${r.name} ${t('todayLower')}`}><Icon name="check"/></button></div></Card>):<Empty text={t('noData')}/>}</div>{edit&&<RoutineEditor family={family} routine={edit} onClose={()=>setEdit(null)} onSaved={async()=>{setEdit(null);await onChanged?.()}}/>}</>}

function MorePage({family,data,t,i18n,open,onShowOnboarding,onLogout,installable,onInstall}){const items=[['calendar',t('calendar'),'calendar',''],['loyalty',t('loyaltyUi.title'),'store',''],['inbox',t('inbox'),'inbox',data.inbox_count||''],['notifications',t('notifications'),'warning',''],['integrations',t('integrations'),'integrations',''],['automations',t('ifThen'),'automation',data.automation_count||''],['members',t('members'),'members','']];return <><PageHead title={t('more')}/>{installable&&<Card><button className="menu-row install-row" onClick={onInstall}><Icon name="install"/><span><strong>{t('installApp')}</strong><small>{t('pwaHint')}</small></span><Icon name="next"/></button></Card>}<Card><button className="menu-row" onClick={onShowOnboarding}><Icon name="progress"/><span><strong>{t('onboarding.setupMenu')}</strong><small>{t('onboarding.setupMenuHint')}</small></span><Icon name="next"/></button>{items.map(([id,label,icon,count])=><button className="menu-row" key={id} onClick={()=>open(id)}><Icon name={icon}/><span>{label}</span><span className="menu-tail">{count?<b className="count-badge">{count}</b>:null}<Icon name="next"/></span></button>)}</Card><Card><button className="menu-row" onClick={()=>switchLanguage(i18n)}><Icon name="language"/><span>{t('language')}</span><strong>{i18n.language.toUpperCase()}</strong></button><button className="menu-row danger-text" onClick={onLogout}><Icon name="logout"/><span>{t('logout')}</span></button></Card>{family&&<p className="family-note">{family.name} · {family.timezone}</p>}</>}

function switchLanguage(i18n){const l=i18n.language?.startsWith('de')?'en':'de';i18n.changeLanguage(l);localStorage.setItem('famuhle-language',l)}
function distance(date,t){if(!date)return t('never');const d=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000));return d===0?t('todayLower'):t('daysAgo',{count:d})}
