import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Home, CheckSquare, ShoppingCart, History, MoreHorizontal, Plus, CalendarDays, CloudSun, Trash2, PlugZap, Inbox, Users, Languages, LogOut, Wifi, WifiOff, Check, RefreshCw, ArrowLeft, ChevronRight, X, ListTodo } from 'lucide-react';
import { api, isAuthenticated, login, logout } from './api';

const demo={tasks:[],events:[],routines:[],shopping_lists:[],inbox_count:0};
const unwrap=x=>x?.results||x||[];
function Card({children,className=''}){return <section className={`card ${className}`}>{children}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function Toggle({checked,onClick,label}){return <button className={`check ${checked?'checked':''}`} aria-label={label} onClick={onClick}>{checked&&<Check size={14}/>}</button>}
function BackHead({title,onBack,action}){return <div className="page-head"><button className="back-button" onClick={onBack} aria-label="Back"><ArrowLeft/></button><h1 className="grow">{title}</h1>{action}</div>}
function PageHead({title,action}){return <div className="page-head"><h1>{title}</h1>{action&&<button className="fab-inline" onClick={action}><Plus size={20}/></button>}</div>}
function SectionTitle({children}){return <div className="section-title"><h2>{children}</h2></div>}

function Login({onDone}){
 const {t,i18n}=useTranslation();const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(false);
 async function submit(e){e.preventDefault();setError(false);try{await login(username,password);onDone()}catch{setError(true)}}
 return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="fam-uh-le"/><Card className="login-card"><h1>{t('login')}</h1><form onSubmit={submit}><label>{t('username')}<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>{t('password')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<p className="error">Anmeldung fehlgeschlagen.</p>}<button className="primary" type="submit">{t('login')}</button></form><button className="text-button" onClick={()=>switchLanguage(i18n)}><Languages size={17}/> Deutsch / English</button></Card></main>
}

export default function App(){
 const {t,i18n}=useTranslation();const [authed,setAuthed]=useState(isAuthenticated());const [active,setActive]=useState('home');const [data,setData]=useState(demo);const [families,setFamilies]=useState([]);const [loading,setLoading]=useState(false);const [online,setOnline]=useState(navigator.onLine);const family=families[0];
 async function load(){if(!isAuthenticated())return;setLoading(true);try{const [d,f]=await Promise.all([api('/dashboard/'),api('/families/')]);setData(d);setFamilies(unwrap(f))}catch(e){if(e.message==='unauthorized')setAuthed(false)}finally{setLoading(false)}}
 useEffect(()=>{load();const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[authed]);
 if(!authed)return <Login onDone={()=>{setAuthed(true);load()}}/>;
 async function quickTask(){const title=prompt(t('addTask'));if(!title||!family)return;await api('/tasks/',{method:'POST',body:JSON.stringify({family:family.id,title})});load()}
 async function toggleTask(x){await api(`/tasks/${x.id}/toggle/`,{method:'POST'});load()}
 async function quickItem(){let list=data.shopping_lists?.[0];if(!family)return;if(!list){list=await api('/shopping-lists/',{method:'POST',body:JSON.stringify({family:family.id,name:t('shopping')})})}const name=prompt(t('addItem'));if(!name)return;await api('/shopping-items/',{method:'POST',body:JSON.stringify({shopping_list:list.id,name})});load()}
 async function toggleItem(x){await api(`/shopping-items/${x.id}/toggle/`,{method:'POST'});load()}
 async function routineDone(x){await api(`/routines/${x.id}/done/`,{method:'POST',body:'{}'});load()}
 const detail=['calendar','inbox','integrations','members'].includes(active);
 const pages={
  home:<HomePage data={data} t={t} onTask={toggleTask}/>,tasks:<TasksPage tasks={data.tasks||[]} t={t} add={quickTask} toggle={toggleTask}/>,shopping:<ShoppingPage lists={data.shopping_lists||[]} t={t} add={quickItem} toggle={toggleItem}/>,routines:<RoutinesPage routines={data.routines||[]} t={t} done={routineDone}/>,
  more:<MorePage family={family} inboxCount={data.inbox_count} t={t} i18n={i18n} open={setActive} onLogout={()=>{logout();setAuthed(false)}}/>,calendar:<CalendarPage t={t} onBack={()=>setActive('more')}/>,inbox:<InboxPage t={t} onBack={()=>setActive('more')} onChanged={load}/>,integrations:<IntegrationsPage family={family} t={t} onBack={()=>setActive('more')}/>,members:<MembersPage family={family} t={t} onBack={()=>setActive('more')}/>
 };
 const nav=[['home',Home,t('today')],['tasks',CheckSquare,t('tasks')],['shopping',ShoppingCart,t('shopping')],['routines',History,t('routines')],['more',MoreHorizontal,t('more')]];
 return <div className="app-shell"><header className="topbar"><button className="brand-mini" onClick={()=>setActive('home')}><img src="/brand/icon.svg"/><span>fam-uh-le</span></button><div className="status-pill">{online?<Wifi size={14}/>:<WifiOff size={14}/>} {online?t('online'):t('offline')}</div></header><main className="content">{loading&&<div className="loading"><RefreshCw size={16}/> Sync</div>}{pages[active]}</main>{!detail&&<nav className="bottom-nav">{nav.map(([id,Icon,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={22}/><span>{label}</span>{id==='more'&&data.inbox_count>0&&<i>{data.inbox_count}</i>}</button>)}</nav>}</div>
}

function HomePage({data,t,onTask}){return <><div className="hero"><p>{new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{t('greeting')}</h1></div><div className="alert-grid">{(data.events||[]).slice(0,2).map(e=><Card key={e.id} className="alert-card"><div className={`event-icon ${e.type?.includes('weather')?'weather':'waste'}`}>{e.type?.includes('weather')?<CloudSun/>:<Trash2/>}</div><div><small>{t('nextUp')}</small><strong>{e.title}</strong><span>{formatDate(e.starts_at)}</span></div></Card>)}</div><SectionTitle>{t('today')}</SectionTitle><Card>{(data.tasks||[]).length?(data.tasks||[]).slice(0,5).map(x=><div className="row" key={x.id}><Toggle checked={!!x.completed_at} onClick={()=>onTask(x)} label={x.title}/><div className="grow"><strong>{x.title}</strong><span>{x.due_at?formatDate(x.due_at):''}</span></div></div>):<Empty text={t('noData')}/>}</Card><SectionTitle>{t('shopping')}</SectionTitle><Card><div className="chips">{(data.shopping_lists?.[0]?.items||[]).filter(x=>!x.checked).slice(0,8).map(x=><span className="chip" key={x.id}>{x.name}</span>)}</div></Card><SectionTitle>{t('recentlyDone')}</SectionTitle><div className="routine-strip">{(data.routines||[]).slice(0,4).map(r=><Card key={r.id} className="routine-card"><History size={20}/><strong>{r.name}</strong><span>{distance(r.last_done_at)}</span></Card>)}</div></>}
function TasksPage({tasks,t,add,toggle}){return <><PageHead title={t('tasks')} action={add}/><Card>{tasks.length?tasks.map(x=><div className="row" key={x.id}><Toggle checked={!!x.completed_at} onClick={()=>toggle(x)} label={x.title}/><div className="grow"><strong>{x.title}</strong><span>{x.due_at?formatDate(x.due_at):''}</span></div>{x.priority==='high'&&<span className="badge danger">!</span>}</div>):<Empty text={t('noData')}/>}</Card></>}
function ShoppingPage({lists,t,add,toggle}){const items=lists.flatMap(l=>l.items||[]);return <><PageHead title={t('shopping')} action={add}/><div className="filter-chips"><span className="chip active">Alle</span>{lists.map(l=><span className="chip" key={l.id}>{l.name}</span>)}</div><Card>{items.length?items.map(x=><div className="row" key={x.id}><Toggle checked={x.checked} onClick={()=>toggle(x)} label={x.name}/><div className="grow"><strong className={x.checked?'strike':''}>{x.name}</strong><span>{x.quantity||x.category||''}</span></div></div>):<Empty text={t('noData')}/>}</Card></>}
function RoutinesPage({routines,t,done}){return <><PageHead title={t('recentlyDone')}/><div className="stack">{routines.length?routines.map(r=><Card key={r.id}><div className="row"><div className="round-icon"><History size={18}/></div><div className="grow"><strong>{r.name}</strong><span>{distance(r.last_done_at)} {r.suggested_interval_days?`· ≈ ${r.suggested_interval_days} Tage`:''}</span></div><button className="icon-button positive" onClick={()=>done(r)}><Check size={20}/></button></div></Card>):<Empty text={t('noData')}/>}</div></>}
function MorePage({family,inboxCount,t,i18n,open,onLogout}){const items=[[CalendarDays,t('calendar'),'calendar'],[Inbox,t('inbox'),'inbox'],[PlugZap,t('integrations'),'integrations'],[Users,t('members'),'members']];return <><PageHead title={t('more')}/><Card>{items.map(([Icon,label,id])=><button className="menu-row" key={id} onClick={()=>open(id)}><Icon size={20}/><span>{label}</span><span className="menu-tail">{id==='inbox'&&inboxCount>0?<b className="count-badge">{inboxCount}</b>:null}<ChevronRight size={18}/></span></button>)}</Card><Card><button className="menu-row" onClick={()=>switchLanguage(i18n)}><Languages size={20}/><span>{t('language')}</span><strong>{i18n.language.toUpperCase()}</strong></button><button className="menu-row danger-text" onClick={onLogout}><LogOut size={20}/><span>{t('logout')}</span></button></Card>{family&&<p className="family-note">{family.name} · {family.timezone}</p>}</>}

function CalendarPage({t,onBack}){const [events,setEvents]=useState([]);const [busy,setBusy]=useState(true);useEffect(()=>{api('/events/').then(x=>setEvents(unwrap(x))).finally(()=>setBusy(false))},[]);return <><BackHead title={t('calendar')} onBack={onBack}/><p className="page-intro">{t('calendarHint')}</p><div className="timeline">{busy?<Empty text="…"/>:events.length?events.map(e=><Card key={e.id} className="event-row"><div className="date-tile"><strong>{e.starts_at?new Date(e.starts_at).getDate():'–'}</strong><span>{e.starts_at?new Intl.DateTimeFormat(undefined,{month:'short'}).format(new Date(e.starts_at)):''}</span></div><div className="grow"><strong>{e.title}</strong><span>{formatDate(e.starts_at)}{e.payload?.location?` · ${e.payload.location}`:''}</span><small>{e.type}</small></div></Card>):<Empty text={t('noUpcoming')}/>}</div></>}
function InboxPage({t,onBack,onChanged}){const [items,setItems]=useState([]);const load=()=>api('/inbox/').then(x=>setItems(unwrap(x)));useEffect(()=>{load()},[]);async function act(id,kind){await api(`/inbox/${id}/${kind}/`,{method:'POST',body:'{}'});await load();onChanged()}return <><BackHead title={t('inbox')} onBack={onBack}/><p className="page-intro">{t('inboxHint')}</p><div className="stack">{items.filter(x=>x.status==='new').length?items.filter(x=>x.status==='new').map(x=><Card key={x.id}><div className="inbox-head"><Inbox size={18}/><div className="grow"><strong>{x.title}</strong><span>{x.source}</span></div></div>{x.body&&<p className="body-copy">{x.body}</p>}<div className="action-row"><button onClick={()=>act(x.id,'to_task')}><ListTodo size={16}/>{t('toTask')}</button><button onClick={()=>act(x.id,'to_shopping')}><ShoppingCart size={16}/>{t('toShopping')}</button><button className="ghost-danger" onClick={()=>act(x.id,'dismiss')}><X size={16}/>{t('dismiss')}</button></div></Card>):<Empty text={t('noData')}/>}</div></>}
function IntegrationsPage({family,t,onBack}){const [items,setItems]=useState([]);const [busy,setBusy]=useState('');const load=()=>api('/integrations/').then(x=>setItems(unwrap(x)));useEffect(()=>{load()},[]);async function sync(x){setBusy(x.id);await api(`/integrations/${x.id}/sync/`,{method:'POST',body:'{}'});await load();setBusy('')}return <><BackHead title={t('integrations')} onBack={onBack}/><p className="page-intro">{t('integrationsHint')}</p><div className="stack">{items.length?items.map(x=><Card key={x.id}><div className="integration-row"><div className="round-icon"><PlugZap size={18}/></div><div className="grow"><strong>{x.name}</strong><span>{x.kind} · {x.enabled?t('enabled'):t('disabled')}</span><small>{t('lastSync')}: {x.last_synced_at?formatDate(x.last_synced_at):t('never')}</small></div><button className="small-action" disabled={!x.enabled||busy===x.id} onClick={()=>sync(x)}><RefreshCw size={15} className={busy===x.id?'spin':''}/>{t('sync')}</button></div></Card>):<Empty text={t('noData')}/>}</div>{family&&<p className="family-note">{family.name}</p>}</>}
function MembersPage({family,t,onBack}){const members=family?.memberships||[];return <><BackHead title={t('members')} onBack={onBack}/><p className="page-intro">{t('membersHint')}</p><Card>{members.length?members.map(m=><div className="member-row" key={m.id}><div className="avatar">{(m.display_name||m.username||'?').slice(0,1).toUpperCase()}</div><div className="grow"><strong>{m.display_name||m.username}</strong><span>{t(m.role)||m.role}</span></div><span className="role-pill">{m.role}</span></div>):<Empty text={t('noData')}/>}</Card></>}

function switchLanguage(i18n){const l=i18n.language?.startsWith('de')?'en':'de';i18n.changeLanguage(l);localStorage.setItem('famuhle-language',l)}
function formatDate(date){if(!date)return '';return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(date))}
function distance(date){if(!date)return 'Noch nie';const d=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000));return d===0?'heute':`vor ${d} ${d===1?'Tag':'Tagen'}`}
