import {useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';

const unwrap=x=>x?.results||x||[];
const triggerLabels={
 waste_tomorrow:'Müllabfuhr ist morgen',weather_frost:'Frost wird erwartet',weather_rain:'Regenwahrscheinlichkeit ist hoch',warning_active:'Amtliche Warnung ist aktiv',event_upcoming:'Termin steht bevor',daily:'Täglich zu einer Uhrzeit',home_state:'Smart-Home-Zustand trifft zu',transit_delay:'ÖPNV ist verspätet',task_completed:'Aufgabe wurde erledigt'
};
const actionLabels={task_create:'Aufgabe anlegen',shopping_add:'Einkauf ergänzen',inbox_create:'Inbox-Hinweis anlegen',home_service:'Smart-Home-Aktion ausführen',push_notify:'Push-Benachrichtigung senden'};
const defaultBuilder=()=>({name:'',trigger_type:'waste_tomorrow',action_type:'task_create',trigger_config:{},action_config:{title:'{event_title} erledigen'}});

export default function AutomationHub({family,onBack}){
 const [rules,setRules]=useState([]);const [templates,setTemplates]=useState([]);const [integrations,setIntegrations]=useState([]);const [taskLists,setTaskLists]=useState([]);const [shoppingLists,setShoppingLists]=useState([]);const [busy,setBusy]=useState(false);const [builder,setBuilder]=useState(defaultBuilder());
 async function load(){if(!family)return;const [r,t,i,tl,sl]=await Promise.all([api('/automation-rules/'),api('/automation-rules/templates/'),api('/integrations/'),api('/task-lists/'),api('/shopping-lists/')]);setRules(unwrap(r).filter(x=>x.family===family.id));setTemplates(t);setIntegrations(unwrap(i).filter(x=>x.family===family.id&&x.enabled));setTaskLists(unwrap(tl).filter(x=>x.family===family.id&&!x.archived));setShoppingLists(unwrap(sl).filter(x=>x.family===family.id&&!x.archived))}
 useEffect(()=>{load().catch(e=>toast(e.message||'Automationen konnten nicht geladen werden.',{type:'error'}))},[family?.id]);
 const homeSources=useMemo(()=>integrations.filter(x=>x.kind==='home'&&x.config?.adapter==='home_assistant'),[integrations]);
 const transitSources=useMemo(()=>integrations.filter(x=>x.kind==='transit'),[integrations]);
 async function addTemplate(id){setBusy(true);try{await api('/automation-rules/from_template/',{method:'POST',body:JSON.stringify({family:family.id,template_id:id})});await load();toast('Vorlage aktiviert.',{type:'success'})}catch(e){toast(e.message||'Vorlage konnte nicht aktiviert werden.',{type:'error'})}finally{setBusy(false)}}
 async function toggle(rule){try{await api(`/automation-rules/${rule.id}/toggle/`,{method:'POST'});await load();toast(rule.enabled?'Regel deaktiviert.':'Regel aktiviert.',{type:'success'})}catch(e){toast(e.message||'Regel konnte nicht geändert werden.',{type:'error'})}}
 async function run(rule){setBusy(true);try{await api(`/automation-rules/${rule.id}/run/`,{method:'POST'});await load();toast('Regeltest ausgeführt.',{type:'success'})}catch(e){toast(e.message||'Regeltest fehlgeschlagen.',{type:'error'})}finally{setBusy(false)}}
 async function remove(rule){const ok=await confirmAction({title:'Regel löschen?',message:`„${rule.name}“ wird dauerhaft entfernt.`,confirmLabel:'Regel löschen',danger:true});if(!ok)return;try{await api(`/automation-rules/${rule.id}/`,{method:'DELETE'});await load();toast('Regel gelöscht.',{type:'success'})}catch(e){toast(e.message||'Regel konnte nicht gelöscht werden.',{type:'error'})}}
 async function create(e){e.preventDefault();const name=builder.name.trim()||`${triggerLabels[builder.trigger_type]} → ${actionLabels[builder.action_type]}`;setBusy(true);try{await api('/automation-rules/',{method:'POST',body:JSON.stringify({...builder,family:family.id,name,icon:'wand-magic-sparkles'})});setBuilder(defaultBuilder());await load();toast('Regel gespeichert.',{type:'success'})}catch(e){toast(e.message||'Regel konnte nicht gespeichert werden.',{type:'error'})}finally{setBusy(false)}}
 function set(key,value){setBuilder(v=>({...v,[key]:value}))}
 function setAction(key,value){setBuilder(v=>({...v,action_config:{...v.action_config,[key]:value}}))}
 function setTrigger(key,value){setBuilder(v=>({...v,trigger_config:{...v.trigger_config,[key]:value}}))}
 return <div className="smart-page automation-grid"><div className="page-head"><button className="back-button" onClick={onBack}><Icon name="back"/></button><div className="grow"><small>Automationen</small><h1>Wenn → Dann</h1></div><span className="status-pill"><Icon name="bolt"/> {rules.filter(x=>x.enabled).length} aktiv</span></div><p className="page-intro">fam-uh-le prüft Regeln nach jedem Daten-Sync. Erfolgreiche Ausführungen werden dedupliziert und protokolliert – dadurch entstehen keine Doppelaufgaben.</p>
 <section><div className="section-title"><h2>Schnellvorlagen</h2></div><div className="automation-template-grid">{templates.map(t=><button key={t.id} className="automation-template" onClick={()=>addTemplate(t.id)} disabled={busy}><span className="template-icon"><Icon name={templateIcon(t.id)} size={20}/></span><strong>{t.name}</strong><p>{t.description}</p><span className="text-button"><Icon name="plus"/> Aktivieren</span></button>)}</div></section>
 <section><div className="section-title"><h2>Eigene Regel</h2></div><form className="automation-builder" onSubmit={create}><label>Name<input value={builder.name} onChange={e=>set('name',e.target.value)} placeholder="z. B. Mülltonne erinnern"/></label><div className="when-then"><div><label>WENN<select value={builder.trigger_type} onChange={e=>set('trigger_type',e.target.value)}>{Object.entries(triggerLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><TriggerFields builder={builder} setTrigger={setTrigger} homeSources={homeSources} transitSources={transitSources} taskLists={taskLists}/></div><div className="arrow"><Icon name="next" size={24}/></div><div><label>DANN<select value={builder.action_type} onChange={e=>set('action_type',e.target.value)}>{Object.entries(actionLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><ActionFields builder={builder} setAction={setAction} homeSources={homeSources} taskLists={taskLists} shoppingLists={shoppingLists}/></div></div><button className="primary" disabled={busy}><Icon name="automation"/> {busy?'Speichere …':'Regel speichern'}</button></form></section>
 <section><div className="section-title"><h2>Regeln & Historie</h2></div><div className="automation-grid">{rules.map(r=><article className="rule-row" key={r.id}><span className="rule-icon"><Icon name={ruleIcon(r.trigger_type)}/></span><div><strong>{r.name}</strong><div className="rule-summary"><span>WENN {triggerLabels[r.trigger_type]||r.trigger_type}</span><span>→</span><span>DANN {actionLabels[r.action_type]||r.action_type}</span>{r.executions?.length>0&&<span>· {r.executions.filter(x=>x.status==='success').length}× erfolgreich</span>}{r.executions?.some(x=>x.status==='error')&&<span className="danger-text">· Fehler protokolliert</span>}</div></div><div className="rule-actions"><button className={r.enabled?'active':''} onClick={()=>toggle(r)} title={r.enabled?'Deaktivieren':'Aktivieren'} aria-label={r.enabled?'Regel deaktivieren':'Regel aktivieren'}><Icon name="bolt"/></button><button onClick={()=>run(r)} title="Jetzt testen" aria-label="Regel jetzt testen"><Icon name="play"/></button><button onClick={()=>remove(r)} title="Löschen" aria-label="Regel löschen"><Icon name="delete"/></button></div></article>)}{!rules.length&&<div className="smart-empty"><Icon name="automation" size={34}/><strong>Noch keine Regeln</strong><span>Aktiviere eine Vorlage oder erstelle deine erste Wenn→Dann-Regel.</span></div>}</div></section></div>
}

function TriggerFields({builder,setTrigger,homeSources,transitSources,taskLists}){const t=builder.trigger_type,c=builder.trigger_config;return <>{t==='weather_frost'&&<><label>Temperatur ≤ °C<input type="number" value={c.temperature??0} onChange={e=>setTrigger('temperature',Number(e.target.value))}/></label><label>Zeitraum (Stunden)<input type="number" min="1" value={c.within_hours??36} onChange={e=>setTrigger('within_hours',Number(e.target.value))}/></label></>}{t==='weather_rain'&&<><label>Wahrscheinlichkeit ≥ %<input type="number" min="0" max="100" value={c.probability??75} onChange={e=>setTrigger('probability',Number(e.target.value))}/></label><label>Zeitraum (Stunden)<input type="number" min="1" value={c.within_hours??24} onChange={e=>setTrigger('within_hours',Number(e.target.value))}/></label></>}{t==='daily'&&<label>Uhrzeit<input type="time" value={c.time||'08:00'} onChange={e=>setTrigger('time',e.target.value)}/></label>}{t==='event_upcoming'&&<><label>Terminart<select value={c.event_type||'calendar.event'} onChange={e=>setTrigger('event_type',e.target.value)}><option value="calendar.event">Kalendertermin</option><option value="school.event">Schule / Stundenplan</option><option value="waste.collection">Müllabfuhr</option></select></label><label>Titel enthält<input value={c.title_contains||''} onChange={e=>setTrigger('title_contains',e.target.value)} placeholder="optional"/></label><label>Innerhalb Stunden<input type="number" min="1" value={c.within_hours??24} onChange={e=>setTrigger('within_hours',Number(e.target.value))}/></label></>}{t==='home_state'&&<><SourceSelect label="Home Assistant" sources={homeSources} value={c.integration_source||''} onChange={v=>setTrigger('integration_source',v)}/><label>Entity<input value={c.entity_id||''} onChange={e=>setTrigger('entity_id',e.target.value)} placeholder="binary_sensor.tuer" required/></label><label>Zustand<input value={c.state||''} onChange={e=>setTrigger('state',e.target.value)} placeholder="on / off / open"/></label></>}{t==='transit_delay'&&<><SourceSelect label="VRN-Quelle" sources={transitSources} value={c.integration_source||''} onChange={v=>setTrigger('integration_source',v)}/><label>Verspätung mindestens (Min.)<input type="number" min="1" value={c.minutes??10} onChange={e=>setTrigger('minutes',Number(e.target.value))}/></label><label>Innerhalb Stunden<input type="number" min="1" value={c.within_hours??2} onChange={e=>setTrigger('within_hours',Number(e.target.value))}/></label></>}{t==='task_completed'&&<><label>Aufgabenliste<select value={c.task_list||''} onChange={e=>setTrigger('task_list',e.target.value)}><option value="">Alle Listen</option>{taskLists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Titel enthält<input value={c.title_contains||''} onChange={e=>setTrigger('title_contains',e.target.value)} placeholder="z. B. Waschmittel"/></label></>}</>}

function ActionFields({builder,setAction,homeSources,taskLists,shoppingLists}){const a=builder.action_type,c=builder.action_config;return <>{a==='task_create'&&<><label>Aufgabenliste<select value={c.task_list||''} onChange={e=>setAction('task_list',e.target.value)}><option value="">Standardliste</option>{taskLists.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Aufgabentitel<input value={c.title||''} onChange={e=>setAction('title',e.target.value)} placeholder="{event_title} erledigen" required/></label><label>Priorität<select value={c.priority||'normal'} onChange={e=>setAction('priority',e.target.value)}><option value="low">Niedrig</option><option value="normal">Normal</option><option value="high">Hoch</option></select></label></>}{a==='shopping_add'&&<><label>Einkaufsliste<select value={c.shopping_list||''} onChange={e=>setAction('shopping_list',e.target.value)}><option value="">Standardliste</option>{shoppingLists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Artikel<input value={c.name||''} onChange={e=>setAction('name',e.target.value)} placeholder="Artikelname oder {task_title}" required/></label><label>Menge<input value={c.quantity||''} onChange={e=>setAction('quantity',e.target.value)}/></label><label>Kategorie<input value={c.category||''} onChange={e=>setAction('category',e.target.value)}/></label></>}{a==='inbox_create'&&<><label>Titel<input value={c.title||''} onChange={e=>setAction('title',e.target.value)} placeholder="{event_title}" required/></label><label>Text<input value={c.body||''} onChange={e=>setAction('body',e.target.value)}/></label></>}{a==='home_service'&&<><SourceSelect label="Home Assistant" sources={homeSources} value={c.integration_source||''} onChange={v=>setAction('integration_source',v)}/><label>Domain<input value={c.domain||''} onChange={e=>setAction('domain',e.target.value)} placeholder="light" required/></label><label>Service<input value={c.service||''} onChange={e=>setAction('service',e.target.value)} placeholder="turn_on" required/></label><label>Entity<input value={c.entity_id||''} onChange={e=>setAction('entity_id',e.target.value)} placeholder="light.flur"/></label></>}{a==='push_notify'&&<><label>Push-Titel<input value={c.title||''} onChange={e=>setAction('title',e.target.value)} placeholder="{event_title}" required/></label><label>Nachricht<input value={c.body||''} onChange={e=>setAction('body',e.target.value)} placeholder="Details zur Benachrichtigung"/></label><label>Beim Tippen öffnen<select value={c.url||'/'} onChange={e=>setAction('url',e.target.value)}><option value="/">Startseite</option><option value="/?page=calendar">Kalender</option><option value="/?page=tasks">Aufgaben</option><option value="/?page=shopping">Einkauf</option><option value="/?page=automations">Wenn → Dann</option></select></label></>}</>}

function SourceSelect({label,sources,value,onChange}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)} required><option value="">Quelle auswählen …</option>{sources.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select>{!sources.length&&<small>Passende Integration zuerst unter „Integrationen“ verbinden.</small>}</label>}
function templateIcon(id){if(id.includes('frost'))return'frost';if(id.includes('rain'))return'rain';if(id.includes('warning'))return'warning';if(id.includes('transit'))return'transit';return'waste'}
function ruleIcon(trigger){if(trigger.includes('weather'))return trigger.includes('frost')?'frost':'rain';if(trigger.includes('warning'))return'warning';if(trigger.includes('waste'))return'waste';if(trigger.includes('home'))return'smartHome';if(trigger.includes('transit'))return'transit';if(trigger.includes('task'))return'tasks';return'automation'}
