import i18n from './ux-i18n';

const de={
 auto:{
  title:'Wenn → Dann',subtitle:'Automationen',active:'aktiv',intro:'Formuliere Familienregeln in vier einfachen Schritten. Technische Details erscheinen nur dort, wo sie wirklich nötig sind.',templates:'Schnellvorlagen',activate:'Aktivieren',ownRule:'Eigene Regel',step:'Schritt {{current}} von 4',restart:'Neu beginnen',createRule:'Regel erstellen',back:'Zurück',nextAction:'Weiter zur Aktion',yourRule:'DEINE REGEL',preview:'VORSCHAU',if:'Wenn',then:'dann',ruleName:'Name der Regel',optional:'optional',saveRule:'Regel speichern',rulesHistory:'Regeln & Historie',successful:'{{count}}× erfolgreich',errorLogged:'Fehler protokolliert',disable:'Deaktivieren',enable:'Aktivieren',disableRule:'Regel deaktivieren',enableRule:'Regel aktivieren',testRule:'Regel testen; die Aktion kann dabei wirklich ausgelöst werden',deleteRule:'Regel löschen',noRules:'Noch keine Regeln',noRulesHint:'Aktiviere eine Vorlage oder erstelle deine erste Wenn→Dann-Regel.',triggerQuestion:'Was soll die Regel auslösen?',triggerIntro:'Wähle zuerst einen Anlass aus dem Familienalltag.',actionQuestion:'Was soll fam-uh-le dann tun?',actionIntro:'Wenn „{{trigger}}“, dann …',noExtra:'Keine weiteren Angaben nötig',chooseSource:'Quelle auswählen …',missingIntegration:'Noch keine passende Integration verbunden.',setupIntegration:'Integration einrichten',loadFailed:'Automationen konnten nicht geladen werden.',templateEnabled:'Vorlage aktiviert.',templateFailed:'Vorlage konnte nicht aktiviert werden.',ruleDisabled:'Regel deaktiviert.',ruleEnabled:'Regel aktiviert.',ruleChangeFailed:'Regel konnte nicht geändert werden.',testQuestion:'Regel jetzt testen?',testWarning:'Der Test kann die konfigurierte Aktion wirklich ausführen, z. B. eine Aufgabe anlegen, Push senden oder Smart Home schalten.',runTest:'Test ausführen',testDone:'Regeltest ausgeführt.',testFailed:'Regeltest fehlgeschlagen.',deleteQuestion:'Regel löschen?',deleteMessage:'„{{name}}“ wird dauerhaft entfernt.',deleted:'Regel gelöscht.',deleteFailed:'Regel konnte nicht gelöscht werden.',saved:'Regel gespeichert.',saveFailed:'Regel konnte nicht gespeichert werden.',
  trigger:{waste_tomorrow:'Müllabfuhr ist morgen',weather_frost:'Frost wird erwartet',weather_rain:'Regenwahrscheinlichkeit ist hoch',warning_active:'Amtliche Warnung ist aktiv',event_upcoming:'Termin steht bevor',daily:'Täglich zu einer Uhrzeit',home_state:'Smart-Home-Zustand trifft zu',transit_delay:'ÖPNV ist verspätet',task_completed:'Aufgabe wurde erledigt'},
  triggerHelp:{waste_tomorrow:'Reagiere automatisch auf die nächste Müllabfuhr.',weather_frost:'Nutze Wetterdaten für Frostschutz und Erinnerungen.',weather_rain:'Reagiere auf eine hohe Regenwahrscheinlichkeit.',warning_active:'Reagiere auf amtliche oder regionale Warnungen.',event_upcoming:'Starte eine Aktion vor einem Kalender-, Schul- oder Mülltermin.',daily:'Führe eine Familienaktion jeden Tag zu einer festen Uhrzeit aus.',home_state:'Reagiere auf einen Zustand aus Home Assistant.',transit_delay:'Reagiere, wenn eine ÖPNV-Verbindung deutlich verspätet ist.',task_completed:'Starte etwas Neues, sobald eine passende Aufgabe erledigt wurde.'},
  action:{task_create:'Aufgabe anlegen',shopping_add:'Einkauf ergänzen',inbox_create:'Inbox-Hinweis anlegen',home_service:'Smart-Home-Aktion ausführen',push_notify:'Push-Benachrichtigung senden'},
  actionHelp:{task_create:'Lege automatisch eine Aufgabe für die Familie an.',shopping_add:'Füge einen Artikel in eine Einkaufsliste ein.',inbox_create:'Lege einen Hinweis in der Familien-Inbox ab.',home_service:'Rufe einen Home-Assistant-Dienst auf.',push_notify:'Sende eine Benachrichtigung an aktivierte Familiengeräte.'},
  steps:{occasion:'Anlass',condition:'Bedingung',action:'Aktion',preview:'Vorschau'},
  fields:{temperature:'Ab welcher Temperatur reagieren?',temperatureHelp:'Frost, wenn die Vorhersage gleich oder kälter ist.',lookAhead:'Wie weit voraus?',rainProbability:'Ab welcher Regenwahrscheinlichkeit?',time:'Uhrzeit',eventType:'Welche Terminart?',titleContains:'Nur wenn der Titel enthält',reactEarly:'Wie früh reagieren?',homeSource:'Welche Home-Assistant-Verbindung?',deviceDetails:'Technische Gerätedetails',entityId:'Entity-ID',entityHelp:'Kennung des Geräts oder Sensors, z. B. binary_sensor.tuer.',state:'Zustand',transitSource:'Welche ÖPNV-Quelle?',delay:'Ab welcher Verspätung?',period:'In welchem Zeitraum?',taskList:'Welche Aufgabenliste?',allLists:'Alle Listen',taskTitle:'Aufgabentitel',defaultList:'Standardliste',priority:'Priorität',item:'Artikel',shoppingList:'Welche Einkaufsliste?',quantity:'Menge',category:'Kategorie',text:'Text',smartHomeAction:'Smart-Home-Aktion',domain:'Bereich / Domain',domainHelp:'z. B. light, switch oder scene',service:'Aktion / Service',serviceHelp:'z. B. turn_on oder turn_off',entity:'Gerät / Entity',pushTitle:'Push-Titel',message:'Nachricht',openOnTap:'Beim Tippen öffnen'},
  eventTypes:{calendar:'Familien-/Kalendertermin',school:'Schule / Stundenplan',waste:'Müllabfuhr'},
  hoursAhead:'{{count}} Stunden',hourAhead:'1 Stunde vorher',hoursBefore:'{{count}} Stunden vorher',nextHour:'Nächste Stunde',nextHours:'Nächste {{count}} Stunden'
 }
};

const en={
 auto:{
  title:'If → Then',subtitle:'Automations',active:'active',intro:'Build family rules in four simple steps. Technical details only appear where they are actually needed.',templates:'Quick templates',activate:'Activate',ownRule:'Custom rule',step:'Step {{current}} of 4',restart:'Start over',createRule:'Create rule',back:'Back',nextAction:'Continue to action',yourRule:'YOUR RULE',preview:'PREVIEW',if:'If',then:'then',ruleName:'Rule name',optional:'optional',saveRule:'Save rule',rulesHistory:'Rules & history',successful:'{{count}}× successful',errorLogged:'Error logged',disable:'Disable',enable:'Enable',disableRule:'Disable rule',enableRule:'Enable rule',testRule:'Test rule; the configured action may actually run',deleteRule:'Delete rule',noRules:'No rules yet',noRulesHint:'Activate a template or create your first If→Then rule.',triggerQuestion:'What should trigger the rule?',triggerIntro:'Choose an event from everyday family life first.',actionQuestion:'What should fam-uh-le do then?',actionIntro:'If “{{trigger}}”, then …',noExtra:'No additional details needed',chooseSource:'Choose source …',missingIntegration:'No matching integration connected yet.',setupIntegration:'Set up integration',loadFailed:'Could not load automations.',templateEnabled:'Template activated.',templateFailed:'Could not activate template.',ruleDisabled:'Rule disabled.',ruleEnabled:'Rule enabled.',ruleChangeFailed:'Could not change rule.',testQuestion:'Test rule now?',testWarning:'The test can really execute the configured action, such as creating a task, sending push, or controlling smart home.',runTest:'Run test',testDone:'Rule test executed.',testFailed:'Rule test failed.',deleteQuestion:'Delete rule?',deleteMessage:'“{{name}}” will be permanently removed.',deleted:'Rule deleted.',deleteFailed:'Could not delete rule.',saved:'Rule saved.',saveFailed:'Could not save rule.',
  trigger:{waste_tomorrow:'Waste collection is tomorrow',weather_frost:'Frost is expected',weather_rain:'Rain probability is high',warning_active:'Official warning is active',event_upcoming:'Event is coming up',daily:'Daily at a set time',home_state:'Smart-home state matches',transit_delay:'Transit is delayed',task_completed:'Task was completed'},
  triggerHelp:{waste_tomorrow:'React automatically to the next waste collection.',weather_frost:'Use weather data for frost protection and reminders.',weather_rain:'React to a high probability of rain.',warning_active:'React to official or regional warnings.',event_upcoming:'Start an action before a calendar, school, or waste event.',daily:'Run a family action every day at a fixed time.',home_state:'React to a Home Assistant state.',transit_delay:'React when public transport is significantly delayed.',task_completed:'Start something new when a matching task is completed.'},
  action:{task_create:'Create task',shopping_add:'Add shopping item',inbox_create:'Create inbox note',home_service:'Run smart-home action',push_notify:'Send push notification'},
  actionHelp:{task_create:'Automatically create a task for the family.',shopping_add:'Add an item to a shopping list.',inbox_create:'Create a note in the family inbox.',home_service:'Call a Home Assistant service.',push_notify:'Send a notification to enabled family devices.'},
  steps:{occasion:'Trigger',condition:'Condition',action:'Action',preview:'Preview'},
  fields:{temperature:'React at which temperature?',temperatureHelp:'Frost when the forecast is at or below this value.',lookAhead:'How far ahead?',rainProbability:'React at which rain probability?',time:'Time',eventType:'Which event type?',titleContains:'Only if title contains',reactEarly:'How early?',homeSource:'Which Home Assistant connection?',deviceDetails:'Technical device details',entityId:'Entity ID',entityHelp:'Identifier of the device or sensor, e.g. binary_sensor.door.',state:'State',transitSource:'Which transit source?',delay:'Minimum delay?',period:'Which time window?',taskList:'Which task list?',allLists:'All lists',taskTitle:'Task title',defaultList:'Default list',priority:'Priority',item:'Item',shoppingList:'Which shopping list?',quantity:'Quantity',category:'Category',text:'Text',smartHomeAction:'Smart-home action',domain:'Domain',domainHelp:'e.g. light, switch or scene',service:'Service',serviceHelp:'e.g. turn_on or turn_off',entity:'Device / entity',pushTitle:'Push title',message:'Message',openOnTap:'Open on tap'},
  eventTypes:{calendar:'Family/calendar event',school:'School / timetable',waste:'Waste collection'},
  hoursAhead:'{{count}} hours',hourAhead:'1 hour before',hoursBefore:'{{count}} hours before',nextHour:'Next hour',nextHours:'Next {{count}} hours'
 }
};

i18n.addResourceBundle('de','translation',de,true,true);
i18n.addResourceBundle('en','translation',en,true,true);
export default i18n;
