import {useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';

const localInput=value=>{const date=value instanceof Date?value:new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};
const iso=value=>new Date(value).toISOString();

function Toggle({checked,onChange,label}){return <label className="baby-toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span><strong>{label}</strong></span></label>}

export default function BabyReportPanel({baby,t,canCare,canGrowth}){
 const [selected,setSelected]=useState(canGrowth?['growth','development']:canCare?['care']:[]);
 const [days,setDays]=useState('7');const [customStart,setCustomStart]=useState(localInput(new Date(Date.now()-7*86400000)));const [customEnd,setCustomEnd]=useState(localInput(new Date()));const [preview,setPreview]=useState(null);const [busy,setBusy]=useState(false);
 const [handoverPreset,setHandoverPreset]=useState('12h');const [handoverStart,setHandoverStart]=useState(localInput(new Date(Date.now()-12*3600000)));const [handoverEnd,setHandoverEnd]=useState(localInput(new Date()));const [handoverNote,setHandoverNote]=useState('');const [handover,setHandover]=useState(null);
 useEffect(()=>{setSelected(canGrowth?['growth','development']:canCare?['care']:[]);setPreview(null);setHandover(null)},[baby.id,canCare,canGrowth]);
 const choices=[...(canGrowth?[['growth',t('babyUi.growth')],['development',t('babyUi.development')]]:[]),...(canCare?[['care',t('babyUi.care')],['handover',t('babyUi.handover')]]:[])];
 const range=useMemo(()=>{const end=days==='custom'?iso(customEnd):new Date().toISOString();const start=days==='custom'?iso(customStart):new Date(Date.now()-Number(days)*86400000).toISOString();return{start,end}},[days,customStart,customEnd]);
 const query=()=>`sections=${encodeURIComponent(selected.join(','))}&start=${encodeURIComponent(range.start)}&end=${encodeURIComponent(range.end)}`;
 async function loadPreview(){if(!selected.length)return;setBusy(true);try{setPreview(await api(`/baby/profiles/${baby.id}/report/?${query()}&format=json`))}catch(error){toast(error.message||t('babyUi.error'),{type:'error'})}finally{setBusy(false)}}
 function handoverRange(){const end=new Date();if(handoverPreset==='custom')return{from:iso(handoverStart),to:iso(handoverEnd)};if(handoverPreset==='today'){const start=new Date();start.setHours(0,0,0,0);return{from:start.toISOString(),to:end.toISOString()}}if(handoverPreset==='18'){const start=new Date();start.setHours(18,0,0,0);if(start>end)start.setDate(start.getDate()-1);return{from:start.toISOString(),to:end.toISOString()}}return{from:new Date(Date.now()-Number(handoverPreset.replace('h',''))*3600000).toISOString(),to:end.toISOString()}}
 async function createHandover(){const value=handoverRange();setBusy(true);try{const row=await api(`/baby/profiles/${baby.id}/handover/`,{method:'POST',body:JSON.stringify({from_at:value.from,to_at:value.to,note:handoverNote})});setHandover(await api(`/baby/handover/${row.id}/`));toast(t('babyUi.created'),{type:'success'})}catch(error){toast(error.message||t('babyUi.error'),{type:'error'})}finally{setBusy(false)}}
 const disabled=!selected.length||busy;
 return <>
  <section className="card baby-panel"><h2>{t('babyUi.report')}</h2><p className="baby-reference-note">{t('babyUi.reportPrivacy')}</p><div className="baby-report-sections">{choices.map(([key,label])=><Toggle key={key} checked={selected.includes(key)} label={label} onChange={checked=>{setSelected(current=>checked?[...new Set([...current,key])]:current.filter(value=>value!==key));setPreview(null)}}/>)}</div>
   <label>{t('babyUi.reportPeriod')}<select value={days} onChange={e=>{setDays(e.target.value);setPreview(null)}}><option value="1">{t('babyUi.lastDay')}</option><option value="7">{t('babyUi.last7Days')}</option><option value="30">{t('babyUi.last30Days')}</option><option value="custom">{t('babyUi.customPeriod')}</option></select></label>{days==='custom'&&<div className="form-grid"><label>{t('babyUi.from')}<input type="datetime-local" value={customStart} onChange={e=>{setCustomStart(e.target.value);setPreview(null)}}/></label><label>{t('babyUi.to')}<input type="datetime-local" value={customEnd} onChange={e=>{setCustomEnd(e.target.value);setPreview(null)}}/></label></div>}
   <div className="baby-actions"><button className="secondary" disabled={disabled} onClick={loadPreview}><Icon name="receipt"/>{t('babyUi.preview')}</button><a className={`secondary ${disabled?'is-disabled':''}`} aria-disabled={disabled} tabIndex={disabled?-1:0} href={disabled?undefined:`/api/baby/profiles/${baby.id}/report/?${query()}&format=html`} target="_blank" rel="noreferrer"><Icon name="receipt"/>{t('babyUi.exportHtml')}</a><a className={`secondary ${disabled?'is-disabled':''}`} aria-disabled={disabled} tabIndex={disabled?-1:0} href={disabled?undefined:`/api/baby/profiles/${baby.id}/report/?${query()}&format=csv`}><Icon name="download"/>{t('babyUi.exportCsv')}</a></div>
   {preview&&<div className="baby-report-preview"><div className="baby-section-head"><h3>{t('babyUi.preview')}</h3><small>{new Date(preview.range.start).toLocaleString()} – {new Date(preview.range.end).toLocaleString()}</small></div><div className="baby-chip-row">{preview.sections.map(section=><span className="chip" key={section}>{choices.find(([key])=>key===section)?.[1]||section}</span>)}</div><p className="baby-reference-note">{preview.notice}</p></div>}
  </section>
  {canCare&&<section className="card baby-panel"><h2>{t('babyUi.handover')}</h2><div className="segmented">{[['18',t('babyUi.since18')],['12h',t('babyUi.last12Hours')],['today',t('babyUi.today')],['custom',t('babyUi.customPeriod')]].map(([value,label])=><button key={value} className={handoverPreset===value?'active':''} onClick={()=>setHandoverPreset(value)}>{label}</button>)}</div>{handoverPreset==='custom'&&<div className="form-grid"><label>{t('babyUi.from')}<input type="datetime-local" value={handoverStart} onChange={e=>setHandoverStart(e.target.value)}/></label><label>{t('babyUi.to')}<input type="datetime-local" value={handoverEnd} onChange={e=>setHandoverEnd(e.target.value)}/></label></div>}<textarea value={handoverNote} onChange={e=>setHandoverNote(e.target.value)} placeholder={t('babyUi.note')}/><button className="secondary" disabled={busy} onClick={createHandover}>{t('babyUi.createHandover')}</button>{handover&&<div className="baby-handover-summary"><div className="baby-chip-row">{Object.entries(handover.counts||{}).map(([key,value])=><span className="chip" key={key}>{t(`babyUi.${key}`,{defaultValue:key})}: {value}</span>)}{handover.totals?.bottle_ml!=null&&<span className="chip">{t('babyUi.bottle')}: {Math.round(handover.totals.bottle_ml)} ml</span>}<span className="chip">{t('babyUi.sleep')}: {handover.sleep_minutes||0} min</span></div><div className="baby-timeline">{(handover.events||[]).map(row=><div className="baby-event" key={row.id}><Icon name={row.kind==='sleep'?'clock':'heart'}/><div><strong>{t(`babyUi.${row.kind}`,{defaultValue:row.kind})}</strong><small>{new Date(row.started_at).toLocaleString()}</small></div></div>)}</div></div>}</section>}
 </>;
}
