import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import {requestCreate} from './create-request';
import BirthdayEditor from './BirthdayEditor';
import './birthday-i18n';
import './birthdays.css';

export default function BirthdaysHub({family,onBack}){
 const {t,i18n}=useTranslation();const [rows,setRows]=useState([]);const [canManage,setCanManage]=useState(false);const [selected,setSelected]=useState(null);const [editing,setEditing]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setError('');try{const result=await api(`/birthdays/?family=${family.id}`);const next=result.birthdays||[];setRows(next);setCanManage(!!result.can_manage);const key=new URLSearchParams(location.search).get('birthday');setSelected(current=>next.find(x=>x.key===(current?.key||key))||null)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[family?.id]);
 function select(row){const url=new URL(location.href);url.searchParams.set('birthday',row.key);history.pushState({...history.state,page:'birthdays'},'',url.pathname+url.search);setSelected(row)}
 function close(){const url=new URL(location.href);url.searchParams.delete('birthday');history.replaceState({...history.state},'',url.pathname+url.search);setSelected(null)}
 useEffect(()=>{const pop=()=>{const key=new URLSearchParams(location.search).get('birthday');setSelected(rows.find(x=>x.key===key)||null)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[rows]);
 async function edit(row){try{setEditing(await api(`/birthday-people/${row.id}/`))}catch(e){toast(e.message,{type:'error'})}}
 const label=row=>t(row.days_until===0?'birthdayUi.today':'birthdayUi.inDays',{name:row.name,count:row.days_until});
 return <section className="birthdays-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><h1 className="grow">{t('birthdayUi.title')}</h1></div><div className="birthday-actions">{canManage&&<button className="primary compact" onClick={()=>requestCreate('birthday')}><Icon name="plus"/>{t('birthdayUi.add')}</button>}<a className="secondary compact" href="/?page=profile">{t('birthdayUi.self')}</a></div>{loading&&<p role="status">{t('pleaseWait')}</p>}{error&&<div role="alert"><p>{error}</p><button onClick={load}>{t('sessionUi.retry')}</button></div>}{!loading&&!rows.length&&<div className="smart-empty"><Icon name="calendar"/><strong>{t('birthdayUi.empty')}</strong><span>{t('birthdayUi.emptyHint')}</span></div>}<div className="birthday-list">{rows.map((row,index)=><article className={`card birthday-card ${index===0?'birthday-next':''}`} key={row.key}><button className="birthday-main" onClick={()=>select(row)}><span className="round-icon"><Icon name="calendar"/></span><span className="grow"><strong>{label(row)}</strong><small>{new Intl.DateTimeFormat(i18n.language,{day:'numeric',month:'long'}).format(new Date(row.next_occurrence+'T12:00:00'))}{row.turning_age!==null&&row.turning_age!==undefined?` · ${t('birthdayUi.age',{age:row.turning_age})}`:''}{row.relation?` · ${row.relation}`:''}</small></span><Icon name="next"/></button>{row.can_plan&&<button className="birthday-plan-link" onClick={()=>select(row)}>{t(['ready','given'].includes(row.gift_status)?'birthdayUi.ready':'birthdayUi.plan')}</button>}{canManage&&row.kind==='person'&&<button className="icon-button" onClick={()=>edit(row)} aria-label={`${row.name}: ${t('birthdayUi.edit')}`}><Icon name="edit"/></button>}</article>)}</div><p className="family-note">{t('birthdayUi.leap')}</p>{selected&&<GiftSheet key={`${selected.key}:${selected.next_occurrence}`} row={selected} family={family} onClose={close} onSaved={load}/>} {editing&&<BirthdayEditor family={family} person={editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>}</section>
}

function GiftSheet({row,family,onClose,onSaved}){
 const {t}=useTranslation();const [idea,setIdea]=useState(row.idea_text||'');const [status,setStatus]=useState(row.gift_status||'none');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(action){if(busy)return;setBusy(true);setError('');try{const saved=await api('/birthday-gift-plans/',{method:'POST',body:JSON.stringify({family:family.id,birthday_key:row.key,idea_text:idea,status,action})});setStatus(saved.gift_status);await onSaved();toast(t('birthdayUi.giftSaved'),{type:'success'});if(!action)onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section className="quick-sheet" role="dialog" aria-modal="true" aria-labelledby="gift-title"><div className="sheet-head"><h2 id="gift-title">{row.name}</h2><button className="sheet-close" disabled={busy} onClick={onClose} aria-label={t('close')}><Icon name="close"/></button></div><p>{t(row.days_until===0?'birthdayUi.today':'birthdayUi.inDays',{name:row.name,count:row.days_until})}</p>{row.can_plan&&<form className="quick-form" onSubmit={e=>{e.preventDefault();save()}}><small>{t('birthdayUi.privacy')}</small><label>{t('birthdayUi.idea')}<textarea rows={3} value={idea} maxLength={4000} onChange={e=>setIdea(e.target.value)}/></label><label>{t('birthdayUi.status')}<select value={status} onChange={e=>setStatus(e.target.value)}>{['none','idea','planned','ordered','ready','given'].map(x=><option value={x} key={x}>{t(`birthdayUi.states.${x}`)}</option>)}</select></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{t(busy?'saving':'save')}</button><button type="button" className="secondary" disabled={busy||!!row.linked_task} onClick={()=>save('task')}><Icon name="tasks"/>{t('birthdayUi.task')}</button><button type="button" className="secondary" disabled={busy||!!row.linked_shopping_item} onClick={()=>save('shopping')}><Icon name="shopping"/>{t('birthdayUi.shopping')}</button></form>}</section></div>
}
