import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import {useDirtyForm} from './dirty-state';
import './birthday-i18n';

export default function BirthdayEditor({family,person,onClose,onSaved}){
 const {t}=useTranslation();const initial={name:person?.name||'',birth_day:person?.birth_day||'',birth_month:person?.birth_month||'',birth_year:person?.birth_year||'',relation:person?.relation||'',notes:person?.notes||''};const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 useDirtyForm(JSON.stringify(form)!==JSON.stringify(initial));
 async function save(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const payload={...form,family:family.id,birth_day:Number(form.birth_day),birth_month:Number(form.birth_month),birth_year:form.birth_year?Number(form.birth_year):null};const saved=await api(person?`/birthday-people/${person.id}/`:'/birthday-people/',{method:person?'PATCH':'POST',body:JSON.stringify(payload)});await onSaved(saved);toast(t('birthdayUi.saved'),{type:'success'})}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function deactivate(){setBusy(true);try{await api(`/birthday-people/${person.id}/`,{method:'PATCH',body:JSON.stringify({active:false})});await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section className="quick-sheet" role="dialog" aria-modal="true" aria-labelledby="birthday-editor-title"><div className="sheet-head"><h2 id="birthday-editor-title">{t(person?'birthdayUi.edit':'birthdayUi.add')}</h2><button className="sheet-close" disabled={busy} onClick={onClose} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>{t('birthdayUi.name')}<input value={form.name} maxLength={120} autoFocus required onChange={e=>set('name',e.target.value)}/></label><div className="birthday-date-fields"><label>{t('birthdayUi.day')}<input type="number" inputMode="numeric" min="1" max="31" required value={form.birth_day} onChange={e=>set('birth_day',e.target.value)}/></label><label>{t('birthdayUi.month')}<input type="number" inputMode="numeric" min="1" max="12" required value={form.birth_month} onChange={e=>set('birth_month',e.target.value)}/></label><label>{t('birthdayUi.year')}<input type="number" inputMode="numeric" min="1900" max={new Date().getFullYear()} value={form.birth_year} onChange={e=>set('birth_year',e.target.value)}/></label></div><small>{t('birthdayUi.unknownYear')}</small><label>{t('birthdayUi.relation')}<input value={form.relation} maxLength={120} onChange={e=>set('relation',e.target.value)}/></label><details><summary>{t('birthdayUi.notes')}</summary><label>{t('birthdayUi.notes')}<textarea value={form.notes} rows={3} onChange={e=>set('notes',e.target.value)}/></label></details>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{t(busy?'saving':'save')}</button>{person&&<button type="button" className="ghost-danger" onClick={deactivate} disabled={busy}>{t('birthdayUi.inactive')}</button>}</form></section></div>
}
