import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {useFamilyPermissions} from './family-permissions';
import {confirmAction} from './feedback';
import './board.css';

export default function BoardHub({family,onBack}){
 const {i18n}=useTranslation();const en=i18n.language.startsWith('en');
 const w=en?{title:'Family board',new:'New post',hint:'Share news and photos with your family.',text:'Message',photos:'Add photos',publish:'Publish',cancel:'Cancel',edit:'Edit',remove:'Delete',save:'Save',more:'Load more',empty:'Your family board is ready for its first post.',loading:'Loading …',confirm:'Delete this post?',limit:'Up to four JPEG, PNG or WebP images, 10 MB each. Photos are resized and metadata removed on the server.',back:'Back',failed:'Could not load posts. Try again.',retry:'Try again',removePhoto:'Remove photo',shared:'Visible to everyone in this family.'}:{title:'Schwarzes Brett',new:'Neuer Beitrag',hint:'Neuigkeiten und Fotos mit deiner Familie teilen.',text:'Mitteilung',photos:'Fotos hinzufügen',publish:'Veröffentlichen',cancel:'Abbrechen',edit:'Bearbeiten',remove:'Löschen',save:'Speichern',more:'Weitere laden',empty:'Euer Schwarzes Brett wartet auf den ersten Beitrag.',loading:'Wird geladen …',confirm:'Diesen Beitrag löschen?',limit:'Bis zu vier Bilder als JPEG, PNG oder WebP, je 10 MB. Fotos werden auf dem Server verkleinert und Metadaten entfernt.',back:'Zurück',failed:'Beiträge konnten nicht geladen werden.',retry:'Erneut versuchen',removePhoto:'Foto entfernen',shared:'Für alle Mitglieder dieser Familie sichtbar.'};
 const [rows,setRows]=useState([]),[next,setNext]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[compose,setCompose]=useState(false),[editing,setEditing]=useState(null),[text,setText]=useState(''),[files,setFiles]=useState([]),[busy,setBusy]=useState(false);
 const familyId=family?.id;
 async function load(path=`/board/?family=${familyId}`,append=false){setLoading(true);setError('');try{const data=await api(path);let incoming=data.results;const target=new URLSearchParams(location.search).get('post');if(!append&&target&&!incoming.some(row=>String(row.id)===target)){try{const focused=await api(`/board/${encodeURIComponent(target)}/?family=${familyId}`);incoming=[focused,...incoming]}catch{}}setRows(previous=>append?[...previous,...incoming]:incoming);if(target)setTimeout(()=>document.getElementById(`post-${target}`)?.scrollIntoView({block:'nearest'}),100);setNext(data.next?new URL(data.next,location.origin).pathname.replace(/^\/api/,'')+new URL(data.next,location.origin).search:null)}catch(e){setError(e.message||w.failed)}finally{setLoading(false)}}
 useEffect(()=>{if(familyId)load()},[familyId]);
 function close(){setCompose(false);setEditing(null);setText('');setFiles([]);setError('')}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(editing){await api(`/board/${editing.id}/`,{method:'PATCH',body:JSON.stringify({text})})}else{const body=new FormData();body.append('family',familyId);body.append('text',text);files.forEach(file=>body.append('images',file));await api('/board/',{method:'POST',body})}close();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removePhoto(image){setBusy(true);try{await api(`/board-images/${image.id}/`,{method:'DELETE'});setEditing(old=>({...old,images:old.images.filter(row=>row.id!==image.id)}));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(row){if(!await confirmAction({title:w.confirm,confirmLabel:w.remove,cancelLabel:w.cancel,danger:true}))return;setBusy(true);try{await api(`/board/${row.id}/`,{method:'DELETE'});setRows(old=>old.filter(p=>p.id!==row.id))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const {role}=useFamilyPermissions(family);const canPost=!!role&&role!=='guest';
 return <section className="board-hub"><header className="page-head"><button className="icon-btn" aria-label={w.back} onClick={onBack}><Icon name="back"/></button><div><h1>{w.title}</h1><p>{w.hint}</p></div></header>{canPost&&!compose&&<button className="primary" onClick={()=>{close();setCompose(true)}}>{w.new}</button>}
 {error&&<div role="alert" className="card board-error">{error} {!compose&&<button onClick={()=>load()}>{w.retry}</button>}</div>}
 {compose&&<form className="card board-compose" onSubmit={submit}><h2>{editing?w.edit:w.new}</h2><p>{w.shared}</p><label>{w.text}<textarea autoFocus rows={5} maxLength={10000} value={text} onChange={e=>setText(e.target.value)}/></label>{!editing&&<><label className="board-file">{w.photos}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const picked=Array.from(e.target.files||[]);if(picked.length+files.length>4||picked.some(f=>f.size>10*1024*1024)){setError(w.limit);e.target.value='';return}setFiles(old=>[...old,...picked]);e.target.value=''}}/></label><small>{w.limit}</small><ul className="board-files">{files.map((f,i)=><li key={`${f.name}-${i}`}><FilePreview file={f}/>{f.name}<button type="button" aria-label={`${w.removePhoto}: ${f.name}`} onClick={()=>setFiles(old=>old.filter((_,j)=>j!==i))}>×</button></li>)}</ul></>}{editing?.images?.length>0&&<div className="board-edit-photos">{editing.images.map(image=><div key={image.id}><img src={image.url} alt={w.photos}/><button type="button" className="secondary compact" disabled={busy} onClick={()=>removePhoto(image)}>{w.removePhoto}</button></div>)}</div>}<div className="board-actions"><button type="button" className="secondary" onClick={close} disabled={busy}>{w.cancel}</button><button className="primary" disabled={busy||(!text.trim()&&!files.length&&!editing?.images?.length)}>{busy?w.loading:editing?w.save:w.publish}</button></div></form>}
 <div className="board-posts">{rows.map(row=><article id={`post-${row.id}`} className="card board-post" key={row.id}><header><strong>{row.author_name}</strong><time dateTime={row.created_at}>{new Date(row.created_at).toLocaleString(en?'en-GB':'de-DE',{dateStyle:'medium',timeStyle:'short'})}</time></header>{row.text&&<p className="board-text">{row.text}</p>}{row.images?.length>0&&<div className="board-photos">{row.images.map((image,i)=><a key={image.id} href={image.url} target="_blank" rel="noreferrer" aria-label={`${w.photos} ${i+1}`}><img src={image.url} width={image.width} height={image.height} loading="lazy" alt={`${row.author_name} · ${i+1}`}/></a>)}</div>}<footer>{row.can_edit&&<button className="secondary compact" disabled={busy} onClick={()=>{setEditing(row);setText(row.text);setFiles([]);setCompose(true);window.scrollTo({top:0,behavior:'auto'})}}>{w.edit}</button>}{row.can_delete&&<button className="ghost-danger compact" disabled={busy} onClick={()=>remove(row)}>{w.remove}</button>}</footer></article>)}</div>
 {loading&&<p role="status">{w.loading}</p>}{!loading&&!error&&!rows.length&&<p className="card">{w.empty}</p>}{next&&<button className="secondary" disabled={loading} onClick={()=>load(next,true)}>{w.more}</button>}</section>
}

function FilePreview({file}){const [url,setUrl]=useState('');useEffect(()=>{const value=URL.createObjectURL(file);setUrl(value);return()=>URL.revokeObjectURL(value)},[file]);return url?<img className="board-file-preview" src={url} alt=""/>:null}
