import {useEffect,useMemo,useState} from 'react';
import i18n from './i18n';
import './calendar-i18n';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';
import {formatDateTime} from './locale';
import './calendar-hub.css';

const unwrap=x=>x?.results||x||[];
const localValue=value=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const iso=value=>value?new Date(value).toISOString():null;
const nativeEvent=e=>!e.source&&e.type==='calendar.event';
const sourceKey=e=>nativeEvent(e)?'family':e.type?.includes('warning')?'warning':e.type?.includes('waste')?'waste':e.type?.includes('weather')?'weather':e.type?.includes('transit')?'transit':e.type?.includes('school')?'school':'calendar';
const sourceLabelKey={family:'sourceFamily',warning:'sourceWarnings',waste:'sourceWaste',weather:'sourceWeather',transit:'sourceTransit',school:'sourceSchool',calendar:'sourceCalendar'};
const sourceIcons={family:'members',warning:'warning',waste:'waste',weather:'weather',transit:'transit',school:'school',calendar:'calendar'};
const sourceLabel=(key,t)=>t(`calendarUi.${sourceLabelKey[key]||'sourceCalendar'}`);

export default function CalendarHub({family,onBack,t}){
 const [events,setEvents]=useState([]);const [busy,setBusy]=useState(false);const [edit,setEdit]=useState(null);const [detail,setDetail]=useState(null);const [notice,setNotice]=useState('');const [filter,setFilter]=useState('all');const [showPast,setShowPast]=useState(false);
 const load=async()=>{const rows=unwrap(await api('/events/'));setEvents(rows.filter(x=>!family||x.family===family.id).sort((a,b)=>eventTime(a)-eventTime(b)))};
 useEffect(()=>{setShowPast(false);load().catch(e=>toast(e.message||t('saveFailed'),{type:'error'}))},[family?.id]);
 const filters=useMemo(()=>[...new Set(events.map(sourceKey))],[events]);
 const sourceFiltered=useMemo(()=>filter==='all'?events:events.filter(e=>sourceKey(e)===filter),[events,filter]);
 const hasPast=useMemo(()=>sourceFiltered.some(eventIsPast),[sourceFiltered]);
 const visible=useMemo(()=>showPast?sourceFiltered:sourceFiltered.filter(e=>!eventIsPast(e)),[sourceFiltered,showPast]);
 const grouped=useMemo(()=>groupByDay(visible),[visible]);
 function create(){const d=new Date();d.setMinutes(Math.ceil(d.getMinutes()/30)*30,0,0);const end=new Date(d.getTime()+60*60000);setEdit({title:'',starts_at:localValue(d),ends_at:localValue(end),location:'',description:'',recurrence:'',isNew:true})}
 function editEvent(e){setDetail(null);setEdit({id:e.id,title:e.title,starts_at:localValue(e.starts_at),ends_at:localValue(e.ends_at),location:e.payload?.location||'',description:e.payload?.description||'',recurrence:e.payload?.recurrence||'',isNew:false})}
 async function save(e){e.preventDefault();setBusy(true);setNotice('');try{const payload={family:family.id,type:'calendar.event',title:edit.title,starts_at:iso(edit.starts_at),ends_at:iso(edit.ends_at),actionable:false,payload:{location:edit.location,description:edit.description,recurrence:edit.recurrence,provider:'fam-uh-le'}};if(edit.isNew)await api('/events/',{method:'POST',body:JSON.stringify(payload)});else await api(`/events/${edit.id}/`,{method:'PATCH',body:JSON.stringify(payload)});const created=edit.isNew;setEdit(null);await load();toast(created?t('addEvent'):t('save'),{type:'success'})}catch(err){setNotice(err.message);toast(err.message||t('saveFailed'),{type:'error'})}finally{setBusy(false)}}
 async function remove(){if(!edit?.id)return;const ok=await confirmAction({title:t('deleteEvent'),message:`„${edit.title}“`,confirmLabel:t('deleteEvent'),danger:true});if(!ok)return;setBusy(true);try{await api(`/events/${edit.id}/`,{method:'DELETE'});setEdit(null);await load();toast(t('deleteEvent'),{type:'success'})}catch(err){setNotice(err.message);toast(err.message||t('saveFailed'),{type:'error'})}finally{setBusy(false)}}
 const language=i18n.language;
 return <div className="smart-page calendar-agenda"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{t('calendarUi.agenda')}</small><h1>{t('calendar')}</h1></div><button className="fab-inline" onClick={create} aria-label={t('addEvent')}><Icon name="plus"/></button></div><p className="page-intro">{t('calendarHint')}</p>{notice&&<div className="integration-notice" role="alert">{notice}</div>}
 {filters.length>1&&<div className="calendar-filters" aria-label={t('calendarUi.sources')}><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><Icon name="calendar"/> {t('all')}</button>{filters.map(key=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}><Icon name={sourceIcons[key]||'calendar'}/>{key==='family'?(family?.name||sourceLabel(key,t)):sourceLabel(key,t)}</button>)}</div>}
 {hasPast&&<div className="calendar-history-toggle"><button className="secondary compact" aria-pressed={showPast} onClick={()=>setShowPast(value=>!value)}><Icon name="calendar"/>{t(showPast?'calendarUi.hidePast':'calendarUi.showPast')}</button></div>}
 <div className="agenda-days">{grouped.length?grouped.map(([day,rows])=><section className="agenda-day" key={day}><div className="agenda-day-head"><div><small>{dayRelativeLabel(day,t,language)}</small><h2>{dayLongLabel(day,t,language)}</h2></div><span>{rows.length}</span></div><div className="agenda-list">{rows.map(e=><AgendaEvent key={e.id} event={e} family={family} t={t} language={language} onOpen={()=>setDetail(e)}/>)}</div></section>):<div className="smart-empty"><Icon name="calendar" size={34}/><strong>{t('noUpcoming')}</strong><span>{filter==='all'?t('calendarAddHint'):t('calendarUi.noSourceEntries')}</span>{filter!=='all'&&<button className="secondary compact" onClick={()=>setFilter('all')}>{t('calendarUi.showAllSources')}</button>}</div>}</div>
 {detail&&<EventDetail event={detail} family={family} t={t} language={language} onClose={()=>setDetail(null)} onEdit={nativeEvent(detail)?()=>editEvent(detail):null}/>} 
 {edit&&<div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setEdit(null)}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{family?.name}</small><h2>{edit.isNew?t('addEvent'):t('editEvent')}</h2></div><button className="sheet-close" onClick={()=>setEdit(null)} disabled={busy} aria-label={t('back')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>{t('eventTitle')}<input value={edit.title} onChange={e=>setEdit(v=>({...v,title:e.target.value}))} required autoFocus/></label><div className="form-grid"><label>{t('startsAt')}<input type="datetime-local" value={edit.starts_at} onChange={e=>setEdit(v=>({...v,starts_at:e.target.value}))} required/></label><label>{t('endsAt')}<input type="datetime-local" value={edit.ends_at} onChange={e=>setEdit(v=>({...v,ends_at:e.target.value}))}/></label></div><label>{t('location')}<input value={edit.location} onChange={e=>setEdit(v=>({...v,location:e.target.value}))}/></label><label>{t('notes')}<textarea value={edit.description} onChange={e=>setEdit(v=>({...v,description:e.target.value}))}/></label><label>{t('recurrence')}<select value={edit.recurrence} onChange={e=>setEdit(v=>({...v,recurrence:e.target.value}))}><option value="">{t('none')}</option><option value="weekly">{t('weekly')}</option><option value="monthly">{t('monthly')}</option><option value="yearly">{t('yearly')}</option></select></label><button className="primary" disabled={busy}><Icon name="check"/>{busy?t('pleaseWait'):t('save')}</button>{!edit.isNew&&<button type="button" className="ghost-danger destructive-wide" onClick={remove} disabled={busy}><Icon name="delete"/>{t('deleteEvent')}</button>}</form></section></div>}</div>
}

function AgendaEvent({event,family,t,language,onOpen}){const source=sourceKey(event);const native=nativeEvent(event);const warning=source==='warning';return <button className={`agenda-event ${warning?'agenda-warning':''}`} onClick={onOpen}><div className="agenda-time">{event.payload?.all_day?<strong>{t('calendarUi.allDay')}</strong>:<><strong>{formatTime(event.starts_at,language)}</strong>{event.ends_at&&<span>{formatEndTime(event,language)}</span>}</>}</div><span className={`agenda-source-icon source-${source}`}><Icon name={sourceIcons[source]||'calendar'}/></span><div className="grow agenda-event-main"><div className="agenda-title-line"><strong>{event.title}</strong>{event.payload?.delay_minutes>0&&<span className="delay-badge">+{event.payload.delay_minutes} min</span>}</div><div className="agenda-event-meta">{event.payload?.location&&<span><Icon name="location"/>{event.payload.location}</span>}<span className={`source-badge source-${source}`}><Icon name={sourceIcons[source]||'calendar'}/>{source==='family'?(family?.name||sourceLabel(source,t)):sourceLabel(source,t)}</span>{event.payload?.recurrence&&<span><Icon name="refresh"/> {recurrenceLabel(event.payload.recurrence,t)}</span>}</div></div><Icon name={native?'edit':'next'} className="agenda-affordance"/></button>}

function EventDetail({event,family,t,language,onClose,onEdit}){const source=sourceKey(event);const provider=nativeEvent(event)?'fam-uh-le':event.payload?.provider||event.source||event.type;return <div className="sheet-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`quick-sheet calendar-detail ${source==='warning'?'warning-detail':''}`} role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><span className={`source-badge source-${source}`}><Icon name={sourceIcons[source]||'calendar'}/>{source==='family'?(family?.name||sourceLabel(source,t)):sourceLabel(source,t)}</span><h2>{event.title}</h2></div><button className="sheet-close" onClick={onClose} aria-label={t('back')}><Icon name="close"/></button></div><div className="event-detail-body"><div className="event-detail-primary"><span className={`agenda-source-icon source-${source}`}><Icon name={sourceIcons[source]||'calendar'}/></span><div><strong>{formatFullDate(event,t,language)}</strong><span>{formatEventRange(event,t,language)}</span></div></div>{event.payload?.location&&<DetailRow icon="location" label={t('location')} value={event.payload.location}/>} {event.payload?.description&&<DetailRow icon="info" label={t('notes')} value={event.payload.description}/>} {event.payload?.recurrence&&<DetailRow icon="refresh" label={t('recurrence')} value={recurrenceLabel(event.payload.recurrence,t)}/>} {event.payload?.delay_minutes>0&&<DetailRow icon="transit" label={t('calendarUi.delay')} value={`+${event.payload.delay_minutes} ${t('calendarUi.minutes')}`}/>}<DetailRow icon="integrations" label={t('calendarUi.source')} value={provider}/></div>{onEdit?<button className="primary" onClick={onEdit}><Icon name="edit"/>{t('editEvent')}</button>:<div className="readonly-event-note"><Icon name="info"/><span>{t('calendarUi.readonly')}</span></div>}</section></div>}
function DetailRow({icon,label,value}){return <div className="event-detail-row"><Icon name={icon}/><div><small>{label}</small><span>{value}</span></div></div>}

function eventTime(event){return event.starts_at?new Date(event.starts_at).getTime():Number.MAX_SAFE_INTEGER}
function eventIsPast(event){if(!event.starts_at)return false;const boundary=event.ends_at||event.starts_at;return new Date(boundary).getTime()<Date.now()}
function dayKey(value){if(!value)return'undated';const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function groupByDay(events){const groups=new Map();events.forEach(event=>{const key=dayKey(event.starts_at);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(event)});return [...groups.entries()]}
function localDay(key){if(key==='undated')return null;const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d)}
function dayRelativeLabel(key,t,language){const date=localDay(key);if(!date)return t('calendarUi.undatedUpper');const today=new Date();today.setHours(0,0,0,0);const target=new Date(date);target.setHours(0,0,0,0);const diff=Math.round((target-today)/86400000);if(diff===0)return t('calendarUi.todayUpper');if(diff===1)return t('calendarUi.tomorrowUpper');if(diff===-1)return t('calendarUi.yesterdayUpper');return formatDateTime(language,date,{weekday:'long'}).toUpperCase()}
function dayLongLabel(key,t,language){const date=localDay(key);return date?formatDateTime(language,date,{day:'numeric',month:'long'}):t('calendarUi.undated')}
function formatTime(value,language){return value?formatDateTime(language,value,{hour:'2-digit',minute:'2-digit'}):'–'}
function formatEndTime(event,language){if(!event.ends_at)return'';const start=event.starts_at?new Date(event.starts_at):null,end=new Date(event.ends_at);if(start&&start.toDateString()!==end.toDateString())return formatDateTime(language,end,{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});return `– ${formatTime(event.ends_at,language)}`}
function formatFullDate(event,t,language){if(!event.starts_at)return t('calendarUi.noDate');return formatDateTime(language,event.starts_at,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function formatEventRange(event,t,language){if(event.payload?.all_day)return t('calendarUi.allDay');if(!event.starts_at)return'';return `${formatTime(event.starts_at,language)}${event.ends_at?` ${formatEndTime(event,language)}`:''}`}
function recurrenceLabel(value,t){return value==='weekly'?t('weekly'):value==='monthly'?t('monthly'):value==='yearly'?t('yearly'):value}