import {useEffect,useMemo,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import {useFamilyPermissions} from './family-permissions';
import './expenses-i18n';
import './expenses.css';

const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const memberName=member=>member?.display_name||member?.username||'—';
const dateOnly=value=>{if(!value)return new Date().toISOString().slice(0,10);try{return new Date(value).toISOString().slice(0,10)}catch{return String(value).slice(0,10)}};
const localMidday=date=>new Date(`${date}T12:00:00`).toISOString();

function initialValues(expense,splitType){
 const result={};
 for(const share of expense?.shares||[]){
  const original=share.split_value;
  if(splitType==='exact')result[share.member]=String(original??share.amount);
  else if(splitType==='percentage'&&Number(expense?.total_amount)>0)result[share.member]=original!==null&&original!==undefined?String(original):String((Number(share.amount)/Number(expense.total_amount)*100).toFixed(2));
  else if(splitType==='shares')result[share.member]=String(original??share.amount);
 }
 return result;
}
function formFrom(expense,members){
 const splitType=expense?.shares?.[0]?.split_type||'equal';
 return {
  title:expense?.merchant||expense?.title||'',amount:expense?.total_amount||'',date:expense?.extraction?.date||dateOnly(expense?.occurred_at),currency:expense?.currency||'EUR',paid_by:expense?.paid_by||'',
  participants:expense?.shares?.length?expense.shares.map(share=>String(share.member)):members.map(member=>String(member.id)),split_type:splitType,split_values:initialValues(expense,splitType),
 };
}
function confidenceLabel(value,t){if(value>=.82)return['good',t('expensesUi.confidenceHigh')];if(value>=.55)return['warn',t('expensesUi.confidenceMedium')];return['low',t('expensesUi.confidenceLow')]}

export default function ExpenseEditor({family,expense=null,onClose,onSaved}){
 const {t}=useTranslation();const members=family?.memberships||[];const {membership}=useFamilyPermissions(family);const isExisting=Boolean(expense?.id);const [stage,setStage]=useState(isExisting?'form':'capture');const [draft,setDraft]=useState(expense);const [form,setForm]=useState(()=>formFrom(expense,members));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [quality,setQuality]=useState(expense?.extraction?.quality_warnings||[]);const cancelled=useRef(false);
 useEffect(()=>()=>{cancelled.current=true},[]);
 useEffect(()=>{if(!form.paid_by&&membership?.id)setForm(value=>({...value,paid_by:String(membership.id)}))},[membership?.id,form.paid_by]);
 const extraction=draft?.extraction;const status=draft?.receipt_status;const confidences=extraction?.field_confidences||{};
 const receiptUrl=draft?.receipt_available?`${import.meta.env.VITE_API_BASE||'/api'}/expenses/${draft.id}/receipt-file/`:'';
 const selectedMembers=useMemo(()=>members.filter(member=>form.participants.includes(String(member.id))),[members,form.participants]);
 function mergeDetected(next){setDraft(next);setQuality(next?.extraction?.quality_warnings||quality);setForm(current=>({...current,title:next?.merchant||next?.title||current.title,amount:next?.total_amount||current.amount,date:next?.extraction?.date||dateOnly(next?.occurred_at)||current.date,currency:next?.currency||current.currency,paid_by:String(next?.paid_by||current.paid_by||'')}))}
 async function pollReceipt(id){for(let attempt=0;attempt<36&&!cancelled.current;attempt++){await sleep(attempt<8?500:900);if(cancelled.current)return;try{const next=await api(`/expenses/${id}/`);mergeDetected(next);if(['review','failed','ready'].includes(next.receipt_status)){setStage('form');return}}catch(err){setError(err.message);setStage('form');return}}setStage('form')}
 async function upload(file){if(!file)return;setBusy(true);setError('');setStage('processing');try{const body=new FormData();body.append('family',family.id);body.append('receipt',file);const created=await api('/expenses/receipt/',{method:'POST',body});mergeDetected(created);setQuality(created.quality_warnings||[]);setBusy(false);await pollReceipt(created.id)}catch(err){setError(err.message);setBusy(false);setStage('capture')}}
 function toggleMember(id){setForm(value=>{const key=String(id);const selected=value.participants.includes(key);const participants=selected?value.participants.filter(item=>item!==key):[...value.participants,key];const split_values={...value.split_values};if(selected)delete split_values[key];return{...value,participants,split_values}})}
 function changeSplit(type){setForm(value=>({...value,split_type:type,split_values:type==='equal'?{}:{...value.split_values}}))}
 async function retry(){if(!draft?.id)return;setBusy(true);setError('');try{await api(`/expenses/${draft.id}/retry-receipt/`,{method:'POST',body:'{}'});setDraft(value=>({...value,receipt_status:'queued'}));setStage('processing');setBusy(false);await pollReceipt(draft.id)}catch(err){setError(err.message);setBusy(false);setStage('form')}}
 async function removeReceipt(){if(!draft?.id)return;try{await api(`/expenses/${draft.id}/receipt-file/`,{method:'DELETE'});setDraft(value=>({...value,receipt_available:false}));toast(t('expensesUi.removeReceipt'),{type:'success'})}catch(err){setError(err.message)}}
 async function close(){if(!isExisting&&draft?.id&&draft?.status==='draft'){try{await api(`/expenses/${draft.id}/`,{method:'DELETE'})}catch{}}onClose()}
 async function save(event){event.preventDefault();if(!form.participants.length){setError(t('expensesUi.selectAtLeastOne'));return}setBusy(true);setError('');const payload={family:family.id,title:form.title.trim()||t('expensesUi.add'),merchant:form.title.trim(),total_amount:form.amount,currency:form.currency,occurred_at:localMidday(form.date),paid_by:form.paid_by||undefined,participants:form.participants,split_type:form.split_type,split_values:form.split_type==='equal'?undefined:form.split_values};try{let saved;if(draft?.id&&draft?.status==='draft')saved=await api(`/expenses/${draft.id}/`,{method:'PATCH',body:JSON.stringify({...payload,finalize:true})});else if(isExisting)saved=await api(`/expenses/${expense.id}/`,{method:'PATCH',body:JSON.stringify(payload)});else saved=await api('/expenses/',{method:'POST',body:JSON.stringify(payload)});setDraft(saved);toast(t('expensesUi.save'),{type:'success'});await onSaved?.(saved)}catch(err){setError(err.message);setBusy(false)}}
 return <div className="sheet-backdrop expense-sheet-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)close()}}><section className="quick-sheet expense-sheet" role="dialog" aria-modal="true" aria-labelledby="expense-editor-title"><div className="sheet-handle"/><div className="sheet-head"><div><small>{family?.name}</small><h2 id="expense-editor-title">{isExisting?t('expensesUi.edit'):t('expensesUi.addExpense')}</h2></div><button className="sheet-close" onClick={close} disabled={busy} aria-label={t('expensesUi.close')}><Icon name="close"/></button></div>
 {stage==='capture'&&<div className="expense-capture"><div className="receipt-hero"><Icon name="receipt" size={34}/><strong>{t('expensesUi.photo')}</strong><span>{t('expensesUi.captureHint')}</span></div><label className="primary receipt-upload"><Icon name="camera"/> {t('expensesUi.photo')}<input type="file" accept="image/*" capture="environment" onChange={event=>upload(event.target.files?.[0])}/></label><label className="secondary receipt-upload"><Icon name="upload"/> {t('expensesUi.chooseFile')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files?.[0])}/></label><button className="text-button manual-expense" onClick={()=>setStage('form')}><Icon name="edit"/>{t('expensesUi.manual')}</button>{error&&<p className="error" role="alert">{error}</p>}</div>}
 {stage==='processing'&&<div className="expense-processing" role="status"><span className="receipt-spinner"><Icon name="refresh" size={30}/></span><strong>{status==='queued'?t('expensesUi.queued'):t('expensesUi.processing')}</strong><span>{t('expensesUi.captureHint')}</span>{quality.map(item=><small key={item}>{item==='dark'?t('expensesUi.qualityDark'):t('expensesUi.qualityLowResolution')}</small>)}</div>}
 {stage==='form'&&<form className="quick-form expense-form" onSubmit={save}>{draft?.source==='receipt'&&<div className={`receipt-review-status ${status==='failed'?'failed':''}`}><Icon name={status==='failed'?'warning':'receipt'}/><div><strong>{status==='failed'?t('expensesUi.ocrFailed'):t('expensesUi.review')}</strong><span>{t('expensesUi.reviewHint')}</span></div>{status==='failed'&&<button type="button" className="secondary compact" onClick={retry} disabled={busy}><Icon name="refresh"/>{t('expensesUi.retryOcr')}</button>}</div>}{quality.map(item=><p className="receipt-quality" key={item}><Icon name="warning"/>{item==='dark'?t('expensesUi.qualityDark'):t('expensesUi.qualityLowResolution')}</p>)}{receiptUrl&&<div className="receipt-preview"><img src={receiptUrl} alt=""/><span><Icon name="lock"/>{t('expensesUi.receiptStored')}</span><button type="button" className="text-button" onClick={removeReceipt}>{t('expensesUi.removeReceipt')}</button></div>}
 <label>{t('expensesUi.merchant')}<span className="field-with-confidence"><input value={form.title} onChange={event=>setForm(value=>({...value,title:event.target.value}))} required autoFocus/>{draft?.source==='receipt'&&<Confidence value={confidences.merchant} t={t}/>}</span></label><div className="form-grid"><label>{t('expensesUi.amount')}<span className="field-with-confidence"><input type="number" min="0.01" step="0.01" inputMode="decimal" value={form.amount} onChange={event=>setForm(value=>({...value,amount:event.target.value}))} required/>{draft?.source==='receipt'&&<Confidence value={confidences.total} t={t}/>}</span></label><label>{t('expensesUi.currency')}<select value={form.currency} onChange={event=>setForm(value=>({...value,currency:event.target.value}))}><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></label></div><label>{t('expensesUi.date')}<span className="field-with-confidence"><input type="date" value={form.date} onChange={event=>setForm(value=>({...value,date:event.target.value}))} required/>{draft?.source==='receipt'&&<Confidence value={confidences.date} t={t}/>}</span></label><label>{t('expensesUi.paidBy')}<select value={form.paid_by} onChange={event=>setForm(value=>({...value,paid_by:event.target.value}))} required><option value="" disabled>—</option>{members.map(member=><option key={member.id} value={member.id}>{memberName(member)}</option>)}</select></label><fieldset className="expense-participants"><legend>{t('expensesUi.participants')}</legend><div className="participant-chips">{members.map(member=>{const active=form.participants.includes(String(member.id));return <button type="button" key={member.id} className={active?'active':''} aria-pressed={active} onClick={()=>toggleMember(member.id)}><span>{memberName(member).slice(0,1).toUpperCase()}</span>{memberName(member)}{active&&<Icon name="check" size={12}/>}</button>})}</div></fieldset><fieldset className="expense-split"><legend>{t('expensesUi.split')}</legend><div className="split-tabs">{[['equal','equal'],['exact','exact'],['percentage','percentage'],['shares','shares']].map(([id,key])=><button key={id} type="button" className={form.split_type===id?'active':''} onClick={()=>changeSplit(id)}>{t(`expensesUi.${key}`)}</button>)}</div>{form.split_type!=='equal'&&<div className="split-values">{selectedMembers.map(member=><label key={member.id}><span>{memberName(member)}</span><input type="number" min="0" step={form.split_type==='shares'?'0.1':'0.01'} value={form.split_values[member.id]||''} onChange={event=>setForm(value=>({...value,split_values:{...value.split_values,[member.id]:event.target.value}}))} required/></label>)}</div>}</fieldset>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!form.title.trim()||!form.amount||!form.participants.length}><Icon name="check"/>{busy?t('expensesUi.saving'):t('expensesUi.save')}</button></form>}</section></div>
}

function Confidence({value=0,t}){if(!value)return null;const [tone,label]=confidenceLabel(Number(value),t);return <small className={`confidence ${tone}`} title={`${t('expensesUi.confidence')}: ${Math.round(Number(value)*100)}%`}>{Math.round(Number(value)*100)}% · {label}</small>}
