import i18n from './create-i18n';

const de={expensesUi:{
 title:'Ausgaben',subtitle:'Gemeinsam zahlen, ohne Buchhaltungsgefühl.',add:'Ausgabe',addExpense:'Ausgabe hinzufügen',photo:'Beleg fotografieren',chooseFile:'Bild auswählen',manual:'Ohne Beleg eingeben',captureHint:'Foto hochladen – Rapporter liest Betrag, Händler und Datum serverseitig aus.',processing:'Beleg wird gelesen …',queued:'Beleg wartet auf Verarbeitung …',review:'Kurz prüfen',reviewHint:'Erkannte Angaben prüfen, Beteiligte bestätigen und speichern.',ocrFailed:'Der Beleg konnte nicht zuverlässig gelesen werden. Du kannst die Angaben trotzdem manuell ergänzen.',retryOcr:'Noch einmal lesen',merchant:'Händler / Titel',amount:'Betrag',date:'Datum',currency:'Währung',paidBy:'Bezahlt von',participants:'Für wen?',split:'Aufteilen',equal:'Gleichmäßig',exact:'Exakte Beträge',percentage:'Prozent',shares:'Anteile',save:'Ausgabe speichern',saving:'Speichert …',confidence:'Erkennung',confidenceHigh:'sicher',confidenceMedium:'prüfen',confidenceLow:'unsicher',qualityDark:'Das Foto ist recht dunkel.',qualityLowResolution:'Das Foto hat eine niedrige Auflösung.',balance:'Euer Stand',allSettled:'Alles ausgeglichen',owes:'schuldet',gets:'bekommt',settle:'Abrechnen',settleHint:'Rapporter dokumentiert die Abrechnung nur. Es wird kein Geld übertragen.',markSettled:'Als abgerechnet markieren',recent:'Letzte Ausgaben',noExpenses:'Noch keine gemeinsamen Ausgaben.',paid:'bezahlt von {{name}}',delete:'Ausgabe löschen',deleteQuestion:'Ausgabe löschen?',deleted:'Ausgabe gelöscht.',settlements:'Abrechnungen',undoSettlement:'Abrechnung stornieren',settlementRecorded:'Abrechnung dokumentiert.',settlementVoided:'Abrechnung storniert.',edit:'Ausgabe bearbeiten',receiptStored:'Beleg geschützt gespeichert',removeReceipt:'Beleg löschen',close:'Schließen',advanced:'Andere Aufteilung',selectAtLeastOne:'Mindestens eine Person auswählen.',sumMismatch:'Die Aufteilung muss zum Gesamtbetrag passen.',openAmount:'{{amount}} offen',forCurrency:'Saldo in {{currency}}',back:'Zurück',detected:'Erkannt',corrected:'Korrigierbar'
}};
const en={expensesUi:{
 title:'Expenses',subtitle:'Share spending without turning it into bookkeeping.',add:'Expense',addExpense:'Add expense',photo:'Take receipt photo',chooseFile:'Choose image',manual:'Enter without receipt',captureHint:'Upload a photo – Rapporter reads total, merchant and date on the server.',processing:'Reading receipt …',queued:'Receipt is queued …',review:'Quick review',reviewHint:'Check detected fields, confirm participants, and save.',ocrFailed:'The receipt could not be read reliably. You can still enter the details manually.',retryOcr:'Read again',merchant:'Merchant / title',amount:'Amount',date:'Date',currency:'Currency',paidBy:'Paid by',participants:'For whom?',split:'Split',equal:'Equally',exact:'Exact amounts',percentage:'Percent',shares:'Shares',save:'Save expense',saving:'Saving …',confidence:'Detection',confidenceHigh:'confident',confidenceMedium:'review',confidenceLow:'uncertain',qualityDark:'The photo is quite dark.',qualityLowResolution:'The photo has low resolution.',balance:'Your balance',allSettled:'All settled',owes:'owes',gets:'gets',settle:'Settle up',settleHint:'Rapporter only records the settlement. No money is transferred.',markSettled:'Mark as settled',recent:'Recent expenses',noExpenses:'No shared expenses yet.',paid:'paid by {{name}}',delete:'Delete expense',deleteQuestion:'Delete expense?',deleted:'Expense deleted.',settlements:'Settlements',undoSettlement:'Void settlement',settlementRecorded:'Settlement recorded.',settlementVoided:'Settlement voided.',edit:'Edit expense',receiptStored:'Receipt stored securely',removeReceipt:'Delete receipt',close:'Close',advanced:'Other split',selectAtLeastOne:'Select at least one person.',sumMismatch:'The split must match the total.',openAmount:'{{amount}} open',forCurrency:'Balance in {{currency}}',back:'Back',detected:'Detected',corrected:'Editable'
}};

i18n.addResourceBundle('de','translation',de,true,true);
i18n.addResourceBundle('en','translation',en,true,true);
export default i18n;
