import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { api } from './api';
import { Icon } from './icons';

const unwrap=x=>x?.results||x||[];

export default function FamilyMembers({family,onBack}){
 const {t}=useTranslation();const members=family?.memberships||[];const [invites,setInvites]=useState([]);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [form,setForm]=useState({display_name:'',email:'',role:'adult'});
 const load=()=>api('/invitations/').then(x=>setInvites(unwrap(x).filter(i=>i.family===family?.id)));
 useEffect(()=>{if(family)load()},[family?.id]);
 async function create(e){e.preventDefault();setBusy(true);setNotice('');try{const expires=new Date(Date.now()+7*86400000).toISOString();const invite=await api('/invitations/',{method:'POST',body:JSON.stringify({family:family.id,display_name:form.display_name,email:form.email,role:form.role,expires_at:expires})});setShow(false);setForm({display_name:'',email:'',role:'adult'});await load();await share(invite)}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 function url(invite){return `${window.location.origin}/invite/${invite.token}`}
 async function share(invite){const link=url(invite);try{if(navigator.share){await navigator.share({title:`fam-uh-le · ${family.name}`,text:t('inviteShareText',{family:family.name}),url:link});setNotice(t('inviteShared'))}else{await navigator.clipboard.writeText(link);setNotice(t('linkCopied'))}}catch(e){if(e?.name!=='AbortError')setNotice(t('copyFailed'))}}
 async function copy(invite){try{await navigator.clipboard.writeText(url(invite));setNotice(t('linkCopied'))}catch{setNotice(t('copyFailed'))}}
 async function revoke(invite){if(!confirm(t('revokeInviteConfirm')))return;setBusy(true);try{await api(`/invitations/${invite.id}/`,{method:'DELETE'});await load();setNotice(t('inviteRevoked'))}finally{setBusy(false)}}
 return <><div className="page-head"><button className="back-button" onClick={onBack}><Icon name="back"/></button><h1 className="grow">{t('members')}</h1><button className="fab-inline" onClick={()=>setShow(true)}><Icon name="plus"/></button></div><p className="page-intro">{t('membersHint')}</p>{notice&&<div className="integration-notice">{notice}</div>}
 <section className="card">{members.length?members.map(m=><div className="member-row" key={m.id}><div className="avatar">{(m.display_name||m.username||'?').slice(0,1).toUpperCase()}</div><div className="grow"><strong>{m.display_name||m.username}</strong><span>{t(m.role)||m.role}</span></div><span className="role-pill">{m.role}</span></div>):<div className="empty">{t('noData')}</div>}</section>
 <div className="section-title"><h2>{t('pendingInvites')}</h2></div><div className="stack">{invites.filter(i=>i.active).length?invites.filter(i=>i.active).map(i=><section className="card" key={i.id}><div className="member-row"><div className="avatar"><Icon name="link"/></div><div className="grow"><strong>{i.display_name||i.email||t('inviteLink')}</strong><span>{t(i.role)||i.role} · {new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(i.expires_at))}</span></div></div><div className="action-row"><button onClick={()=>share(i)}><Icon name="share"/>{t('share')}</button><button onClick={()=>copy(i)}><Icon name="copy"/>{t('copyLink')}</button><button className="ghost-danger" onClick={()=>revoke(i)} disabled={busy}><Icon name="delete"/>{t('revoke')}</button></div></section>):<div className="empty">{t('noPendingInvites')}</div>}</div>
 {show&&<div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setShow(false)}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{family?.name}</small><h2>{t('invitePerson')}</h2></div><button className="sheet-close" onClick={()=>setShow(false)} disabled={busy}><Icon name="close"/></button></div><form className="quick-form" onSubmit={create}><label>{t('displayName')}<input value={form.display_name} onChange={e=>setForm(f=>({...f,display_name:e.target.value}))} autoFocus placeholder={t('optional')}/></label><label>{t('emailOptional')}<input type="email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></label><label>{t('role')}<select value={form.role} onChange={e=>setForm(f=>({...f,role:e.target.value}))}><option value="adult">{t('adult')}</option><option value="teen">{t('teen')}</option><option value="child">{t('child')}</option><option value="guest">{t('guest')}</option></select></label><p className="page-intro">{t('inviteExpiryHint')}</p><button className="primary" disabled={busy}>{busy?t('pleaseWait'):t('createInvite')}</button></form></section></div>}</>
}
