import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { api } from './api';
import { Icon } from './icons';
import {confirmAction,toast} from './feedback';
import './integration-hub.css';

const unwrap=x=>x?.results||x||[];
const groups={waste:'waste',warning:'warnings',weather:'weather',ics:'calendars',messenger:'messengers',home:'smartHome',transit:'transit',school:'school'};
const kindIcons={waste:'waste',warning:'warning',weather:'weather',ics:'calendar',messenger:'inbox',home:'smartHome',transit:'transit',school:'school'};

export default function IntegrationHub({family,onBack}){
 const {t}=useTranslation();
 const [catalog,setCatalog]=useState([]);const [items,setItems]=useState([]);const [busy,setBusy]=useState('');const [selected,setSelected]=useState(null);const [notice,setNotice]=useState('');
 const load=async()=>{if(!family)return;const [c,i]=await Promise.all([api('/integration-hub/catalog/'),api('/integrations/')]);setCatalog(c);setItems(unwrap(i).filter(x=>x.family===family.id))};
 useEffect(()=>{load().catch(e=>toast(e.message||t('connectionFailed'),{type:'error'}));const q=new URLSearchParams(location.search);if(q.get('integration_connected'))toast(`${q.get('integration_connected')} verbunden.`,{type:'success'});if(q.get('integration_error'))toast(q.get('integration_error'),{type:'error'});if(q.has('integration_connected')||q.has('integration_error'))history.replaceState({},'',location.pathname)},[family?.id]);
 const connectedAdapters=useMemo(()=>new Set(items.map(x=>x.config?.adapter).filter(Boolean)),[items]);
 async function sync(x){setBusy(x.id);setNotice('');try{const r=await api(`/integration-hub/${x.id}/sync/`,{method:'POST',body:'{}'});toast(`${x.name}: ${r.synced} ${t('syncedItems')}`,{type:'success'})}catch(e){const message=e.message||t('connectionFailed');setNotice(message);toast(message,{type:'error'})}finally{await load();setBusy('')}}
 async function syncAll(){setBusy('all');setNotice('');try{const r=await api('/integration-hub/sync-all/',{method:'POST',body:'{}'});const message=`${r.synced} ${t('syncedItems')}${r.errors?.length?` · ${r.errors.length} ${t('errors')}`:''}`;toast(message,{type:r.errors?.length?'warning':'success'})}catch(e){toast(e.message||t('connectionFailed'),{type:'error'})}finally{await load();setBusy('')}}
 async function remove(x){const ok=await confirmAction({title:`${t('disconnect')}?`,message:`${x.name} wird von fam-uh-le getrennt. Bereits synchronisierte Familieninhalte bleiben erhalten, sofern der jeweilige Bereich sie gespeichert hat.`,confirmLabel:t('disconnect'),danger:true});if(!ok)return;setBusy(x.id);try{await api(`/integrations/${x.id}/`,{method:'DELETE'});await load();toast(`${x.name} getrennt.`,{type:'success'})}catch(e){toast(e.message||t('connectionFailed'),{type:'error'})}finally{setBusy('')}}
 async function startOAuth(item){setBusy(item.id);setNotice('');try{const r=await api('/integration-oauth/start/',{method:'POST',body:JSON.stringify({family:family.id,provider:item.oauth_provider})});location.assign(r.authorization_url)}catch(e){const message=e.message||t('connectionFailed');setNotice(message);toast(message,{type:'error'});setBusy('')}}
 return <><div className="page-head"><button className="back-button" onClick={onBack}><Icon name="back"/></button><h1 className="grow">{t('integrations')}</h1><button className="small-action" onClick={syncAll} disabled={busy==='all'}><Icon name="refresh"/>{t('syncAll')}</button></div><p className="page-intro">{t('integrationsHint')}</p>{notice&&<div className="integration-notice" role="alert">{notice}</div>}
 <h2 className="integration-section-title">{t('activeIntegrations')}</h2><div className="stack">{items.length?items.map(x=><section className={`card integration-card sync-${x.last_sync_status||'never'}`} key={x.id}><div className="integration-row"><div className="round-icon"><Icon name={kindIcons[x.kind]||'integrations'}/></div><div className="grow"><div className="integration-name-line"><strong>{x.name}</strong><SyncBadge status={x.last_sync_status} t={t}/></div><span>{t(groups[x.kind]||x.kind)} · {x.enabled?t('enabled'):t('disabled')}</span><small>{t('lastSync')}: {x.last_success_at||x.last_synced_at?new Intl.DateTimeFormat(undefined,{dateStyle:'short',timeStyle:'short'}).format(new Date(x.last_success_at||x.last_synced_at)):t('never')}</small>{x.last_sync_error&&<small className="sync-error"><Icon name="warning"/> {x.last_sync_error}</small>}{x.next_sync_at&&x.last_sync_status==='error'&&<small>{t('autoRetry')}: {new Intl.DateTimeFormat(undefined,{dateStyle:'short',timeStyle:'short'}).format(new Date(x.next_sync_at))}</small>}</div><button className="small-action" onClick={()=>sync(x)} disabled={busy===x.id}><Icon name="refresh"/>{t('sync')}</button><button className="icon-button" onClick={()=>remove(x)} disabled={busy===x.id} aria-label={t('disconnect')}><Icon name="delete"/></button></div></section>):<div className="empty">{t('noIntegrations')}</div>}</div>
 <h2 className="integration-section-title">{t('addIntegration')}</h2>{Object.entries(groupCatalog(catalog)).map(([kind,rows])=><div key={kind} className="integration-group"><h3><Icon name={kindIcons[kind]||'integrations'}/> {t(groups[kind]||kind)}</h3><div className="stack">{rows.map(x=><section className="card catalog-card" key={x.id}><div className="catalog-top"><div className="round-icon"><Icon name={kindIcons[x.kind]||'integrations'}/></div><div className="grow"><strong>{x.name}</strong><p>{x.description}</p>{x.oauth_provider&&x.oauth_ready===false&&<small className="secret-notice">{t('oauthSetupFirst')}</small>}</div>{connectedAdapters.has(x.defaults?.adapter)&&<span className="role-pill">{t('connected')}</span>}</div><div className="catalog-actions">{x.help_url&&<a className="text-link" href={x.help_url} target="_blank" rel="noreferrer"><Icon name="link"/>{t('openProvider')}</a>}{x.oauth_provider?<button className="primary compact" onClick={()=>startOAuth(x)} disabled={busy===x.id||x.oauth_ready===false}><Icon name="link"/>{t('connect')}</button>:<button className="primary compact" onClick={()=>setSelected(x)}><Icon name="settings"/>{t('configure')}</button>}</div></section>)}</div></div>)}
 {selected&&<ConnectSheet item={selected} family={family} t={t} onClose={()=>setSelected(null)} onConnected={async()=>{setSelected(null);toast(t('connectionSuccess'),{type:'success'});await load()}}/>}</>
}

function SyncBadge({status='never',t}){const key=status==='success'?'syncHealthy':status==='error'?'syncError':status==='running'?'syncRunning':'never';return <span className={`sync-badge ${status}`}><Icon name={status==='success'?'check':status==='error'?'warning':'refresh'} size={11}/>{t(key)}</span>}
function groupCatalog(items){return items.reduce((acc,x)=>{(acc[x.kind]??=[]).push(x);return acc},{})}

function ConnectSheet({item,family,t,onClose,onConnected}){
 const initial={};for(const f of item.fields||[])initial[f.key]=f.default??'';
 const [values,setValues]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('/integration-hub/connect/',{method:'POST',body:JSON.stringify({family:family.id,catalog_id:item.id,values})});await onConnected()}catch(e){const message=e.message||t('connectionFailed');setError(message);toast(message,{type:'error'});setBusy(false)}}
 const waste=item.id?.startsWith('waste_');
 return <div className="sheet-backdrop"><section className="quick-sheet integration-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('configure')}</small><h2>{item.name}</h2></div><button className="sheet-close" onClick={onClose} disabled={busy}><Icon name="close"/></button></div><p className="page-intro">{item.description}</p>{waste&&<div className="helper-box"><Icon name="warning"/><span>{t('addressCalendarHint')}</span></div>}{item.help_url&&<a className="provider-button" href={item.help_url} target="_blank" rel="noreferrer"><Icon name="link"/>{t('openProvider')}</a>}<form className="quick-form" onSubmit={submit}>{(item.fields||[]).map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} value={values[f.key]??''} onChange={e=>setValues(v=>({...v,[f.key]:f.type==='number'?Number(e.target.value):e.target.value}))} required={!!f.required} placeholder={f.default??''}/></label>)}{((item.fields||[]).some(f=>f.type==='password')||item.secret_endpoint)&&<small className="secret-notice"><Icon name="info"/> {t('secretNotice')}</small>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={busy||!family}>{busy?t('pleaseWait'):t('connect')}</button></form></section></div>
}
