import {useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';
import {useFamilyPermissions} from './family-permissions';
import './integration-hub.css';

const unwrap=x=>x?.results||x||[];
const groups={waste:'waste',warning:'warnings',weather:'weather',ics:'calendars',messenger:'messengers',home:'smartHome',transit:'transit',school:'school'};
const kindIcons={waste:'waste',warning:'warning',weather:'weather',ics:'calendar',messenger:'inbox',home:'smartHome',transit:'transit',school:'school'};

export default function IntegrationHub({family,onBack}){
 const {t}=useTranslation();
 const {canManageSettings,role}=useFamilyPermissions(family);
 const [catalog,setCatalog]=useState([]);const [items,setItems]=useState([]);const [busy,setBusy]=useState('');const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [recentConnected,setRecentConnected]=useState(null);
 const load=async()=>{if(!family)return;const [c,i]=await Promise.all([api('/integration-hub/catalog/'),api('/integrations/')]);setCatalog(c);setItems(unwrap(i).filter(x=>x.family===family.id))};
 useEffect(()=>{load().catch(e=>toast(e.message||t('connectionFailed'),{type:'error'}));const q=new URLSearchParams(location.search);if(q.get('integration_connected')&&canManageSettings){const name=q.get('integration_connected');toast(`${name} verbunden.`,{type:'success'});setRecentConnected({name,kind:'ics'})}if(q.get('integration_error')&&canManageSettings)toast(q.get('integration_error'),{type:'error'});if(q.has('integration_connected')||q.has('integration_error'))history.replaceState({},'',location.pathname)},[family?.id,canManageSettings]);
 const connectedAdapters=useMemo(()=>new Set(items.map(x=>x.config?.adapter).filter(Boolean)),[items]);
 const visibleCatalog=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();const rows=needle?catalog.filter(x=>`${x.name} ${x.description||''} ${x.kind||''}`.toLocaleLowerCase().includes(needle)):catalog;return [...rows].sort((a,b)=>Number(connectedAdapters.has(a.defaults?.adapter))-Number(connectedAdapters.has(b.defaults?.adapter)))},[catalog,query,connectedAdapters]);
 async function sync(x){if(!canManageSettings)return;setBusy(x.id);try{const r=await api(`/integration-hub/${x.id}/sync/`,{method:'POST',body:'{}'});toast(`${x.name}: ${r.synced} ${t('syncedItems')}`,{type:'success'})}catch(e){toast(e.message||t('connectionFailed'),{type:'error'})}finally{await load();setBusy('')}}
 async function syncAll(){if(!canManageSettings)return;setBusy('all');try{const r=await api('/integration-hub/sync-all/',{method:'POST',body:'{}'});const message=`${r.synced} ${t('syncedItems')}${r.errors?.length?` · ${r.errors.length} ${t('errors')}`:''}`;toast(message,{type:r.errors?.length?'warning':'success'})}catch(e){toast(e.message||t('connectionFailed'),{type:'error'})}finally{await load();setBusy('')}}
 async function remove(x){if(!canManageSettings)return;const ok=await confirmAction({title:`${t('disconnect')}?`,message:`${x.name} wird von fam-uh-le getrennt. Bereits synchronisierte Familieninhalte bleiben erhalten, sofern der jeweilige Bereich sie gespeichert hat.`,confirmLabel:t('disconnect'),danger:true});if(!ok)return;setBusy(x.id);try{await api(`/integrations/${x.id}/`,{method:'DELETE'});await load();toast(`${x.name} getrennt.`,{type:'success'})}catch(e){toast(e.message||t('connectionFailed'),{type:'error'})}finally{setBusy('')}}
 async function startOAuth(item){if(!canManageSettings)return;setBusy(item.id);try{const r=await api('/integration-oauth/start/',{method:'POST',body:JSON.stringify({family:family.id,provider:item.oauth_provider})});location.assign(r.authorization_url)}catch(e){toast(e.message||t('connectionFailed'),{type:'error'});setBusy('')}}
 function connected(item){return connectedAdapters.has(item.defaults?.adapter)}
 return <><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{t('settings')}</small><h1>{t('integrations')}</h1></div></div><p className="page-intro">Verbinde externe Quellen in geführten Schritten. Du siehst jederzeit, welche Verbindung gesund ist und was bei einem Fehler zu tun ist.</p>
 {!canManageSettings&&role&&<div className="integration-notice" role="status"><Icon name="info"/> Du kannst Integrationen ansehen. Verwalten, verbinden und trennen können nur Owner und Erwachsene.</div>}
 {canManageSettings&&recentConnected&&<ConnectionSuccess item={recentConnected} onClose={()=>setRecentConnected(null)}/>} 
 <section className="integration-overview"><div className="integration-section-head"><div><small>{items.length} {t('connected')}</small><h2>{t('activeIntegrations')}</h2></div>{canManageSettings&&items.length>0&&<button className="secondary compact sync-all-secondary" onClick={syncAll} disabled={busy==='all'}><Icon name="refresh"/>{busy==='all'?t('syncing'):t('syncAll')}</button>}</div><div className="integration-health-grid">{items.length?items.map(x=><IntegrationStatusCard key={x.id} item={x} t={t} busy={busy===x.id} canManage={canManageSettings} onSync={()=>sync(x)} onRemove={()=>remove(x)}/>):<div className="integration-empty"><span className="round-icon"><Icon name="integrations"/></span><div><strong>{t('noIntegrations')}</strong><p>{canManageSettings?'Starte unten mit der Quelle, die euren Alltag am meisten vereinfacht.':'Für diese Familie sind noch keine Integrationen eingerichtet.'}</p></div></div>}</div></section>
 <section className="integration-catalog"><div className="integration-section-head catalog-heading"><div><small>{catalog.length} {t('available')}</small><h2>{t('addIntegration')}</h2></div><label className="integration-search"><Icon name="search"/><span className="sr-only">Integration suchen</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Quelle suchen …"/></label></div>{visibleCatalog.length?Object.entries(groupCatalog(visibleCatalog)).map(([kind,rows])=><div key={kind} className="integration-group"><h3><Icon name={kindIcons[kind]||'integrations'}/> {t(groups[kind]||kind)}</h3><div className="catalog-grid">{rows.map(x=>{const isConnected=connected(x);return <section className={`card catalog-card ${isConnected?'catalog-connected':''}`} key={x.id}><div className="catalog-top"><div className="round-icon"><Icon name={kindIcons[x.kind]||'integrations'}/></div><div className="grow"><div className="catalog-name"><strong>{x.name}</strong>{isConnected&&<span className="sync-badge success"><Icon name="check" size={11}/>{t('connected')}</span>}</div><p>{x.description}</p></div></div>{x.oauth_provider&&x.oauth_ready===false?<div className="oauth-setup-needed"><Icon name="settings"/><div><strong>Server-Setup erforderlich</strong><span>{t('oauthSetupFirst')}</span><small>Führe das fam-uh-le Setup erneut aus und aktiviere dort {x.name}.</small></div></div>:<div className="catalog-actions">{x.help_url&&<a className="text-link" href={x.help_url} target="_blank" rel="noreferrer"><Icon name="link"/>{t('openProvider')}</a>}{canManageSettings?<button className={isConnected?'secondary compact':'primary compact'} onClick={()=>x.oauth_provider?startOAuth(x):setSelected(x)} disabled={busy===x.id}><Icon name={x.oauth_provider?'link':'settings'}/>{isConnected?'Weitere Verbindung':x.oauth_provider?t('connect'):t('configure')}</button>:<small>Nur ansehen</small>}</div>}</section>})}</div></div>):<div className="smart-empty"><Icon name="search" size={28}/><strong>Keine Quelle gefunden</strong><span>Versuche einen anderen Suchbegriff.</span></div>}</section>
 {canManageSettings&&selected&&<ConnectSheet item={selected} family={family} t={t} onClose={()=>setSelected(null)} onConnected={async result=>{setSelected(null);setRecentConnected({name:selected.name,kind:selected.kind,id:result?.id});toast(t('connectionSuccess'),{type:'success'});await load()}}/>}</>
}

function IntegrationStatusCard({item,t,busy,canManage,onSync,onRemove}){const status=item.last_sync_status||'never';const successAt=item.last_success_at||item.last_synced_at;const healthy=status==='success';const errored=status==='error';return <article className={`integration-health-card status-${status}`}><div className="integration-health-top"><span className="integration-health-icon"><Icon name={kindIcons[item.kind]||'integrations'}/></span><div className="grow"><div className="integration-name-line"><strong>{item.name}</strong><SyncBadge status={status} t={t}/></div><span className="integration-health-summary">{errored?'Verbindung braucht Aufmerksamkeit':healthy&&successAt?`Zuletzt ${relativeTime(successAt)} erfolgreich`:status==='running'?'Synchronisierung läuft …':item.enabled?'Verbunden · erste Aktualisierung steht aus':t('disabled')}</span></div></div>{errored&&<div className="integration-recovery" role="alert"><Icon name="warning"/><div className="grow"><strong>Synchronisierung fehlgeschlagen</strong><span>{friendlySyncError(item.last_sync_error)}</span>{item.next_sync_at&&<small>Nächster automatischer Versuch {relativeTime(item.next_sync_at)}.</small>}</div>{canManage&&<button className="secondary compact" onClick={onSync} disabled={busy}><Icon name="refresh"/> Erneut versuchen</button>}</div>}<div className="integration-health-actions">{canManage&&!errored&&<button className="secondary compact" onClick={onSync} disabled={busy}><Icon name="refresh"/>{busy?t('syncing'):t('sync')}</button>}<NextStep kind={item.kind}/><details className="integration-details"><summary><Icon name="info"/> Details</summary><div><span>{t(groups[item.kind]||item.kind)} · {item.enabled?t('enabled'):t('disabled')}</span><span>{t('lastSync')}: {successAt?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(successAt)):t('never')}</span>{item.last_sync_error&&<span className="danger-text">{item.last_sync_error}</span>}{canManage&&<button className="text-button danger-text" onClick={onRemove} disabled={busy}><Icon name="delete"/>{t('disconnect')}</button>}</div></details></div></article>}
function NextStep({kind}){if(['ics','school','waste','warning','weather','transit'].includes(kind))return <a className="integration-next-link" href="/?page=calendar"><Icon name="calendar"/> Kalender ansehen</a>;return <a className="integration-next-link" href="/?page=automations"><Icon name="automation"/> Regel ansehen</a>}
function ConnectionSuccess({item,onClose}){return <section className="connection-success"><span className="connection-success-icon"><Icon name="check"/></span><div className="grow"><small>VERBUNDEN</small><strong>{item.name} ist bereit</strong><p>Wähle direkt den nächsten sinnvollen Schritt oder richte später weiter ein.</p><div className="connection-next-actions"><a href="/?page=calendar"><Icon name="calendar"/> Kalender ansehen</a><a href="/?page=automations"><Icon name="automation"/> Regel erstellen</a></div></div><button className="icon-button quiet" onClick={onClose} aria-label="Hinweis schließen"><Icon name="close"/></button></section>}
function SyncBadge({status='never',t}){const key=status==='success'?'syncHealthy':status==='error'?'syncError':status==='running'?'syncRunning':'never';return <span className={`sync-badge ${status}`}><Icon name={status==='success'?'check':status==='error'?'warning':'refresh'} size={11}/>{t(key)}</span>}
function groupCatalog(items){return items.reduce((acc,x)=>{(acc[x.kind]??=[]).push(x);return acc},{})}
function relativeTime(value){if(!value)return'';const delta=new Date(value).getTime()-Date.now();const abs=Math.abs(delta);const formatter=new Intl.RelativeTimeFormat(undefined,{numeric:'auto'});if(abs<60000)return formatter.format(Math.round(delta/1000),'second');if(abs<3600000)return formatter.format(Math.round(delta/60000),'minute');if(abs<86400000)return formatter.format(Math.round(delta/3600000),'hour');return formatter.format(Math.round(delta/86400000),'day')}
function friendlySyncError(message){if(!message)return'Bitte prüfe die Verbindung und versuche es erneut.';const text=String(message);if(/401|403|auth|token|credential|permission/i.test(text))return'Zugang oder Berechtigung wurde abgelehnt. Prüfe die hinterlegten Zugangsdaten.';if(/timeout|timed out|network|connection|unreachable/i.test(text))return'Die Quelle war nicht erreichbar. Prüfe Netzwerk bzw. Anbieter und versuche es erneut.';if(/404|not found/i.test(text))return'Die angegebene Quelle wurde nicht gefunden. Prüfe URL oder Kalender-Link.';return text}

function ConnectSheet({item,family,t,onClose,onConnected}){
 const initial={};for(const f of item.fields||[])initial[f.key]=f.default??'';
 const [values,setValues]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await api('/integration-hub/connect/',{method:'POST',body:JSON.stringify({family:family.id,catalog_id:item.id,values})});await onConnected(result)}catch(e){const message=e.message||t('connectionFailed');setError(message);toast(message,{type:'error'});setBusy(false)}}
 const waste=item.id?.startsWith('waste_');
 return <div className="sheet-backdrop"><section className="quick-sheet integration-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('configure')}</small><h2>{item.name}</h2></div><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('back')}><Icon name="close"/></button></div><div className="integration-setup-steps"><span className="done"><b>1</b> Quelle</span><span className="active"><b>2</b> Zugang</span><span><b>3</b> Verbinden</span></div><p className="page-intro">{item.description}</p><SetupGuide item={item} waste={waste} t={t}/><form className="quick-form" onSubmit={submit}>{(item.fields||[]).map(f=><label key={f.key}>{f.label}{f.required?null:<span className="optional-field">optional</span>}<input type={f.type||'text'} value={values[f.key]??''} onChange={e=>setValues(v=>({...v,[f.key]:f.type==='number'?Number(e.target.value):e.target.value}))} required={!!f.required} placeholder={f.default??''}/>{fieldHint(f.key,item)}</label>)}{((item.fields||[]).some(f=>f.type==='password')||item.secret_endpoint)&&<small className="secret-notice"><Icon name="info"/> {t('secretNotice')}</small>}{error&&<div className="integration-form-error" role="alert"><Icon name="warning"/><div><strong>{t('connectionFailed')}</strong><span>{friendlySyncError(error)}</span></div></div>}<button className="primary" type="submit" disabled={busy||!family}><Icon name="link"/>{busy?t('pleaseWait'):t('connect')}</button></form></section></div>
}
function SetupGuide({item,waste,t}){return <div className="setup-guide">{item.help_url&&<a className="setup-guide-step" href={item.help_url} target="_blank" rel="noreferrer"><b>1</b><span><strong>{waste?'Adresse beim Anbieter auswählen':'Anbieter öffnen'}</strong><small>{waste?t('addressCalendarHint'):'Öffne die offizielle Seite und hole die benötigten Zugangsdaten bzw. den Kalender-Link.'}</small></span><Icon name="link"/></a>}<div className="setup-guide-step current"><b>{item.help_url?2:1}</b><span><strong>Daten hier eintragen</strong><small>fam-uh-le speichert Geheimwerte geschützt und zeigt sie später nicht wieder vollständig an.</small></span></div><div className="setup-guide-step"><b>{item.help_url?3:2}</b><span><strong>Verbinden</strong><small>Nach dem Speichern siehst du den Zustand direkt im Integrations-Hub.</small></span></div></div>}
function fieldHint(key,item){const k=String(key).toLowerCase();if(k.includes('url')||k.includes('endpoint')||k.includes('ics'))return <small className="field-setup-hint">Füge die vollständige URL ein, inklusive https://.</small>;if(k.includes('token')||k.includes('key')||k.includes('secret')||k.includes('password'))return <small className="field-setup-hint">Wird nach dem Speichern aus Sicherheitsgründen maskiert.</small>;if(item.kind==='home'&&k.includes('host'))return <small className="field-setup-hint">Adresse deiner Home-Assistant-Instanz, erreichbar vom fam-uh-le Server.</small>;return null}