import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { api, isAuthenticated, login, markAuthenticated } from './api';
import { Icon } from './icons';

export default function InviteFlow({token}){
 const {t,i18n}=useTranslation();
 const [info,setInfo]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [mode,setMode]=useState(isAuthenticated()?'accept':'register');
 const [form,setForm]=useState({username:'',password:'',email:'',display_name:''});
 useEffect(()=>{api(`/invite/${token}/`).then(x=>{setInfo(x);setForm(f=>({...f,email:x.email_hint||'',display_name:x.display_name||''}))}).catch(e=>setError(e.message))},[token]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function register(e){e.preventDefault();setBusy(true);setError('');try{await api(`/invite/${token}/register/`,{method:'POST',body:JSON.stringify(form)});markAuthenticated(true);window.location.replace('/')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function signIn(e){e.preventDefault();setBusy(true);setError('');try{await login(form.username,form.password);await api(`/invite/${token}/accept/`,{method:'POST',body:JSON.stringify({display_name:form.display_name})});window.location.replace('/')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function accept(){setBusy(true);setError('');try{await api(`/invite/${token}/accept/`,{method:'POST',body:JSON.stringify({display_name:form.display_name})});window.location.replace('/')}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!info&&!error)return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="FamilyOS"/><section className="card login-card"><p>{t('pleaseWait')}</p></section></main>;
 if(!info)return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="FamilyOS"/><section className="card login-card"><h1>{t('inviteInvalid')}</h1><p className="error">{error}</p><a className="primary" href="/">{t('toLogin')}</a></section></main>;
 return <main className="login-shell"><img className="brand-wide" src="/brand/logo-primary.svg" alt="FamilyOS"/><section className="card login-card invite-card"><div className="invite-mark"><Icon name="check" size={30}/></div><small>{t('familyInvite')}</small><h1>{info.family_name}</h1><p>{t('inviteRole')}: <strong>{t(info.role)||info.role}</strong></p>{!info.active&&<p className="error">{t('inviteExpired')}</p>}
 {info.active&&isAuthenticated()?<><label>{t('displayName')}<input value={form.display_name} onChange={e=>set('display_name',e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy} onClick={accept}><Icon name="members"/>{busy?t('pleaseWait'):t('joinFamily')}</button></>:info.active&&<><div className="invite-tabs"><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>{t('createAccount')}</button><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>{t('existingAccount')}</button></div>{mode==='register'?<form onSubmit={register}><label>{t('displayName')}<input value={form.display_name} onChange={e=>set('display_name',e.target.value)} autoFocus/></label><label>{t('username')}<input value={form.username} onChange={e=>set('username',e.target.value)} required minLength="3" autoComplete="username"/></label><label>{t('email')}<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} required={!!info.email_hint} disabled={!!info.email_hint}/></label><label>{t('password')}<input type="password" value={form.password} onChange={e=>set('password',e.target.value)} required minLength="10" autoComplete="new-password"/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}><Icon name="members"/>{busy?t('pleaseWait'):t('createAndJoin')}</button></form>:<form onSubmit={signIn}><label>{t('username')}<input value={form.username} onChange={e=>set('username',e.target.value)} required autoFocus autoComplete="username"/></label><label>{t('password')}<input type="password" value={form.password} onChange={e=>set('password',e.target.value)} required autoComplete="current-password"/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}><Icon name="login"/>{busy?t('pleaseWait'):t('loginAndJoin')}</button></form>}</>}
 <button className="text-button" onClick={()=>{const l=i18n.language?.startsWith('de')?'en':'de';i18n.changeLanguage(l);localStorage.setItem('famuhle-language',l)}}><Icon name="language"/> Deutsch / English</button></section></main>
}
