import {useState} from 'react';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';

export default function ListEditor({type,list,onClose,onSaved}){
 const [form,setForm]=useState({...list});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const path=type==='task'?'task-lists':'shopping-lists';
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/${path}/${list.id}/`,{method:'PATCH',body:JSON.stringify({name:form.name,store:type==='shopping'?form.store||'':undefined,archived:!!form.archived,icon:form.icon|| (type==='task'?'list-check':'cart-shopping')})});await onSaved();toast('Liste gespeichert.',{type:'success'})}catch(err){setError(err.message);toast(err.message||'Liste konnte nicht gespeichert werden.',{type:'error'})}finally{setBusy(false)}}
 async function archive(){setBusy(true);setError('');try{await api(`/${path}/${list.id}/`,{method:'PATCH',body:JSON.stringify({archived:true})});await onSaved();toast(`„${list.name}“ archiviert.`,{type:'success',actionLabel:'Rückgängig',duration:8000,onAction:async()=>{try{await api(`/${path}/${list.id}/`,{method:'PATCH',body:JSON.stringify({archived:false})});await onSaved();toast('Archivierung rückgängig gemacht.',{type:'success'})}catch(err){toast(err.message||'Liste konnte nicht wiederhergestellt werden.',{type:'error'})}}})}catch(err){setError(err.message);toast(err.message||'Liste konnte nicht archiviert werden.',{type:'error'})}finally{setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{type==='task'?'Aufgabenliste':'Einkaufsliste'}</small><h2>Liste bearbeiten</h2></div><button className="sheet-close" onClick={onClose} disabled={busy} aria-label="Schließen"><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>Name<input value={form.name||''} onChange={e=>set('name',e.target.value)} required autoFocus/></label>{type==='shopping'&&<label>Laden / Geschäft<input value={form.store||''} onChange={e=>set('store',e.target.value)} placeholder="z. B. REWE, dm, Baumarkt"/></label>}<label>Symbol<select value={form.icon||''} onChange={e=>set('icon',e.target.value)}><option value={type==='task'?'list-check':'cart-shopping'}>Standard</option><option value="house">Zuhause</option><option value="store">Geschäft</option><option value="star">Favoriten</option></select></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}><Icon name="check"/> {busy?'Speichere …':'Speichern'}</button><button type="button" className="ghost-danger destructive-wide" onClick={archive} disabled={busy}><Icon name="archive"/> Liste archivieren</button></form></section></div>
}
