import i18n from './ux-i18n';

const de={loyaltyUi:{
 title:'Bonuskarten',intro:'Kunden- und Bonuskarten sicher mit ausgewählten Familienmitgliedern teilen und auch offline an der Kasse öffnen.',add:'Karte hinzufügen',search:'Karten durchsuchen',empty:'Noch keine Bonuskarte sichtbar.',emptyHint:'Lege eine Karte manuell an oder scanne den Barcode mit der Kamera.',offline:'Offline-Modus',offlineHint:'Es werden die zuletzt erfolgreich synchronisierten, für dich freigegebenen Karten angezeigt.',sync:'Karten synchronisieren',scan:'Barcode scannen',manual:'Manuell eingeben',scannerTitle:'Barcode mit Kamera scannen',scannerHint:'Halte den Code vollständig in den Kamerabereich. Der Wert wird nur auf diesem Gerät erkannt und nicht an Dritte übertragen.',cameraDenied:'Die Kamera konnte nicht geöffnet werden. Du kannst den Code stattdessen manuell eingeben.',manualFallback:'Manuell fortfahren',detected:'Code erkannt',name:'Kartenname',holder:'Inhaber',holderMember:'Familienmitglied als Inhaber',customerNumber:'Kundennummer',barcodeValue:'Barcode-/Kartenwert',barcodeFormat:'Code-Typ',color:'Kartenfarbe',logo:'Logo/Icon',note:'Notiz',favorite:'Als Favorit anzeigen',sharing:'Freigabe',sharingHint:'Nur ausgewählte Personen erhalten Barcode und Kundennummer über die API und Offline-Synchronisierung.',shareAll:'Mit allen Familienmitgliedern teilen',onlyMe:'Nur für mich / Familien-Owner',save:'Karte speichern',saved:'Bonuskarte gespeichert.',archived:'Bonuskarte archiviert.',deleteQuestion:'Bonuskarte archivieren?',deleteMessage:'Die Karte verschwindet für alle freigegebenen Personen nach dem nächsten Sync.',cashier:'Kassenansicht',fullscreen:'Code groß anzeigen',closeFullscreen:'Kassenansicht schließen',edit:'Karte bearbeiten',formatUnsupported:'Dieser Code konnte nicht dargestellt werden. Prüfe Wert und Symbologie.',offlineEdit:'Zum Ändern oder Teilen der Karte ist eine Online-Verbindung erforderlich.',privacy:'Barcode und Kundennummer bleiben auf deinem Server bzw. verschlüsselt im Browser-Speicher dieser PWA. Es wird kein externer Rendering-Dienst verwendet.',formats:{code128:'Code 128',ean13:'EAN-13',ean8:'EAN-8',upca:'UPC-A',upce:'UPC-E',code39:'Code 39',itf:'ITF',qrcode:'QR Code',datamatrix:'Data Matrix',pdf417:'PDF417',aztec:'Aztec'}
}};
const en={loyaltyUi:{
 title:'Loyalty cards',intro:'Share customer and loyalty cards securely with selected family members and open them at checkout even offline.',add:'Add card',search:'Search cards',empty:'No loyalty card is visible yet.',emptyHint:'Create one manually or scan its barcode with the camera.',offline:'Offline mode',offlineHint:'Showing the last successfully synced cards that are shared with you.',sync:'Sync cards',scan:'Scan barcode',manual:'Enter manually',scannerTitle:'Scan barcode with camera',scannerHint:'Keep the full code inside the camera view. Recognition happens only on this device and is not sent to third parties.',cameraDenied:'The camera could not be opened. You can enter the code manually instead.',manualFallback:'Continue manually',detected:'Code detected',name:'Card name',holder:'Holder',holderMember:'Family member as holder',customerNumber:'Customer number',barcodeValue:'Barcode/card value',barcodeFormat:'Code type',color:'Card color',logo:'Logo/icon',note:'Note',favorite:'Show as favorite',sharing:'Sharing',sharingHint:'Only selected people receive barcode and customer number through the API and offline sync.',shareAll:'Share with all family members',onlyMe:'Only me / family owners',save:'Save card',saved:'Loyalty card saved.',archived:'Loyalty card archived.',deleteQuestion:'Archive loyalty card?',deleteMessage:'The card disappears for all shared members after their next sync.',cashier:'Checkout view',fullscreen:'Show code large',closeFullscreen:'Close checkout view',edit:'Edit card',formatUnsupported:'This code could not be rendered. Check value and symbology.',offlineEdit:'An online connection is required to edit or share the card.',privacy:'Barcode and customer number stay on your server or in this PWA’s browser storage. No external rendering service is used.',formats:{code128:'Code 128',ean13:'EAN-13',ean8:'EAN-8',upca:'UPC-A',upce:'UPC-E',code39:'Code 39',itf:'ITF',qrcode:'QR Code',datamatrix:'Data Matrix',pdf417:'PDF417',aztec:'Aztec'}
}};
i18n.addResourceBundle('de','translation',de,true,true);
i18n.addResourceBundle('en','translation',en,true,true);
export default i18n;
