import {useEffect,useMemo,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import bwipjs from 'bwip-js';
import './loyalty-i18n';
import './loyalty-cards.css';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';
import {loadOfflineCards,replaceOfflineCards} from './loyalty-offline';
import LoyaltyCardEditor from './LoyaltyCardEditor';

const unwrap=value=>value?.results||value||[];
const bcid={code128:'code128',ean13:'ean13',ean8:'ean8',upca:'upca',upce:'upce',code39:'code39',itf:'interleaved2of5',qrcode:'qrcode',datamatrix:'datamatrix',pdf417:'pdf417',aztec:'azteccode'};

function BarcodeView({value,format,t,className=''}){const ref=useRef(null);const [error,setError]=useState('');useEffect(()=>{setError('');if(!value||!format||!ref.current)return;try{bwipjs.toCanvas(ref.current,{bcid:bcid[format]||'code128',text:String(value),scale:3,height:format==='qrcode'||format==='datamatrix'||format==='aztec'?34:18,includetext:!['qrcode','datamatrix','pdf417','aztec'].includes(format),textxalign:'center',paddingwidth:10,paddingheight:10,backgroundcolor:'FFFFFF'})}catch{setError(t('loyaltyUi.formatUnsupported'))}},[value,format,t]);return <div className={`barcode-stage ${className}`}>{error?<div className="barcode-fallback">{error}<br/>{value}</div>:<canvas ref={ref} aria-label={`${t('loyaltyUi.barcodeFormat')}: ${t(`loyaltyUi.formats.${format}`)}`}/>}</div>}

function CardDetail({card,onClose,onEdit,onArchive,t,offline}){const [fullscreen,setFullscreen]=useState(false);return <div className="sheet-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="quick-sheet loyalty-detail" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('loyaltyUi.cashier')}</small><h2>{card.name}</h2></div><button className="sheet-close" onClick={onClose} aria-label={t('back')}><Icon name="close"/></button></div><div className="loyalty-hero" style={{'--card-accent':card.color||'#6750A4'}}><div className="loyalty-hero-head"><div className="wallet-logo">{card.logo||card.name.slice(0,2).toUpperCase()}</div><div><h2>{card.name}</h2><small>{card.holder_display||card.holder_name||''}</small></div></div><BarcodeView value={card.barcode_value} format={card.barcode_format} t={t}/><div className="loyalty-readable">{card.customer_number||card.barcode_value}</div></div><div className="loyalty-detail-grid">{(card.holder_display||card.holder_name)&&<div className="loyalty-detail-cell"><small>{t('loyaltyUi.holder')}</small><strong>{card.holder_display||card.holder_name}</strong></div>}{card.customer_number&&<div className="loyalty-detail-cell"><small>{t('loyaltyUi.customerNumber')}</small><strong>{card.customer_number}</strong></div>}<div className="loyalty-detail-cell"><small>{t('loyaltyUi.barcodeFormat')}</small><strong>{t(`loyaltyUi.formats.${card.barcode_format}`)}</strong></div></div>{card.note&&<p className="loyalty-note">{card.note}</p>}<button className="primary" onClick={()=>setFullscreen(true)}><Icon name="store"/>{t('loyaltyUi.fullscreen')}</button>{card.can_edit&&!offline&&<button className="secondary" onClick={()=>onEdit(card)}><Icon name="edit"/>{t('loyaltyUi.edit')}</button>}{card.can_edit&&!offline&&<button className="ghost-danger" onClick={()=>onArchive(card)}><Icon name="archive"/>{t('delete')}</button>}{offline&&<div className="loyalty-status"><Icon name="offline"/><span>{t('loyaltyUi.offlineEdit')}</span></div>}{fullscreen&&<div className="cashier-overlay" role="dialog" aria-modal="true"><div className="cashier-head"><div className="grow"><small>{t('loyaltyUi.cashier')}</small><h2>{card.name}</h2></div><button className="sheet-close" onClick={()=>setFullscreen(false)} aria-label={t('loyaltyUi.closeFullscreen')}><Icon name="close"/></button></div><BarcodeView value={card.barcode_value} format={card.barcode_format} t={t}/><div className="loyalty-readable">{card.customer_number||card.barcode_value}</div><button className="primary" onClick={()=>setFullscreen(false)}>{t('loyaltyUi.closeFullscreen')}</button></div>}</section></div>}

export default function LoyaltyCards({family,onBack}){
 const {t}=useTranslation();const [cards,setCards]=useState([]);const [loaded,setLoaded]=useState(false);const [offline,setOffline]=useState(!navigator.onLine);const [query,setQuery]=useState('');const [detail,setDetail]=useState(null);const [edit,setEdit]=useState(null);
 async function load(){if(!family?.id)return;try{if(!navigator.onLine)throw new Error('offline');const rows=unwrap(await api(`/loyalty-cards/sync/?family=${encodeURIComponent(family.id)}`));setCards(rows);await replaceOfflineCards(family.id,rows);setOffline(false);const requested=new URLSearchParams(location.search).get('card');if(requested){const found=rows.find(card=>String(card.id)===String(requested));if(found)setDetail(found)}}catch{const rows=await loadOfflineCards(family.id);setCards(rows);setOffline(true)}finally{setLoaded(true)}}
 useEffect(()=>{setLoaded(false);load();const online=()=>load();const offlineEvent=()=>setOffline(true);window.addEventListener('online',online);window.addEventListener('offline',offlineEvent);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offlineEvent)}},[family?.id]);
 const visible=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return cards.filter(card=>!needle||[card.name,card.holder_display,card.holder_name,card.note].some(value=>String(value||'').toLocaleLowerCase().includes(needle)))},[cards,query]);
 async function archive(card){const ok=await confirmAction({title:t('loyaltyUi.deleteQuestion'),message:t('loyaltyUi.deleteMessage'),confirmLabel:t('delete'),danger:true});if(!ok)return;try{await api(`/loyalty-cards/${card.id}/`,{method:'DELETE'});setDetail(null);await load();toast(t('loyaltyUi.archived'),{type:'success'})}catch(error){toast(error.message||t('saveFailed'),{type:'error'})}}
 return <div className="smart-page loyalty-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><h1 className="grow">{t('loyaltyUi.title')}</h1></div><p className="page-intro">{t('loyaltyUi.intro')}</p>{offline&&<div className="loyalty-status"><Icon name="offline"/><div><strong>{t('loyaltyUi.offline')}</strong><span>{t('loyaltyUi.offlineHint')}</span></div></div>}<div className="loyalty-toolbar"><div className="smart-input"><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('loyaltyUi.search')}/></div><button className="secondary compact" onClick={load} disabled={!navigator.onLine}><Icon name="refresh"/>{t('loyaltyUi.sync')}</button></div>{!loaded?<div className="smart-empty"><Icon name="refresh" size={34}/></div>:visible.length?<div className="wallet-list">{visible.map(card=><article className="wallet-card" style={{'--card-accent':card.color||'#6750A4'}} key={card.id}><div className="wallet-accent"/><button className="wallet-card-button" onClick={()=>setDetail(card)}><div className="wallet-name"><span className="wallet-logo">{card.logo||card.name.slice(0,2).toUpperCase()}</span><strong>{card.name}</strong>{card.favorite&&<span className="favorite-mark"><Icon name="favorite"/></span>}</div><div className="wallet-meta">{(card.holder_display||card.holder_name)&&<span><Icon name="user"/>{card.holder_display||card.holder_name}</span>}<span><Icon name="store"/>{t(`loyaltyUi.formats.${card.barcode_format}`)}</span></div></button></article>)}</div>:<div className="smart-empty"><Icon name="store" size={34}/><strong>{t('loyaltyUi.empty')}</strong><span>{t('loyaltyUi.emptyHint')}</span></div>}<div className="loyalty-privacy"><Icon name="info"/><span>{t('loyaltyUi.privacy')}</span></div>{detail&&<CardDetail card={detail} t={t} offline={offline} onClose={()=>setDetail(null)} onEdit={card=>{setDetail(null);setEdit(card)}} onArchive={archive}/>} {edit&&<LoyaltyCardEditor family={family} card={edit} onClose={()=>setEdit(null)} onSaved={async()=>{setEdit(null);await load()}}/>}</div>
}
