import React,{useRef,useState} from 'react';
export default function NoteDrawing({value=[],onChange,readonly,t}){
 const svg=useRef(null),stroke=useRef(null);const [tool,setTool]=useState('pen'),[color,setColor]=useState('#183c32'),[width,setWidth]=useState(4),[working,setWorking]=useState(null),[undo,setUndo]=useState([]),[error,setError]=useState('');
 const point=e=>{const r=svg.current.getBoundingClientRect();return [Math.max(0,Math.min(1000,Math.round((e.clientX-r.left)/r.width*1000))),Math.max(0,Math.min(1000,Math.round((e.clientY-r.top)/r.height*1000)))];};
 const change=next=>{setUndo(old=>[...old.slice(-19),value]);onChange(next)};
 const start=e=>{if(readonly)return;e.preventDefault();svg.current.setPointerCapture(e.pointerId);const p=point(e);if(tool==='eraser'){const index=value.findLastIndex(s=>s.points.some(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<30));if(index>=0)change(value.filter((_,i)=>i!==index));return}if(value.length>=250||value.reduce((n,s)=>n+s.points.length,0)>=18000){setError(t('limit'));return}stroke.current={color,width,points:[p]};setWorking(stroke.current)};
 const move=e=>{if(!stroke.current)return;const p=point(e),s=stroke.current;if(s.points.length>=1800)return;s.points=[...s.points,p];setWorking({...s})};
 const end=()=>{if(stroke.current){change([...value,stroke.current]);stroke.current=null;setWorking(null)}};
 return <div className="note-drawing">{!readonly&&<div className="note-tools"><button aria-pressed={tool==='pen'} onClick={()=>setTool('pen')}>{t('pen')}</button><button aria-pressed={tool==='eraser'} onClick={()=>setTool('eraser')}>{t('eraser')}</button><label>{t('color')}<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>{t('width')}<input type="range" min="1" max="16" value={width} onChange={e=>setWidth(+e.target.value)}/></label><button disabled={!undo.length} onClick={()=>{onChange(undo.at(-1));setUndo(undo.slice(0,-1))}}>{t('undo')}</button><button disabled={!value.length} onClick={()=>change([])}>{t('clear')}</button></div>}{error&&<p role="alert">{error}</p>}<svg ref={svg} role="img" aria-label={t('drawing')} viewBox="0 0 1000 1000" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{touchAction:readonly?'auto':'none'}}>{[...value,...(working?[working]:[])].map((s,i)=><polyline key={i} points={s.points.map(p=>p.join(',')).join(' ')} stroke={s.color} strokeWidth={s.width} strokeLinecap="round" strokeLinejoin="round" fill="none"/>)}{value.map((s,i)=>s.points.length===1?<circle key={'dot'+i} cx={s.points[0][0]} cy={s.points[0][1]} r={s.width/2} fill={s.color}/>:null)}</svg></div>
}
