import React,{useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import MDEditor from '@uiw/react-md-editor';
import rehypeSanitize from 'rehype-sanitize';
import '@uiw/react-md-editor/markdown-editor.css';
import '@uiw/react-markdown-preview/markdown.css';
import {api} from './api';
import {Icon} from './icons';
import NoteDrawing from './NoteDrawing';
import './notes-i18n';
import './notes.css';

export default function NotesHub({family,onBack}){
 const {t}=useTranslation('notes');
 const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[note,setNote]=useState(null),[draft,setDraft]=useState(null),[tab,setTab]=useState('text'),[status,setStatus]=useState(''),[sharing,setSharing]=useState(false),[shareBusy,setShareBusy]=useState(''),[versions,setHistory]=useState(null),[loading,setLoading]=useState(true),[nextPage,setNextPage]=useState(null);
 const timer=useRef(null),serial=useRef(Promise.resolve()),latest=useRef(null),mounted=useRef(true),revision=useRef(0);
 const load=async()=>{try{const data=await api(`/notes/?family=${family.id}&search=${encodeURIComponent(search)}`);setRows(data.results||data);setNextPage(data.next||null)}catch{setStatus('error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[family?.id,search]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('note');if(id&&!note)api(`/notes/${id}/`).then(row=>open(row)).catch(()=>setStatus('error'))},[family?.id]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;clearTimeout(timer.current)}},[]);
 const open=row=>{if(draft&&(status==='saving'||status==='conflict'||status==='error'))return;setNote(row);setDraft(row);latest.current=row;setStatus('saved');setTab('text');setSharing(false);setHistory(null);const url=new URL(location.href);url.searchParams.set('note',row.id);window.history.replaceState({},'',url)};
 const save=current=>{serial.current=serial.current.then(async()=>{if(!latest.current||latest.current.id!==current.id)return;setStatus('saving');try{const saved=await api(`/notes/${current.id}/`,{method:'PATCH',body:JSON.stringify({...current,version:latest.current.version})});latest.current={...latest.current,version:saved.version};if(mounted.current){setNote(saved);setDraft(old=>old?.id===saved.id?{...old,version:saved.version}:old);setStatus(revision.current===current._revision?'saved':'saving');load()}}catch(error){if(mounted.current)setStatus(error.message==='note_conflict'?'conflict':'error')}});return serial.current};
 const change=patch=>{const next={...draft,...patch,_revision:++revision.current};setDraft(next);latest.current={...next,version:latest.current.version};setStatus('saving');clearTimeout(timer.current);timer.current=setTimeout(()=>save(next),650)};
 const create=async()=>{if(draft&&(status==='saving'||status==='error'||status==='conflict'))return;try{const row=await api('/notes/',{method:'POST',body:JSON.stringify({family:family.id,title:'',body:''})});open(row);load()}catch{setStatus('error')}};
 const applyShares=async shares=>{if(status!=='saved')return;try{const saved=await api(`/notes/${note.id}/sharing/`,{method:'POST',body:JSON.stringify({version:latest.current.version,shares})});setNote(saved);setDraft(saved);latest.current=saved;setStatus('saved');load()}catch(error){setStatus(error.message==='note_conflict'?'conflict':'error')}};
 const setPermission=async(user,permission)=>{if(shareBusy||status!=='saved')return;setShareBusy(String(user));const shares=[...(note.shares||[]).filter(s=>String(s.user)!==String(user)),...(permission?[{user,permission}]:[])];try{await applyShares(shares)}finally{setShareBusy('')}};
 const readonly=note&&!['owner','edit'].includes(note.permission);
 const close=()=>{if(status==='saving'||status==='error'||status==='conflict')return;setNote(null);setDraft(null);latest.current=null;const url=new URL(location.href);url.searchParams.delete('note');window.history.replaceState({},'',url)};
 useEffect(()=>{const guard=e=>{if(draft&&['saving','error','conflict'].includes(status)){e.preventDefault();e.returnValue=''}};const routeGuard=e=>{if(draft&&['saving','error','conflict'].includes(status)){e.preventDefault();if(e.detail?.popstate){const url=new URL(location.href);url.searchParams.set('page','notes');if(note)url.searchParams.set('note',note.id);window.history.pushState({},'',url)}}};window.addEventListener('famuhle:before-navigation',routeGuard);window.addEventListener('beforeunload',guard);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('famuhle:before-navigation',routeGuard)}},[status,draft,note]);
 const previewOptions={rehypePlugins:[[rehypeSanitize]]};
 return <section className="notes-hub"><header className="notes-header"><button className="icon-button" onClick={note?close:onBack} disabled={status==='saving'} aria-label={note?t('close'):t('close')}><Icon name="back"/></button><div className="grow"><small>{family?.name||''}</small><h1>{t('title')}</h1></div>{!note&&<button className="primary compact" onClick={create}><Icon name="plus"/>{t('new')}</button>}</header>
 {status==='error'&&<div role="alert" className="note-alert">{t('error')} <button onClick={()=>draft?save(draft):(setStatus(''),load())}>{t('retry')}</button></div>}{status==='conflict'&&<div role="alert" className="note-alert">{t('conflict')}<div><button onClick={async()=>{const row=await api(`/notes/${note.id}/`);latest.current=row;setNote(row);setDraft(row);setStatus('saved')}}>{t('reload')}</button><button onClick={async()=>{const row=await api('/notes/',{method:'POST',body:JSON.stringify({family:family.id,title:draft.title,body:draft.body,drawing:draft.drawing,pinned:draft.pinned})});latest.current=row;setNote(row);setDraft(row);setStatus('saved');load()}}>{t('copy')}</button></div></div>}
 {!note?<><div className="note-search"><Icon name="search"/><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<p className="note-loading">{t('loading')}</p>:rows.length?<div className="note-grid">{rows.map(row=><button key={row.id} className="note-card" onClick={()=>open(row)}><div className="note-card-head"><strong>{row.pinned?'📌 ':''}{row.title||t('untitled')}</strong><span className={`note-privacy ${row.permission==='owner'&&!row.shares.length?'private':'shared'}`}>{row.permission==='owner'&&!row.shares.length?t('private'):t('shared')}</span></div><p>{row.body.slice(0,140)||t('empty')}</p><small>{row.permission==='owner'?(row.shares.length?t('sharedWith',{count:row.shares.length}):t('sharePrivateHint')):t(row.permission==='edit'?'edit':'readonly')}</small></button>)}</div>:<div className="smart-empty note-empty"><Icon name="edit" size={32}/><strong>{t('empty')}</strong></div>}{nextPage&&<button className="secondary note-more" onClick={async()=>{const url=new URL(nextPage,location.origin);const data=await api(url.pathname.replace(/^\/api/, '')+url.search);setRows([...rows,...data.results]);setNextPage(data.next)}}>{t('more')}</button>}</>:<><div className="note-editor-shell"><div className="note-editor-meta"><div className="note-state" role="status"><span className={`note-save-dot ${status}`}/>{readonly?t('readonly'):t(status||'saved')}</div><span className={`note-privacy ${note.permission==='owner'&&!note.shares.length?'private':'shared'}`}>{note.permission==='owner'&&!note.shares.length?t('private'):t('shared')}</span></div><input className="note-title" aria-label={t('name')} placeholder={t('name')} maxLength={160} readOnly={readonly} value={draft.title} onChange={e=>change({title:e.target.value})}/><p className="note-editor-hint">{t('editorHint')}</p><div className="note-toolbar"><div className="note-mode-tabs" role="tablist">{['text','preview','drawing'].map(mode=><button key={mode} role="tab" aria-selected={tab===mode} className={tab===mode?'active':''} onClick={()=>setTab(mode)}>{t(mode)}</button>)}</div><div className="note-actions">{!readonly&&<button className="ghost" aria-pressed={draft.pinned} onClick={()=>change({pinned:!draft.pinned})}><Icon name="favorite"/>{t(draft.pinned?'unpin':'pin')}</button>}{note.permission==='owner'&&<><button className="ghost" aria-expanded={sharing} onClick={()=>setSharing(!sharing)}><Icon name="members"/>{t('share')}</button><button className="ghost" onClick={async()=>{const data=await api(`/notes/${note.id}/history/`);setHistory(data.results||data)}}><Icon name="history"/>{t('history')}</button><button className="ghost danger-text" onClick={async()=>{if(status==='saved'&&confirm(t('deleteConfirm'))){await api(`/notes/${note.id}/`,{method:'DELETE'});close();load()}}}><Icon name="delete"/>{t('delete')}</button></>}</div></div>
 {sharing&&<section className="note-sharing" aria-label={t('share')}><div className="note-sharing-head"><div><h2>{t('share')}</h2><p>{t('shareHint')}</p></div><span>{note.shares?.length||0}</span></div><div className="note-share-list">{(family.memberships||[]).filter(m=>String(m.user)!==String(note.author)).map(m=>{const current=note.shares.find(s=>String(s.user)===String(m.user))?.permission||'';return <div className="note-share-row" key={m.id}><span className="note-share-avatar" aria-hidden="true">{String(m.display_name||m.username||'?').slice(0,1).toUpperCase()}</span><div className="grow"><strong>{m.display_name||m.username||m.user}</strong><small>{t(current||'unshared')}</small></div><div className="note-share-options" role="group" aria-label={`${t('share')} ${m.display_name||m.user}`}>{[['',t('unshared')],['read',t('read')],['edit',t('edit')]].map(([value,label])=><button key={value||'none'} className={current===value?'active':''} aria-pressed={current===value} disabled={!!shareBusy||status!=='saved'} onClick={()=>setPermission(m.user,value)}>{label}</button>)}</div></div>})}</div></section>}
 {versions&&<details className="note-history" open><summary>{t('history')}</summary>{versions.map(row=><p key={row.id}>v{row.version} · {row.title||t('untitled')} <button disabled={status!=='saved'} onClick={()=>{change({title:row.title,body:row.body,drawing:row.drawing});setHistory(null)}}>{t('restore')}</button></p>)}</details>}
 <div className="note-editor-body">{tab==='text'&&(readonly?<div className="note-preview" data-color-mode="light"><MDEditor.Markdown source={draft.body||''} previewOptions={previewOptions}/></div>:<div className="note-md-editor" data-color-mode="light"><MDEditor value={draft.body||''} onChange={value=>change({body:value||''})} preview="edit" height={440} visibleDragbar={false} textareaProps={{'aria-label':t('text'),maxLength:50000}} previewOptions={previewOptions}/></div>)}{tab==='preview'&&<div className="note-preview" data-color-mode="light"><MDEditor.Markdown source={draft.body||''} previewOptions={previewOptions}/></div>}{tab==='drawing'&&<NoteDrawing value={draft.drawing} onChange={drawing=>change({drawing})} readonly={readonly} t={t}/>}</div></div></>}
 </section>
}
