import React,{useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';import NoteDrawing from './NoteDrawing';import NoteMarkdown from './NoteMarkdown';import './notes-i18n';import './notes.css';
export default function NotesHub({family,onBack}){
 const {t}=useTranslation('notes');const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[note,setNote]=useState(null),[draft,setDraft]=useState(null),[tab,setTab]=useState('text'),[status,setStatus]=useState(''),[sharing,setSharing]=useState(false),[versions,setHistory]=useState(null),[loading,setLoading]=useState(true),[nextPage,setNextPage]=useState(null);const text=useRef(null),timer=useRef(null),serial=useRef(Promise.resolve()),latest=useRef(null),mounted=useRef(true),revision=useRef(0);
 const load=async()=>{try{const data=await api(`/notes/?family=${family.id}&search=${encodeURIComponent(search)}`);setRows(data.results||data);setNextPage(data.next||null)}catch{setStatus('error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[family?.id,search]);useEffect(()=>{const id=new URLSearchParams(location.search).get('note');if(id&&!note)api(`/notes/${id}/`).then(row=>open(row)).catch(()=>setStatus('error'))},[family?.id]);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;clearTimeout(timer.current)}},[]);
 const open=row=>{if(draft&&(status==='saving'||status==='conflict'||status==='error'))return;setNote(row);setDraft(row);latest.current=row;setStatus('saved');setTab('text');setSharing(false);setHistory(null);const url=new URL(location.href);url.searchParams.set('note',row.id);window.history.replaceState({},'',url)};
 const save=current=>{serial.current=serial.current.then(async()=>{if(!latest.current||latest.current.id!==current.id)return;setStatus('saving');try{const saved=await api(`/notes/${current.id}/`,{method:'PATCH',body:JSON.stringify({...current,version:latest.current.version})});latest.current={...latest.current,version:saved.version};if(mounted.current){setNote(saved);setDraft(old=>old?.id===saved.id?{...old,version:saved.version}:old);setStatus(revision.current===current._revision?'saved':'saving');load()}}catch(error){if(mounted.current)setStatus(error.message==='note_conflict'?'conflict':'error')}});return serial.current};
 const change=patch=>{const next={...draft,...patch,_revision:++revision.current};setDraft(next);latest.current={...next,version:latest.current.version};setStatus('saving');clearTimeout(timer.current);timer.current=setTimeout(()=>save(next),650)};
 const create=async()=>{if(draft&&(status==='saving'||status==='error'||status==='conflict'))return;try{const row=await api('/notes/',{method:'POST',body:JSON.stringify({family:family.id,title:'',body:''})});open(row);load()}catch{setStatus('error')}};
 const format=(before,after='')=>{const input=text.current,a=input.selectionStart,b=input.selectionEnd;change({body:draft.body.slice(0,a)+before+draft.body.slice(a,b)+after+draft.body.slice(b)});requestAnimationFrame(()=>{input.focus();input.setSelectionRange(a+before.length,b+before.length)})};
 const applyShares=async shares=>{if(status!=='saved')return;try{const saved=await api(`/notes/${note.id}/sharing/`,{method:'POST',body:JSON.stringify({version:latest.current.version,shares})});setNote(saved);setDraft(saved);latest.current=saved;setStatus('saved');load()}catch(error){setStatus(error.message==='note_conflict'?'conflict':'error')}};
 const readonly=note&&!['owner','edit'].includes(note.permission);
 const close=()=>{if(status==='saving'||status==='error'||status==='conflict')return;setNote(null);setDraft(null);latest.current=null;const url=new URL(location.href);url.searchParams.delete('note');window.history.replaceState({},'',url)};
 useEffect(()=>{const guard=e=>{if(draft&&['saving','error','conflict'].includes(status)){e.preventDefault();e.returnValue=''}};const routeGuard=e=>{if(draft&&['saving','error','conflict'].includes(status)){e.preventDefault();if(e.detail?.popstate){const url=new URL(location.href);url.searchParams.set('page','notes');if(note)url.searchParams.set('note',note.id);window.history.pushState({},'',url)}}};window.addEventListener('famuhle:before-navigation',routeGuard);window.addEventListener('beforeunload',guard);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('famuhle:before-navigation',routeGuard)}},[status,draft]);
 return <section className="notes-hub"><header><button onClick={note?close:onBack} disabled={status==='saving'}>{note?t('close'):'←'}</button><h1>{t('title')}</h1>{!note&&<button onClick={create}>{t('new')}</button>}</header>{status==='error'&&<div role="alert">{t('error')} <button onClick={()=>draft?save(draft):(setStatus(''),load())}>{t('retry')}</button></div>}{status==='conflict'&&<div role="alert">{t('conflict')}<button onClick={async()=>{const row=await api(`/notes/${note.id}/`);latest.current=row;setNote(row);setDraft(row);setStatus('saved')}}>{t('reload')}</button><button onClick={async()=>{const row=await api('/notes/',{method:'POST',body:JSON.stringify({family:family.id,title:draft.title,body:draft.body,drawing:draft.drawing})});latest.current=row;setNote(row);setDraft(row);setStatus('saved');load()}}>{t('copy')}</button></div>}
 {!note?<><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/>{loading?<p>{t('loading')}</p>:rows.length?<div className="note-grid">{rows.map(row=><button key={row.id} className="note-card" onClick={()=>open(row)}><strong>{row.pinned?'📌 ':''}{row.title||t('untitled')}</strong><p>{row.body.slice(0,120)}</p><small>{row.permission==='owner'&&!row.shares.length?t('private'):t('shared')}</small></button>)}</div>:<p>{t('empty')}</p>}{nextPage&&<button onClick={async()=>{const url=new URL(nextPage,location.origin);const data=await api(url.pathname.replace(/^\/api/, '')+url.search);setRows([...rows,...data.results]);setNextPage(data.next)}}>{t('more')}</button>}</>:<><div className="note-state" role="status">{readonly?t('readonly'):t(status||'saved')} · {note.permission==='owner'&&!note.shares.length?t('private'):t('shared')}</div><input className="note-title" aria-label={t('name')} placeholder={t('name')} maxLength={160} readOnly={readonly} value={draft.title} onChange={e=>change({title:e.target.value})}/><div className="note-tools">{['text','preview','drawing'].map(mode=><button key={mode} aria-pressed={tab===mode} onClick={()=>setTab(mode)}>{t(mode)}</button>)}{!readonly&&<button aria-pressed={draft.pinned} onClick={()=>change({pinned:!draft.pinned})}>{t(draft.pinned?'unpin':'pin')}</button>}{note.permission==='owner'&&<><button onClick={()=>setSharing(!sharing)}>{t('share')}</button><button onClick={async()=>{const data=await api(`/notes/${note.id}/history/`);setHistory(data.results||data)}}>{t('history')}</button><button onClick={async()=>{if(status==='saved'&&confirm(t('deleteConfirm'))){await api(`/notes/${note.id}/`,{method:'DELETE'});close();load()}}}>{t('delete')}</button></>}</div>
 {sharing&&<fieldset><legend>{t('share')}</legend>{(family.memberships||[]).filter(m=>String(m.user)!==String(note.author)).map(m=><label key={m.id}>{m.display_name||m.username||m.user}<select aria-label={`${t('share')} ${m.display_name||m.user}`} disabled={status!=='saved'} value={note.shares.find(s=>s.user===m.user)?.permission||''} onChange={e=>applyShares([...note.shares.filter(s=>s.user!==m.user),...(e.target.value?[{user:m.user,permission:e.target.value}]:[])])}><option value="">{t('unshared')}</option><option value="read">{t('read')}</option><option value="edit">{t('edit')}</option></select></label>)}</fieldset>}
 {versions&&<details open><summary>{t('history')}</summary>{versions.map(row=><p key={row.id}>v{row.version} · {row.title||t('untitled')} <button disabled={status!=='saved'} onClick={()=>{change({title:row.title,body:row.body,drawing:row.drawing});setHistory(null)}}>{t('restore')}</button></p>)}</details>}
 {tab==='text'&&<>{!readonly&&<div className="note-tools">{[['bold','**','**'],['italic','*','*'],['heading','# '],['list','- '],['check','- [ ] ']].map(([name,b,a])=><button key={name} onClick={()=>format(b,a)}>{t(name)}</button>)}</div>}<textarea ref={text} aria-label={t('text')} value={draft.body} maxLength={50000} readOnly={readonly} placeholder={t('empty')} onKeyDown={e=>{if(!readonly&&(e.ctrlKey||e.metaKey)&&['b','i'].includes(e.key)){e.preventDefault();format(e.key==='b'?'**':'*',e.key==='b'?'**':'*')}}} onChange={e=>change({body:e.target.value})}/></>}{tab==='preview'&&<NoteMarkdown text={draft.body}/>} {tab==='drawing'&&<NoteDrawing value={draft.drawing} onChange={drawing=>change({drawing})} readonly={readonly} t={t}/>}</>}
 </section>
}
