import i18n from './ux-i18n';

const de={pushUx:{
 introTitle:'Benachrichtigungen auf diesem Gerät',introText:'fam-uh-le kann wichtige Familienereignisse direkt auf dieses Gerät senden – zum Beispiel Warnungen, Termine oder Wenn→Dann-Regeln.',benefitRules:'Nur Regeln und Ereignisse, die ihr selbst festlegt.',benefitDevice:'Die Freigabe gilt nur für dieses Gerät und diesen Browser.',benefitPrivacy:'Kein Werbetracking und keine Werbenachrichtigungen.',continue:'Freigabe vorbereiten',permissionTitle:'Browser-Freigabe öffnen',permissionText:'Als Nächstes zeigt dein Browser seinen eigenen Benachrichtigungsdialog. Wähle dort „Zulassen“, damit fam-uh-le Push auf diesem Gerät aktivieren kann.',requestPermission:'Browser-Freigabe öffnen',notNow:'Noch nicht',blockedTitle:'Benachrichtigungen sind im Browser blockiert',blockedText:'Öffne die Website-Einstellungen deines Browsers, erlaube Benachrichtigungen für fam-uh-le und lade die Seite danach neu.',blockedSteps:'Website-Einstellungen → Benachrichtigungen → Zulassen',reload:'Seite neu laden',serverMissingTitle:'Push ist serverseitig noch nicht eingerichtet',serverMissingText:'Die App ist bereit, aber im Setup fehlen noch die VAPID-Schlüssel. Danach kann jedes Gerät Push separat aktivieren.',unsupportedTitle:'Dieser Browser unterstützt Web Push nicht',unsupportedText:'Nutze einen aktuellen Browser bzw. die installierte PWA auf einem unterstützten Gerät.',activeTitle:'Auf diesem Gerät aktiv',activeText:'Dieses Gerät kann Benachrichtigungen aus euren Regeln und Ereignissen empfangen.',devicesContext_one:'In eurer Familie ist derzeit {{count}} Gerät für Push registriert.',devicesContext_other:'In eurer Familie sind derzeit {{count}} Geräte für Push registriert.',testHint:'Mit einem Test kannst du prüfen, ob Benachrichtigungen hier sichtbar ankommen.',privacyTitle:'Datenschutz',privacyText:'Gespeichert wird nur die technische Push-Subscription dieses Geräts. Sie wird nicht für Werbung oder Tracking verwendet.',rulesCta:'Push-Regel erstellen',rulesCtaHint:'Push allein sendet noch keine regelmäßigen Nachrichten. Lege fest, wann fam-uh-le euch informieren soll.',permissionDismissed:'Die Browser-Freigabe wurde nicht erteilt. Du kannst es später erneut versuchen.',enableFailed:'Push konnte auf diesem Gerät nicht aktiviert werden.',disableFailed:'Push konnte auf diesem Gerät nicht deaktiviert werden.',testFailed:'Test-Benachrichtigung konnte nicht gesendet werden.'
}};
const en={pushUx:{
 introTitle:'Notifications on this device',introText:'fam-uh-le can send important family events directly to this device – for example warnings, events, or If→Then rules.',benefitRules:'Only rules and events your family chooses.',benefitDevice:'Permission applies only to this device and browser.',benefitPrivacy:'No ad tracking and no advertising notifications.',continue:'Prepare permission',permissionTitle:'Open browser permission',permissionText:'Next, your browser will show its own notification prompt. Choose “Allow” there so fam-uh-le can enable push on this device.',requestPermission:'Open browser permission',notNow:'Not now',blockedTitle:'Notifications are blocked in the browser',blockedText:'Open your browser’s site settings, allow notifications for fam-uh-le, then reload this page.',blockedSteps:'Site settings → Notifications → Allow',reload:'Reload page',serverMissingTitle:'Push is not configured on the server yet',serverMissingText:'The app is ready, but VAPID keys are still missing from setup. Afterwards, each device can enable push separately.',unsupportedTitle:'This browser does not support Web Push',unsupportedText:'Use a current supported browser or the installed PWA on a supported device.',activeTitle:'Active on this device',activeText:'This device can receive notifications from your family rules and events.',devicesContext_one:'Your family currently has {{count}} device registered for push.',devicesContext_other:'Your family currently has {{count}} devices registered for push.',testHint:'Send a test to confirm notifications appear on this device.',privacyTitle:'Privacy',privacyText:'Only this device’s technical push subscription is stored. It is not used for advertising or tracking.',rulesCta:'Create a push rule',rulesCtaHint:'Push by itself does not send recurring messages. Choose when fam-uh-le should notify your family.',permissionDismissed:'Browser permission was not granted. You can try again later.',enableFailed:'Could not enable push on this device.',disableFailed:'Could not disable push on this device.',testFailed:'Could not send the test notification.'
}};

i18n.addResourceBundle('de','translation',de,true,true);
i18n.addResourceBundle('en','translation',en,true,true);
export default i18n;
