import {useEffect,useMemo,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';
import {flushShoppingMutations,listShoppingMutations,loadShoppingSnapshot,optimisticId,queueShoppingMutation,saveShoppingSnapshot} from './offline-shopping';
import './shopping-offline-i18n';

const unwrap=x=>x?.results||x||[];

function findItem(lists,id){for(const list of lists){const item=(list.items||[]).find(row=>String(row.id)===String(id));if(item)return {list,item}}return null}
function updateItem(lists,id,patch){return lists.map(list=>({...list,items:(list.items||[]).map(item=>String(item.id)===String(id)?{...item,...patch,_pending:true}:item)}))}
function replaceItem(lists,tempId,serverItem){return lists.map(list=>({...list,items:(list.items||[]).map(item=>String(item.id)===String(tempId)?{...item,...serverItem,_pending:true}:item)}))}

function OfflineInput({onCreate,disabled}){
 const {t}=useTranslation();const [value,setValue]=useState('');const ref=useRef(null);
 async function submit(e){e.preventDefault();const name=value.trim();if(!name||disabled)return;setValue('');await onCreate(name);requestAnimationFrame(()=>ref.current?.focus())}
 return <form className="smart-input" onSubmit={submit}><Icon name="search"/><input ref={ref} value={value} onChange={e=>setValue(e.target.value)} placeholder={t('searchOrAddItem')} autoComplete="off"/><button disabled={!value.trim()||disabled}><Icon name="plus"/> {t('addAction')}</button></form>
}

function PendingBadge({item,t}){return item._pending?<span className="sync-badge running"><Icon name="refresh" size={11}/>{t('shoppingOffline.pending')}</span>:null}

export default function OfflineShopping({family,onChanged}){
 const {t}=useTranslation();
 const [lists,setLists]=useState([]);const [active,setActive]=useState(null);const [loaded,setLoaded]=useState(false);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [storeMode,setStoreMode]=useState(false);const [editing,setEditing]=useState(null);const [pending,setPending]=useState(0);const [failed,setFailed]=useState(false);const [syncing,setSyncing]=useState(false);const syncingRef=useRef(false);
 const familyId=family?.id;

 async function persist(next){setLists(next);if(familyId)await saveShoppingSnapshot(familyId,next)}
 async function markQueue(){const rows=await listShoppingMutations(familyId);setPending(rows.length);setFailed(rows.some(row=>(row.attempts||0)>=3||row.lastError))}
 async function refreshFromServer(){const rows=unwrap(await api('/shopping-lists/')).filter(row=>row.family===familyId&&!row.archived);await persist(rows);setActive(current=>current&&rows.some(row=>row.id===current)?current:(rows[0]?.id||null));setLoaded(true);setLoadError('');return rows}
 async function load(){if(!familyId)return;setLoading(true);setLoadError('');try{if(navigator.onLine){await flush();await refreshFromServer()}else{const snapshot=await loadShoppingSnapshot(familyId);if(snapshot){setLists(snapshot.lists||[]);setActive(current=>current||(snapshot.lists?.[0]?.id||null));setLoaded(true)}else setLoadError(t('shoppingOffline.noSnapshot'))}}catch(error){if(error?.message!=='unauthorized'){const snapshot=await loadShoppingSnapshot(familyId);if(snapshot){setLists(snapshot.lists||[]);setActive(current=>current||(snapshot.lists?.[0]?.id||null));setLoaded(true);setLoadError('')}else setLoadError(error?.message||t('sessionUi.loadFailed'))}}finally{await markQueue();setLoading(false)}}
 async function flush(){if(!familyId||!navigator.onLine||syncingRef.current)return;syncingRef.current=true;setSyncing(true);try{const result=await flushShoppingMutations(familyId,{onMapped:async(tempId,serverItem)=>{setLists(current=>{const next=replaceItem(current,tempId,serverItem);saveShoppingSnapshot(familyId,next).catch(()=>{});return next})}});setPending(result.pending);setFailed(result.failed>0||(await listShoppingMutations(familyId)).some(row=>(row.attempts||0)>=3));if(result.pending===0&&loaded)await refreshFromServer()}catch(error){if(error?.message!=='unauthorized')setFailed(true)}finally{syncingRef.current=false;setSyncing(false);await markQueue()}}
 useEffect(()=>{setLoaded(false);setLists([]);setActive(null);load()},[familyId]);
 useEffect(()=>{const online=()=>flush();window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[familyId,loaded]);

 const list=lists.find(row=>row.id===active)||lists[0];const items=list?.items||[];const open=items.filter(item=>!item.checked);const checked=items.filter(item=>item.checked);const total=items.length;const progress=total?Math.round(checked.length/total*100):0;
 const groups=useMemo(()=>{const out={};open.forEach(item=>{const key=item.category||t('other');(out[key]||(out[key]=[])).push(item)});Object.values(out).forEach(rows=>rows.sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.name.localeCompare(b.name)));return out},[open,t]);

 async function queueAndMaybeFlush(mutation,next){await persist(next);await queueShoppingMutation(familyId,mutation);await markQueue();if(navigator.onLine)await flush();else toast(t('shoppingOffline.queued'),{type:'info'});onChanged?.()}
 async function create(name){if(!list){toast(t('shoppingOffline.noSnapshot'),{type:'error'});return}const tempId=optimisticId();const item={id:tempId,shopping_list:list.id,name,quantity:'',category:'',aisle:'',note:'',favorite:false,checked:false,added_by_name:'',_pending:true};const next=lists.map(row=>row.id===list.id?{...row,items:[...(row.items||[]),item],open_count:(row.open_count||0)+1}:row);await queueAndMaybeFlush({type:'add',tempId,payload:{family:familyId,shopping_list:list.id,name,quantity:'',category:'',aisle:'',note:''}},next)}
 async function setChecked(item,checkedValue){const next=updateItem(lists,item.id,{checked:checkedValue});await queueAndMaybeFlush({type:'checked',itemId:String(item.id),payload:{checked:checkedValue}},next)}
 async function setFavorite(item,favoriteValue){const next=updateItem(lists,item.id,{favorite:favoriteValue});await queueAndMaybeFlush({type:'favorite',itemId:String(item.id),payload:{favorite:favoriteValue}},next)}
 async function saveEdit(item,values){const patch={...values};const next=updateItem(lists,item.id,patch);setEditing(null);await queueAndMaybeFlush({type:'edit',itemId:String(item.id),payload:patch},next)}
 async function clearChecked(){if(!list||!checked.length||!navigator.onLine){if(!navigator.onLine)toast(t('shoppingOffline.offlineHint'),{type:'info'});return}const ok=await confirmAction({title:t('finishShopping'),message:t('finishShoppingMessage',{count:checked.length}),confirmLabel:t('cleanUp')});if(!ok)return;try{await api(`/smart/shopping-lists/${list.id}/clear-checked/`,{method:'POST'});await refreshFromServer();onChanged?.()}catch(error){toast(error.message||t('cleanItemsFailed'),{type:'error'})}}

 if(!loaded)return <div className="smart-page"><div className="smart-head"><div><small>{t('shoppingTogether')}</small><h1>{t('shopping')}</h1></div></div><div className="smart-empty" role={loadError?'alert':'status'}><Icon name={loadError?'warning':'refresh'} size={34}/><strong>{loadError||t('sessionUi.loading')}</strong>{loadError&&<button className="secondary compact" onClick={load}><Icon name="refresh"/>{t('sessionUi.retry')}</button>}</div></div>;
 return <div className={`smart-page shopping-page ${storeMode?'store-mode':''}`}>
  <div className="smart-head"><div><small>{storeMode?t('inStore'):t('shoppingTogether')}</small><h1>{t('shopping')}</h1></div><div className="metric-row"><span><b>{open.length}</b> {t('open')}</span>{pending>0&&<span className="warn"><Icon name="refresh"/><b>{pending}</b> {t('shoppingOffline.pending')}</span>}</div></div>
  <div className={`integration-notice ${failed?'error':''}`} role={failed?'alert':'status'}><Icon name={failed?'warning':navigator.onLine?'online':'offline'}/><div className="grow"><strong>{failed?t('shoppingOffline.syncFailed'):syncing?t('shoppingOffline.syncing'):navigator.onLine?t('shoppingOffline.offlineReady'):t('shoppingOffline.pending')}</strong><span>{t('shoppingOffline.offlineHint')}</span></div>{(failed||pending>0)&&navigator.onLine&&!syncing&&<button className="secondary compact" onClick={flush}><Icon name="refresh"/>{t('shoppingOffline.retry')}</button>}</div>
  <div className="shopping-session-card"><div className="shopping-session-head"><div className="shopping-session-title"><span className="round-icon"><Icon name="shopping"/></span><div><strong>{list?.name||t('shopping')}</strong><small>{list?.store||t('sharedShoppingList')}</small></div></div><div className="shopping-mode-toggle" role="group" aria-label={t('shoppingMode')}><button className={!storeMode?'active':''} onClick={()=>setStoreMode(false)}><Icon name="settings"/> {t('planning')}</button><button className={storeMode?'active':''} onClick={()=>setStoreMode(true)}><Icon name="shopping"/> {t('inStore')}</button></div></div><div className="shopping-progress-line"><span>{t('doneCount',{done:checked.length,total})}</span><strong>{progress}%</strong></div><div className="shopping-progress-track"><span style={{width:`${progress}%`}}/></div></div>
  <OfflineInput onCreate={create}/>
  <div className="list-tabs shopping-list-tabs">{lists.map(row=><button key={row.id} className={list?.id===row.id?'active':''} onClick={()=>setActive(row.id)}><Icon name="shopping"/>{row.name}<b>{(row.items||[]).filter(item=>!item.checked).length}</b></button>)}</div>
  <div className="smart-toolbar shopping-toolbar">{checked.length>0&&<button onClick={clearChecked} disabled={!navigator.onLine}><Icon name="doneAll"/> {storeMode?t('finishShoppingAction'):t('cleanDone')}</button>}</div>
  <section className="shopping-groups">{Object.entries(groups).map(([category,rows])=><div className="shopping-group" key={category}><h3>{category}<span>{rows.length}</span></h3>{rows.map(item=><article className={`smart-row shopping-row ${item._pending?'pending-row':''}`} key={item.id}><button className="smart-check" onClick={()=>setChecked(item,true)} aria-label={`${item.name} · ${t('complete')}`}><Icon name="check"/></button><button className="smart-row-main row-main-button" onClick={()=>setEditing(item)}><div className="smart-title"><strong>{item.name}</strong>{item.favorite&&<span className="favorite-badge"><Icon name="favorite"/> {t('favorite')}</span>}<PendingBadge item={item} t={t}/></div><div className="smart-meta shopping-meta">{item.quantity&&<span className="shopping-quantity">{item.quantity}</span>}{item.aisle&&<span><Icon name="location"/>{item.aisle}</span>}</div>{item.note&&<p>{item.note}</p>}</button><button className={`row-action ${item.favorite?'favorite':''}`} onClick={()=>setFavorite(item,!item.favorite)} aria-label={t('markFavorite',{name:item.name})}><Icon name="favorite"/></button><Icon name="next"/></article>)}</div>)}{!open.length&&<div className={`smart-empty ${storeMode&&checked.length?'shopping-complete':''}`}><Icon name="doneAll" size={34}/><strong>{storeMode&&checked.length?t('shoppingComplete'):t('listEmpty')}</strong><span>{storeMode&&checked.length?t('shoppingCompleteHint'):t('frequentItemsHint')}</span></div>}</section>
  {checked.length>0&&<details className="done-items"><summary><Icon name="doneAll"/> {checked.length} {storeMode?t('alreadyInCart'):t('completed')}</summary>{checked.map(item=><button key={item.id} onClick={()=>setChecked(item,false)}><Icon name="check"/><span>{item.name}</span>{item._pending&&<small>{t('shoppingOffline.pending')}</small>}</button>)}</details>}
  {editing&&<OfflineEdit item={editing} t={t} onClose={()=>setEditing(null)} onSave={values=>saveEdit(editing,values)}/>} 
 </div>
}

function OfflineEdit({item,t,onClose,onSave}){const [value,setValue]=useState({name:item.name||'',quantity:item.quantity||'',category:item.category||'',aisle:item.aisle||'',note:item.note||'',favorite:!!item.favorite});const [busy,setBusy]=useState(false);const set=(key,next)=>setValue(current=>({...current,[key]:next}));async function submit(e){e.preventDefault();setBusy(true);await onSave(value)}return <div className="sheet-backdrop"><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('shoppingItem')}</small><h2>{item.name}</h2></div><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={submit}><label>{t('item')}<input value={value.name} onChange={e=>set('name',e.target.value)} required autoFocus/></label><div className="form-grid"><label>{t('quantity')}<input value={value.quantity} onChange={e=>set('quantity',e.target.value)}/></label><label>{t('category')}<input value={value.category} onChange={e=>set('category',e.target.value)}/></label></div><label>{t('aisle')}<input value={value.aisle} onChange={e=>set('aisle',e.target.value)}/></label><label>{t('note')}<textarea rows="2" value={value.note} onChange={e=>set('note',e.target.value)}/></label><label className="toggle-label"><input type="checkbox" checked={value.favorite} onChange={e=>set('favorite',e.target.checked)}/><span><Icon name="favorite"/> {t('favoriteHint')}</span></label><button className="primary" disabled={busy||!value.name.trim()}><Icon name="check"/>{busy?t('saving'):t('save')}</button></form></section></div>}
