import {useEffect,useState} from 'react';
import {api} from './api';
import i18n from './i18n';
import {Icon} from './icons';
import {toast} from './feedback';
import './prediction-cards.css';

export default function PredictionCards({family,onChanged,kind=null}){
 const [rows,setRows]=useState([]);const [busy,setBusy]=useState('');const de=i18n.language.startsWith('de');
 async function load(){if(!family?.id)return;const result=await api(`/predictions/?family=${encodeURIComponent(family.id)}`);setRows((result.suggestions||[]).filter(row=>!kind||row.kind===kind))}
 useEffect(()=>{load().catch(()=>setRows([]))},[family?.id,kind]);
 async function feedback(row,action,extra={}){await api('/predictions/feedback/',{method:'POST',body:JSON.stringify({family:family.id,kind:row.kind,subject_key:row.subject_key,action,...extra})})}
 async function accept(row){setBusy(row.id);try{if(row.kind==='shopping')await api('/smart/shopping/quick-add/',{method:'POST',body:JSON.stringify({family:family.id,name:row.title,quantity:row.quantity||'',category:row.category||''})});else await api(`/routines/${row.routine_id}/done/`,{method:'POST',body:'{}'});await feedback(row,'accept');await load();await onChanged?.();toast(row.kind==='shopping'?(de?`${row.title} zur Einkaufsliste hinzugefügt.`:`Added ${row.title} to shopping.`):(de?`${row.title} erledigt.`:`Completed ${row.title}.`),{type:'success'})}catch(error){toast(error.message||(de?'Aktion fehlgeschlagen.':'Action failed.'),{type:'error'})}finally{setBusy('')}}
 async function quiet(row,action){setBusy(row.id);try{await feedback(row,action,action==='snooze'?{days:3}:{});await load()}catch(error){toast(error.message||(de?'Aktion fehlgeschlagen.':'Action failed.'),{type:'error'})}finally{setBusy('')}}
 if(!rows.length)return null;const confidence=row=>row.confidence_label==='high'?(de?'Hohe':'High'):row.confidence_label==='medium'?(de?'Mittlere':'Medium'):(de?'Niedrige':'Low');
 return <section className="today-section prediction-section" aria-labelledby={`prediction-heading-${kind||'all'}`}><div className="today-section-head"><div><small>{de?'VORSCHLÄGE':'SUGGESTIONS'}</small><h2 id={`prediction-heading-${kind||'all'}`}>{kind==='shopping'?(de?'Wahrscheinlich bald wieder nötig':'Probably needed again soon'):(de?'Könnte bald anstehen':'Might be due soon')}</h2></div><span>{rows.length}</span></div><div className="prediction-grid">{rows.map(row=><article className="prediction-card" key={row.id}><span className="prediction-icon"><Icon name={row.kind==='shopping'?'shopping':'history'}/></span><div className="prediction-copy"><strong>{row.title}</strong><span>{de?'Etwa alle':'About every'} {Math.round(row.interval_days)} {de?'Tage':'days'} · {row.sample_count} {de?'Beobachtungen':'observations'}</span><small className={`prediction-confidence ${row.confidence_label}`}>{confidence(row)} {de?'Sicherheit':'confidence'} · {Math.round(row.confidence*100)} %</small></div><div className="prediction-actions"><button className="primary compact" disabled={busy===row.id} onClick={()=>accept(row)}><Icon name="check"/>{row.kind==='shopping'?(de?'Hinzufügen':'Add'):(de?'Erledigt':'Done')}</button><button className="secondary compact" disabled={busy===row.id} onClick={()=>quiet(row,'snooze')}>{de?'Später':'Later'}</button><button className="text-button" disabled={busy===row.id} onClick={()=>quiet(row,'dismiss')}>{de?'Ausblenden':'Hide'}</button></div></article>)}</div><p className="prediction-note"><Icon name="info"/> {de?'Vorschläge werden nur aus den Daten dieser Familie berechnet. Es wird nichts automatisch ausgeführt.':'Suggestions are calculated only from this family’s data. Nothing is performed automatically.'}</p></section>
}
