import {useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import './baby-i18n';
import './pregnancy-baby.css';

const isoNow=()=>new Date().toISOString();
const dateToday=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;

function Panel({children,className=''}){return <section className={`card baby-panel ${className}`}>{children}</section>}
function Toggle({checked,onChange,label,hint}){return <label className="baby-toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span><strong>{label}</strong>{hint&&<small>{hint}</small>}</span></label>}
function TabButton({active,onClick,children}){return <button className={active?'active':''} onClick={onClick}>{children}</button>}

export default function PregnancyBabyHub({family,onBack,onModuleChange}){
 const {t,i18n}=useTranslation();
 const [module,setModule]=useState(null);const [pregnancies,setPregnancies]=useState([]);const [babies,setBabies]=useState([]);const [selectedBaby,setSelectedBaby]=useState('');const [tab,setTab]=useState('pregnancy');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const activePregnancy=pregnancies.find(x=>x.status==='active');const baby=babies.find(x=>String(x.id)===String(selectedBaby))||babies[0];
 const permissions=module?.permissions||{};const canPregnancy=!!permissions.can_view_pregnancy;const canCare=!!permissions.can_log_care;const canGrowth=!!permissions.can_view_growth_development;
 async function loadModule(){if(!family)return;const row=await api(`/baby/module/?family=${encodeURIComponent(family.id)}`);setModule(row);onModuleChange?.(row);return row}
 async function loadPrivate(row=module){if(!family||!row?.enabled||!row?.authorized)return;const jobs=[];if(row.permissions?.can_view_pregnancy)jobs.push(api(`/baby/pregnancies/?family=${encodeURIComponent(family.id)}`).then(x=>setPregnancies(x.pregnancies||[])));if(row.permissions?.can_log_care||row.permissions?.can_view_growth_development)jobs.push(api(`/baby/profiles/?family=${encodeURIComponent(family.id)}`).then(x=>{setBabies(x.babies||[]);setSelectedBaby(v=>v||(x.babies?.[0]?.id||''))}));await Promise.all(jobs)}
 useEffect(()=>{let live=true;(async()=>{setError('');try{const row=await loadModule();if(live)await loadPrivate(row)}catch(e){if(live)setError(e.message||t('babyUi.error'))}})();return()=>{live=false}},[family?.id]);
 async function refresh(){const row=await loadModule();await loadPrivate(row)}
 async function action(fn,success=t('babyUi.saved')){setBusy(true);setError('');try{const result=await fn();toast(success,{type:'success'});return result}catch(e){setError(e.message||t('babyUi.error'));toast(e.message||t('babyUi.error'),{type:'error'});throw e}finally{setBusy(false)}}
 if(!family)return null;
 if(!module)return <div className="smart-empty"><Icon name="refresh"/><strong>{t('babyUi.loading')}</strong></div>;
 return <div className="baby-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{t('babyUi.privacy')}</small><h1>{t('babyUi.title')}</h1></div><span className="baby-private-pill"><Icon name="lock" size={13}/>{t('babyUi.careCircle')}</span></div>
 {error&&<div className="integration-notice" role="alert"><Icon name="warning"/><span>{error}</span></div>}
 {!module.enabled?<DisabledSetup module={module} family={family} busy={busy} t={t} onEnable={()=>action(async()=>{await api('/baby/module/',{method:'PATCH',body:JSON.stringify({family:family.id,enabled:true})});await refresh()},t('babyUi.saved'))}/>:!module.authorized?<Panel><div className="baby-locked"><Icon name="lock" size={28}/><strong>{t('babyUi.noAccess')}</strong><span>{t('babyUi.privacy')}</span></div></Panel>:<>
 <div className="baby-tabs" role="tablist">{canPregnancy&&<TabButton active={tab==='pregnancy'} onClick={()=>setTab('pregnancy')}>{t('babyUi.pregnancy')}</TabButton>}{baby&&canCare&&<TabButton active={tab==='now'} onClick={()=>setTab('now')}>{t('babyUi.now')}</TabButton>}{baby&&canGrowth&&<TabButton active={tab==='growth'} onClick={()=>setTab('growth')}>{t('babyUi.growth')}</TabButton>}{baby&&canGrowth&&<TabButton active={tab==='development'} onClick={()=>setTab('development')}>{t('babyUi.development')}</TabButton>}{baby&&(canCare||canGrowth)&&<TabButton active={tab==='report'} onClick={()=>setTab('report')}>{t('babyUi.report')}</TabButton>}{module.can_manage&&<TabButton active={tab==='settings'} onClick={()=>setTab('settings')}>{t('babyUi.settings')}</TabButton>}</div>
 {babies.length>1&&<label className="baby-selector"><span>{t('babyUi.babies')}</span><select value={baby?.id||''} onChange={e=>setSelectedBaby(e.target.value)}>{babies.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label>}
 {tab==='pregnancy'&&canPregnancy&&<PregnancyPanel family={family} pregnancy={activePregnancy} babies={babies} t={t} busy={busy} action={action} refresh={refresh}/>} 
 {tab==='now'&&baby&&canCare&&<CarePanel baby={baby} t={t} busy={busy} action={action}/>} 
 {tab==='growth'&&baby&&canGrowth&&<GrowthPanel baby={baby} t={t} busy={busy} action={action}/>} 
 {tab==='development'&&baby&&canGrowth&&<DevelopmentPanel baby={baby} t={t} language={i18n.language.startsWith('en')?'en':'de'} busy={busy} action={action}/>} 
 {tab==='report'&&baby&&<ReportPanel baby={baby} t={t}/>} 
 {tab==='settings'&&module.can_manage&&<SettingsPanel family={family} module={module} t={t} busy={busy} action={action} refresh={refresh}/>} 
 {!baby&&tab!=='pregnancy'&&tab!=='settings'&&<Panel><div className="smart-empty"><Icon name="heart"/><strong>{t('babyUi.emptyBaby')}</strong></div></Panel>}
 </>}
 </div>
}

function DisabledSetup({module,busy,t,onEnable}){return <Panel><div className="baby-locked"><Icon name="heart" size={30}/><h2>{t('babyUi.disabled')}</h2><p>{t('babyUi.activateHint')}</p>{module.can_manage?<button className="primary" disabled={busy} onClick={onEnable}><Icon name="plus"/>{t('babyUi.enable')}</button>:<span>{t('babyUi.noAccess')}</span>}</div></Panel>}

function PregnancyPanel({family,pregnancy,babies,t,busy,action,refresh}){
 const [due,setDue]=useState('');const [count,setCount]=useState(1);const [journal,setJournal]=useState('');const [contraction,setContraction]=useState(null);const [showBirth,setShowBirth]=useState(false);const [birth,setBirth]=useState({});const [born,setBorn]=useState({name:'',birth_date:dateToday(),gestational_age_weeks:'',birth_weight_g:'',growth_reference_sex:'unspecified'});
 useEffect(()=>{if(pregnancy)setBirth(Object.fromEntries((pregnancy.babies||[]).map(x=>[x.id,{pregnancy_baby:x.id,display_name:x.display_name||x.stable_label,birth_date:dateToday(),gestational_age_weeks:'',gestational_age_days:0,birth_weight_g:'',growth_reference_sex:'unspecified'}])))},[pregnancy?.id]);
 if(!pregnancy)return <><Panel><h2>{t('babyUi.pregnancy')}</h2><div className="form-grid"><label>{t('babyUi.dueDate')}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>{t('babyUi.babyCount')}<select value={count} onChange={e=>setCount(Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label></div><button className="primary" disabled={busy||!due} onClick={()=>action(async()=>{await api('/baby/pregnancies/',{method:'POST',body:JSON.stringify({family:family.id,expected_due_date:due,baby_count:count})});await refresh()},t('babyUi.created'))}><Icon name="plus"/>{t('babyUi.startPregnancy')}</button></Panel><AlreadyBorn family={family} value={born} setValue={setBorn} t={t} busy={busy} action={action} refresh={refresh}/></>;
 return <>
 <Panel className="pregnancy-hero"><small>{t('babyUi.dueDate')} · {pregnancy.expected_due_date}</small><h2>{t('babyUi.week',{week:pregnancy.progress.week,day:pregnancy.progress.day})}</h2><p>{t('babyUi.daysUntil',{count:pregnancy.progress.days_until_due})}</p><div className="baby-chip-row">{pregnancy.babies.map(x=><span className="chip" key={x.id}>{x.display_name||x.stable_label}</span>)}</div><div className="baby-actions"><button className="secondary" disabled={busy} onClick={()=>action(()=>api(`/baby/pregnancies/${pregnancy.id}/templates/`,{method:'POST',body:JSON.stringify({tasks:true,shopping:true})}),t('babyUi.created'))}><Icon name="tasks"/>{t('babyUi.templates')}</button><button className="primary" onClick={()=>setShowBirth(v=>!v)}><Icon name="heart"/>{t('babyUi.birth')}</button></div></Panel>
 <Panel><h3>{t('babyUi.pregnancy')}</h3><div className="baby-quick-grid"><button disabled={busy} onClick={()=>action(()=>api(`/baby/pregnancies/${pregnancy.id}/utilities/`,{method:'POST',body:JSON.stringify({kind:'kick',started_at:isoNow(),ended_at:isoNow(),client_event_id:uid(),value:{count:1}})}),t('babyUi.saved'))}><Icon name="plus"/><strong>{t('babyUi.kick')}</strong></button><button disabled={busy} onClick={()=>action(async()=>{if(!contraction){const x=await api(`/baby/pregnancies/${pregnancy.id}/utilities/`,{method:'POST',body:JSON.stringify({kind:'contraction',started_at:isoNow(),client_event_id:uid()})});setContraction(x)}else{await api(`/baby/pregnancy-utilities/${contraction.id}/`,{method:'PATCH',body:JSON.stringify({ended_at:isoNow()})});setContraction(null)}},t('babyUi.saved'))}><Icon name="clock"/><strong>{contraction?t('babyUi.contractionStop'):t('babyUi.contractionStart')}</strong></button></div><label>{t('babyUi.journal')}<textarea value={journal} onChange={e=>setJournal(e.target.value)} placeholder={t('babyUi.journalPlaceholder')}/></label><button className="secondary" disabled={busy||!journal.trim()} onClick={()=>action(async()=>{await api(`/baby/pregnancies/${pregnancy.id}/journal/`,{method:'POST',body:JSON.stringify({entry_date:dateToday(),note:journal})});setJournal('')})}>{t('babyUi.save')}</button></Panel>
 {showBirth&&<Panel><h2>{t('babyUi.birth')}</h2><div className="stack">{pregnancy.babies.map(x=>{const row=birth[x.id]||{};const set=(key,value)=>setBirth(v=>({...v,[x.id]:{...v[x.id],[key]:value}}));return <fieldset className="baby-birth-card" key={x.id}><legend>{x.display_name||x.stable_label}</legend><div className="form-grid"><label>{t('babyUi.name')}<input value={row.display_name||''} onChange={e=>set('display_name',e.target.value)}/></label><label>{t('babyUi.birthDate')}<input type="date" value={row.birth_date||''} onChange={e=>set('birth_date',e.target.value)}/></label><label>{t('babyUi.gestation')}<input type="number" min="20" max="44" value={row.gestational_age_weeks||''} onChange={e=>set('gestational_age_weeks',e.target.value?Number(e.target.value):null)}/></label><label>{t('babyUi.birthWeight')}<input inputMode="numeric" value={row.birth_weight_g||''} onChange={e=>set('birth_weight_g',e.target.value?Number(e.target.value):null)}/></label><label>{t('babyUi.growthSex')}<select value={row.growth_reference_sex||'unspecified'} onChange={e=>set('growth_reference_sex',e.target.value)}><option value="unspecified">{t('babyUi.unspecified')}</option><option value="female">{t('babyUi.female')}</option><option value="male">{t('babyUi.male')}</option></select></label></div></fieldset>})}</div><button className="primary" disabled={busy} onClick={()=>action(async()=>{await api(`/baby/pregnancies/${pregnancy.id}/birth/`,{method:'POST',body:JSON.stringify({babies:Object.values(birth)})});setShowBirth(false);await refresh()},t('babyUi.saved'))}>{t('babyUi.saveBirth')}</button></Panel>}
 </>
}

function AlreadyBorn({family,value,setValue,t,busy,action,refresh}){const set=(k,v)=>setValue(x=>({...x,[k]:v}));return <Panel><h3>{t('babyUi.alreadyBorn')}</h3><div className="form-grid"><label>{t('babyUi.name')}<input value={value.name} onChange={e=>set('name',e.target.value)}/></label><label>{t('babyUi.birthDate')}<input type="date" value={value.birth_date} onChange={e=>set('birth_date',e.target.value)}/></label><label>{t('babyUi.gestation')}<input type="number" min="20" max="44" value={value.gestational_age_weeks} onChange={e=>set('gestational_age_weeks',e.target.value)}/></label><label>{t('babyUi.birthWeight')}<input inputMode="numeric" value={value.birth_weight_g} onChange={e=>set('birth_weight_g',e.target.value)}/></label></div><button className="secondary" disabled={busy||!value.name||!value.birth_date} onClick={()=>action(async()=>{await api('/baby/profiles/',{method:'POST',body:JSON.stringify({family:family.id,client_identity_key:uid(),display_name:value.name,birth_date:value.birth_date,gestational_age_weeks:value.gestational_age_weeks?Number(value.gestational_age_weeks):null,birth_weight_g:value.birth_weight_g?Number(value.birth_weight_g):null,growth_reference_sex:value.growth_reference_sex})});await refresh()},t('babyUi.created'))}>{t('babyUi.save')}</button></Panel>}

function CarePanel({baby,t,busy,action}){const [data,setData]=useState(null);const [amount,setAmount]=useState('');const [sleep,setSleep]=useState(null);async function load(){setData(await api(`/baby/profiles/${baby.id}/care/?hours=24`));await api(`/baby/profiles/${baby.id}/viewed/`,{method:'POST',body:'{}'})}useEffect(()=>{load().catch(()=>{})},[baby.id]);async function record(kind,value={}){const row=await action(()=>api(`/baby/profiles/${baby.id}/care/`,{method:'POST',body:JSON.stringify({kind,started_at:isoNow(),value,client_event_id:uid()})}),t('babyUi.saved'));await load();return row}return <><Panel><h2>{baby.display_name} · {t('babyUi.now')}</h2><div className="baby-quick-grid">{[['breastfeed','heart'],['diaper','receipt'],['pump','upload'],['temperature','warning'],['medication','plus']].map(([kind,icon])=><button key={kind} disabled={busy} onClick={()=>record(kind)}><Icon name={icon}/><strong>{t(`babyUi.${kind}`)}</strong><small>{data?.summary?.last?.[kind]?new Date(data.summary.last[kind]).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'–'}</small></button>)}<button className={sleep?'active':''} disabled={busy} onClick={()=>action(async()=>{if(!sleep){const row=await api(`/baby/profiles/${baby.id}/care/`,{method:'POST',body:JSON.stringify({kind:'sleep',started_at:isoNow(),client_event_id:uid()})});setSleep(row)}else{await api(`/baby/care/${sleep.id}/`,{method:'PATCH',body:JSON.stringify({expected_version:sleep.version,ended_at:isoNow()})});setSleep(null)}await load()})}><Icon name="clock"/><strong>{t('babyUi.sleep')}</strong><small>{sleep?t('babyUi.contractionStop'):t('babyUi.record')}</small></button></div></Panel><Panel><h3>{t('babyUi.bottle')}</h3><div className="baby-inline-form"><input inputMode="decimal" placeholder={t('babyUi.amountMl')} value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary compact" disabled={busy||!amount} onClick={()=>record('bottle',{ml:Number(amount)}).then(()=>setAmount(''))}>{t('babyUi.record')}</button></div></Panel><Panel><div className="baby-section-head"><h3>{t('babyUi.last24')}</h3><span>{data?.events?.length||0}</span></div><div className="baby-timeline">{(data?.events||[]).slice(0,30).map((x,index)=><div className="baby-event" key={x.id}><Icon name={x.kind==='sleep'?'clock':'heart'}/><div><strong>{t(`babyUi.${x.kind}`,{defaultValue:x.kind})}</strong><small>{new Date(x.started_at).toLocaleString()}</small></div>{index===0&&<button className="text-button" onClick={()=>action(async()=>{await api(`/baby/care/${x.id}/`,{method:'DELETE'});await load()},t('babyUi.undo'))}>{t('babyUi.undo')}</button>}</div>)}</div></Panel></>}

function GrowthPanel({baby,t,busy,action}){const [data,setData]=useState(null);const [form,setForm]=useState({weight_g:'',length_cm:'',head_circumference_cm:'',source:'home'});async function load(){setData(await api(`/baby/profiles/${baby.id}/growth/`))}useEffect(()=>{load().catch(()=>{})},[baby.id]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));return <><Panel><h2>{t('babyUi.growth')}</h2><div className="form-grid"><label>{t('babyUi.weight')}<input inputMode="numeric" value={form.weight_g} onChange={e=>set('weight_g',e.target.value)}/></label><label>{t('babyUi.length')}<input inputMode="decimal" value={form.length_cm} onChange={e=>set('length_cm',e.target.value)}/></label><label>{t('babyUi.head')}<input inputMode="decimal" value={form.head_circumference_cm} onChange={e=>set('head_circumference_cm',e.target.value)}/></label></div><button className="primary" disabled={busy||(!form.weight_g&&!form.length_cm&&!form.head_circumference_cm)} onClick={()=>action(async()=>{await api(`/baby/profiles/${baby.id}/growth/`,{method:'POST',body:JSON.stringify({measured_at:isoNow(),weight_g:form.weight_g?Number(form.weight_g):null,length_cm:form.length_cm?Number(form.length_cm):null,head_circumference_cm:form.head_circumference_cm?Number(form.head_circumference_cm):null,source:'home'})});setForm({weight_g:'',length_cm:'',head_circumference_cm:'',source:'home'});await load()})}>{t('babyUi.record')}</button></Panel><Panel><label>{t('babyUi.reference')}<select value={data?.reference?.key||'who_2006'} onChange={e=>action(async()=>{await api(`/baby/profiles/${baby.id}/growth-reference/`,{method:'PATCH',body:JSON.stringify({reference_key:e.target.value,corrected_age_enabled:e.target.value==='who_2006_corrected'})});await load()})}><option value="who_2006">{t('babyUi.who')}</option><option value="who_2006_corrected">{t('babyUi.whoCorrected')}</option><option value="intergrowth_21_postnatal">{t('babyUi.intergrowth')}</option></select></label><p className="baby-reference-note">{t('babyUi.percentileNote')}</p><GrowthChart points={data?.points||[]}/></Panel></>}
function GrowthChart({points}){const values=points.map(x=>x.metrics?.weight_g?.percentile).filter(x=>x!=null);if(!values.length)return <div className="smart-empty"><Icon name="trend"/><span>–</span></div>;const w=640,h=180;const path=values.map((v,i)=>`${i?'L':'M'} ${values.length===1?w/2:(i/(values.length-1))*w} ${h-(Math.max(0,Math.min(100,v))/100)*h}`).join(' ');return <svg className="baby-growth-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Percentile trend"><line x1="0" x2={w} y1={h/2} y2={h/2}/><path d={path} fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/></svg>}

function DevelopmentPanel({baby,t,language,busy,action}){const [data,setData]=useState(null);async function load(){setData(await api(`/baby/profiles/${baby.id}/development/?language=${language}`))}useEffect(()=>{load().catch(()=>{})},[baby.id,language]);return <><Panel><div className="baby-section-head"><div><small>{data?.source?.version}</small><h2>{t('babyUi.development')} · {data?.checklist_age_months||'–'} M.</h2></div><button className="secondary compact" onClick={()=>action(()=>api(`/baby/profiles/${baby.id}/preventive-events/`,{method:'POST',body:'{}'}),t('babyUi.created'))}>{t('babyUi.preventive')}</button></div><p className="baby-reference-note">{data?.interpretation}</p><div className="baby-milestones">{(data?.items||[]).map(item=><article key={item.key}><small>{item.category}</small><strong>{item.text}</strong><div className="segmented">{[['observed',t('babyUi.observed')],['not_observed',t('babyUi.notObserved')],['later',t('babyUi.later')]].map(([state,label])=><button key={state} className={item.state===state?'active':''} disabled={busy} onClick={()=>action(async()=>{await api(`/baby/profiles/${baby.id}/development/`,{method:'POST',body:JSON.stringify({milestone_key:item.key,state})});await load()})}>{label}</button>)}</div></article>)}</div></Panel></>}

function ReportPanel({baby,t}){const base=`/api/baby/profiles/${baby.id}/report/?sections=care,growth,development,handover`;return <><Panel><h2>{t('babyUi.report')}</h2><p>{t('babyUi.percentileNote')}</p><div className="baby-actions"><a className="secondary" href={`${base}&format=html`} target="_blank" rel="noreferrer"><Icon name="receipt"/>{t('babyUi.exportHtml')}</a><a className="secondary" href={`${base}&format=csv`}><Icon name="download"/>{t('babyUi.exportCsv')}</a></div></Panel><HandoverCreate baby={baby} t={t}/></>}
function HandoverCreate({baby,t}){const [note,setNote]=useState('');const [result,setResult]=useState(null);async function create(){const to=new Date(),from=new Date(to.getTime()-24*3600*1000);const row=await api(`/baby/profiles/${baby.id}/handover/`,{method:'POST',body:JSON.stringify({from_at:from.toISOString(),to_at:to.toISOString(),note})});setResult(await api(`/baby/handover/${row.id}/`));toast(t('babyUi.created'),{type:'success'})}return <Panel><h3>{t('babyUi.handover')}</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t('babyUi.note')}/><button className="secondary" onClick={create}>{t('babyUi.createHandover')}</button>{result&&<div className="baby-handover-summary">{Object.entries(result.counts||{}).map(([key,value])=><span className="chip" key={key}>{key}: {value}</span>)}</div>}</Panel>}

function SettingsPanel({family,module,t,busy,action,refresh}){const [rows,setRows]=useState([]);async function load(){const x=await api(`/baby/care-circle/?family=${family.id}`);setRows(x.care_circle||[])}useEffect(()=>{load().catch(()=>{})},[family.id]);const update=(id,key,value)=>setRows(current=>current.map(x=>x.membership===id?{...x,[key]:value}:x));const members=family.memberships||[];const merged=useMemo(()=>members.map(member=>{const existing=rows.find(x=>String(x.membership)===String(member.id));return existing||{membership:member.id,display_name:member.display_name,role:member.role,can_view_pregnancy:false,can_log_care:false,can_view_growth_development:false,is_guardian:false}}),[members,rows]);return <><Panel><Toggle checked={module.show_in_main_navigation} label={t('babyUi.showNav')} hint={t('babyUi.mainNavHint')} onChange={value=>action(async()=>{await api('/baby/module/',{method:'PATCH',body:JSON.stringify({family:family.id,show_in_main_navigation:value})});await refresh()})}/><button className="ghost-danger" disabled={busy} onClick={()=>action(async()=>{await api('/baby/module/',{method:'PATCH',body:JSON.stringify({family:family.id,enabled:false})});await refresh()})}>{t('babyUi.disable')}</button></Panel><Panel><h2>{t('babyUi.careCircle')}</h2><div className="baby-care-circle">{merged.map(row=><article key={row.membership}><div><strong>{row.display_name||row.role}</strong><small>{row.role}</small></div><Toggle checked={row.can_view_pregnancy} label={t('babyUi.pregnancyPermission')} onChange={v=>update(row.membership,'can_view_pregnancy',v)}/><Toggle checked={row.can_log_care} label={t('babyUi.carePermission')} onChange={v=>update(row.membership,'can_log_care',v)}/><Toggle checked={row.can_view_growth_development} label={t('babyUi.growthPermission')} onChange={v=>update(row.membership,'can_view_growth_development',v)}/><Toggle checked={row.is_guardian} label={t('babyUi.guardian')} onChange={v=>update(row.membership,'is_guardian',v)}/></article>)}</div><button className="primary" disabled={busy} onClick={()=>action(async()=>{await api('/baby/care-circle/',{method:'PUT',body:JSON.stringify({family:family.id,care_circle:merged.map(({membership,can_view_pregnancy,can_log_care,can_view_growth_development,is_guardian})=>({membership,can_view_pregnancy,can_log_care,can_view_growth_development,is_guardian}))})});await load();await refresh()})}>{t('babyUi.save')}</button></Panel></>}
