import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import './profile-i18n';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import MemberAvatar from './MemberAvatar';
import './profile.css';

const empty={display_name:'',username:'',role:'',avatar_url:'',birth_month:'',birth_day:'',birth_year:'',birthday_visibility:'day_month'};

export default function ProfilePage({family,onBack,onChanged}){
 const {t}=useTranslation();
 const [profile,setProfile]=useState(empty);const [form,setForm]=useState(empty);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const chooseRef=useRef(null);const cameraRef=useRef(null);
 const familyId=family?.id;
 async function load(){if(!familyId)return;setLoading(true);try{const row=await api(`/profile/?family=${encodeURIComponent(familyId)}`);setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''})}catch(e){toast(e.message||t('profileUi.loadFailed'),{type:'error'})}finally{setLoading(false)}}
 useEffect(()=>{load()},[familyId]);
 async function save(event){event.preventDefault();setBusy(true);try{const payload={family:familyId,display_name:form.display_name.trim(),birth_month:form.birth_month===''?null:Number(form.birth_month),birth_day:form.birth_day===''?null:Number(form.birth_day),birth_year:form.birth_year===''?null:Number(form.birth_year),birthday_visibility:form.birthday_visibility};const row=await api(`/profile/?family=${encodeURIComponent(familyId)}`,{method:'PATCH',body:JSON.stringify(payload)});setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''});await onChanged?.();toast(t('profileUi.saved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.saveFailed'),{type:'error'})}finally{setBusy(false)}}
 async function upload(file){if(!file)return;setBusy(true);try{const body=new FormData();body.append('avatar',file);const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'POST',body});setProfile(row);setForm(current=>({...current,avatar_url:row.avatar_url}));await onChanged?.();toast(t('profileUi.photoSaved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.photoFailed'),{type:'error'})}finally{setBusy(false);if(chooseRef.current)chooseRef.current.value='';if(cameraRef.current)cameraRef.current.value=''}}
 async function removeAvatar(){setBusy(true);try{const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'DELETE'});setProfile(row);setForm(current=>({...current,avatar_url:''}));await onChanged?.();toast(t('profileUi.photoRemoved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.removeFailed'),{type:'error'})}finally{setBusy(false)}}
 const person={...profile,...form,avatar_url:profile.avatar_url};
 if(loading)return <div className="smart-empty" role="status"><Icon name="refresh" size={30}/><strong>{t('profileUi.loading')}</strong></div>;
 return <section className="profile-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{family?.name}</small><h1>{t('profileUi.title')}</h1></div></div>
  <section className="card profile-hero"><MemberAvatar person={person} size={112}/><div className="profile-identity"><strong>{form.display_name||profile.username}</strong><span>@{profile.username} · {profile.role}</span></div><div className="profile-photo-actions"><button className="secondary compact" type="button" onClick={()=>chooseRef.current?.click()} disabled={busy}><Icon name="edit"/> {t('profileUi.choose')}</button><button className="secondary compact" type="button" onClick={()=>cameraRef.current?.click()} disabled={busy}><Icon name="user"/> {t('profileUi.camera')}</button>{profile.avatar_url&&<button className="ghost-danger compact" type="button" onClick={removeAvatar} disabled={busy}><Icon name="delete"/> {t('profileUi.remove')}</button>}</div><input ref={chooseRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/><input ref={cameraRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>upload(e.target.files?.[0])}/><small className="profile-photo-note">{t('profileUi.photoHint')}</small></section>
  <form className="card profile-form" onSubmit={save}><label>{t('profileUi.name')}<input value={form.display_name||''} maxLength={80} onChange={e=>setForm(v=>({...v,display_name:e.target.value}))}/></label><fieldset><legend>{t('profileUi.birthday')}</legend><div className="profile-birthday-grid"><label>{t('profileUi.day')}<input inputMode="numeric" type="number" min="1" max="31" value={form.birth_day} onChange={e=>setForm(v=>({...v,birth_day:e.target.value}))} placeholder="TT"/></label><label>{t('profileUi.month')}<input inputMode="numeric" type="number" min="1" max="12" value={form.birth_month} onChange={e=>setForm(v=>({...v,birth_month:e.target.value}))} placeholder="MM"/></label><label>{t('profileUi.year')}<span>{t('profileUi.optional')}</span><input inputMode="numeric" type="number" min="1900" max={new Date().getFullYear()} value={form.birth_year} onChange={e=>setForm(v=>({...v,birth_year:e.target.value}))} placeholder="JJJJ"/></label></div><small>{t('profileUi.dateHint')}</small></fieldset><label>{t('profileUi.visibility',{family:family?.name})}<select value={form.birthday_visibility} onChange={e=>setForm(v=>({...v,birthday_visibility:e.target.value}))}><option value="hidden">{t('profileUi.hidden')}</option><option value="day_month">{t('profileUi.dayMonth')}</option><option value="full_date">{t('profileUi.fullDate')}</option></select></label><div className="profile-privacy-note"><Icon name="info"/><span>{t('profileUi.privacy')}</span></div><button className="primary" disabled={busy}>{t(busy?'saving':'save')}</button></form>
 </section>;
}
