import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import MemberAvatar from './MemberAvatar';
import './profile.css';

const empty={display_name:'',username:'',role:'',avatar_url:'',birth_month:'',birth_day:'',birth_year:'',birthday_visibility:'day_month'};

export default function ProfilePage({family,onBack,onChanged}){
 const [profile,setProfile]=useState(empty);const [form,setForm]=useState(empty);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const chooseRef=useRef(null);const cameraRef=useRef(null);
 const familyId=family?.id;
 async function load(){if(!familyId)return;setLoading(true);try{const row=await api(`/profile/?family=${encodeURIComponent(familyId)}`);setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''})}catch(e){toast(e.message||'Profil konnte nicht geladen werden.',{type:'error'})}finally{setLoading(false)}}
 useEffect(()=>{load()},[familyId]);
 async function save(event){event.preventDefault();setBusy(true);try{const payload={family:familyId,display_name:form.display_name.trim(),birth_month:form.birth_month===''?null:Number(form.birth_month),birth_day:form.birth_day===''?null:Number(form.birth_day),birth_year:form.birth_year===''?null:Number(form.birth_year),birthday_visibility:form.birthday_visibility};const row=await api(`/profile/?family=${encodeURIComponent(familyId)}`,{method:'PATCH',body:JSON.stringify(payload)});setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''});await onChanged?.();toast('Profil gespeichert.',{type:'success'})}catch(e){toast(e.message||'Profil konnte nicht gespeichert werden.',{type:'error'})}finally{setBusy(false)}}
 async function upload(file){if(!file)return;setBusy(true);try{const body=new FormData();body.append('avatar',file);const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'POST',body});setProfile(row);setForm(current=>({...current,avatar_url:row.avatar_url}));await onChanged?.();toast('Profilfoto aktualisiert.',{type:'success'})}catch(e){toast(e.message||'Profilfoto konnte nicht gespeichert werden.',{type:'error'})}finally{setBusy(false);if(chooseRef.current)chooseRef.current.value='';if(cameraRef.current)cameraRef.current.value=''}}
 async function removeAvatar(){setBusy(true);try{const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'DELETE'});setProfile(row);setForm(current=>({...current,avatar_url:''}));await onChanged?.();toast('Profilfoto entfernt.',{type:'success'})}catch(e){toast(e.message||'Profilfoto konnte nicht entfernt werden.',{type:'error'})}finally{setBusy(false)}}
 const person={...profile,...form,avatar_url:profile.avatar_url};
 if(loading)return <div className="smart-empty" role="status"><Icon name="refresh" size={30}/><strong>Profil wird geladen …</strong></div>;
 return <section className="profile-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label="Zurück"><Icon name="back"/></button><div className="grow"><small>{family?.name}</small><h1>Mein Profil</h1></div></div>
  <section className="card profile-hero"><MemberAvatar person={person} size={112}/><div className="profile-identity"><strong>{form.display_name||profile.username}</strong><span>@{profile.username} · {profile.role}</span></div><div className="profile-photo-actions"><button className="secondary compact" type="button" onClick={()=>chooseRef.current?.click()} disabled={busy}><Icon name="edit"/> Foto auswählen</button><button className="secondary compact" type="button" onClick={()=>cameraRef.current?.click()} disabled={busy}><Icon name="user"/> Foto aufnehmen</button>{profile.avatar_url&&<button className="ghost-danger compact" type="button" onClick={removeAvatar} disabled={busy}><Icon name="delete"/> Entfernen</button>}</div><input ref={chooseRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/><input ref={cameraRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>upload(e.target.files?.[0])}/><small className="profile-photo-note">JPEG, PNG oder WebP bis 10 MB. FamilyOS schneidet das Bild quadratisch zu, entfernt Metadaten und speichert nur optimierte Varianten.</small></section>
  <form className="card profile-form" onSubmit={save}><label>Name in dieser Familie<input value={form.display_name||''} maxLength={80} onChange={e=>setForm(v=>({...v,display_name:e.target.value}))}/></label><fieldset><legend>Geburtstag</legend><div className="profile-birthday-grid"><label>Tag<input inputMode="numeric" type="number" min="1" max="31" value={form.birth_day} onChange={e=>setForm(v=>({...v,birth_day:e.target.value}))} placeholder="TT"/></label><label>Monat<input inputMode="numeric" type="number" min="1" max="12" value={form.birth_month} onChange={e=>setForm(v=>({...v,birth_month:e.target.value}))} placeholder="MM"/></label><label>Jahr <span>optional</span><input inputMode="numeric" type="number" min="1900" max={new Date().getFullYear()} value={form.birth_year} onChange={e=>setForm(v=>({...v,birth_year:e.target.value}))} placeholder="JJJJ"/></label></div><small>Tag und Monat reichen. Das Jahr wird nur verwendet, wenn du es angibst.</small></fieldset><label>Wer darf meinen Geburtstag in {family?.name} sehen?<select value={form.birthday_visibility} onChange={e=>setForm(v=>({...v,birthday_visibility:e.target.value}))}><option value="hidden">Niemand – Geburtstag ausblenden</option><option value="day_month">Tag und Monat – Alter verborgen</option><option value="full_date">Vollständiges Datum – Alter darf angezeigt werden</option></select></label><div className="profile-privacy-note"><Icon name="info"/><span>Diese Sichtbarkeit gilt nur für diese Familie. Rolle und Rechte werden niemals aus Geburtstag oder Alter abgeleitet.</span></div><button className="primary" disabled={busy}>{busy?'Wird gespeichert …':'Speichern'}</button></form>
 </section>;
}
