import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import './profile-i18n';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import MemberAvatar from './MemberAvatar';
import FileDropZone from './FileDropZone';
import './profile.css';

const empty={display_name:'',username:'',role:'',avatar_url:'',birth_month:'',birth_day:'',birth_year:'',birthday_visibility:'day_month'};
const emptyFamily={family:'',name:'',slug:'',can_edit:false,image_url:'',address_street:'',address_house_number:'',address_postal_code:'',address_city:'',address_region:'',address_country_code:'',location_context:null};

export default function ProfilePage({family,onBack,onChanged}){
 const {t}=useTranslation();
 const [profile,setProfile]=useState(empty);const [form,setForm]=useState(empty);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const [familyData,setFamilyData]=useState(emptyFamily);const [familyForm,setFamilyForm]=useState(emptyFamily);const [familyBusy,setFamilyBusy]=useState(false);
 const familyId=family?.id;
 async function load(){if(!familyId)return;setLoading(true);try{const [row,master]=await Promise.all([api(`/profile/?family=${encodeURIComponent(familyId)}`),api(`/family-settings/?family=${encodeURIComponent(familyId)}`)]);setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''});setFamilyData(master);setFamilyForm(master)}catch(e){toast(e.message||t('profileUi.loadFailed'),{type:'error'})}finally{setLoading(false)}}
 useEffect(()=>{load()},[familyId]);
 async function save(event){event.preventDefault();setBusy(true);try{const payload={family:familyId,display_name:form.display_name.trim(),birth_month:form.birth_month===''?null:Number(form.birth_month),birth_day:form.birth_day===''?null:Number(form.birth_day),birth_year:form.birth_year===''?null:Number(form.birth_year),birthday_visibility:form.birthday_visibility};const row=await api(`/profile/?family=${encodeURIComponent(familyId)}`,{method:'PATCH',body:JSON.stringify(payload)});setProfile(row);setForm({...row,birth_month:row.birth_month??'',birth_day:row.birth_day??'',birth_year:row.birth_year??''});await onChanged?.();toast(t('profileUi.saved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.saveFailed'),{type:'error'})}finally{setBusy(false)}}
 async function upload(file){if(!file)return;setBusy(true);try{const body=new FormData();body.append('avatar',file);const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'POST',body});setProfile(row);setForm(current=>({...current,avatar_url:row.avatar_url}));await onChanged?.();toast(t('profileUi.photoSaved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.photoFailed'),{type:'error'})}finally{setBusy(false)}}
 async function removeAvatar(){setBusy(true);try{const row=await api(`/profile/avatar/?family=${encodeURIComponent(familyId)}`,{method:'DELETE'});setProfile(row);setForm(current=>({...current,avatar_url:''}));await onChanged?.();toast(t('profileUi.photoRemoved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.removeFailed'),{type:'error'})}finally{setBusy(false)}}
 async function saveFamily(event){event.preventDefault();if(!familyData.can_edit)return;setFamilyBusy(true);try{const payload={family:familyId,name:familyForm.name.trim(),address_street:familyForm.address_street.trim(),address_house_number:familyForm.address_house_number.trim(),address_postal_code:familyForm.address_postal_code.trim(),address_city:familyForm.address_city.trim(),address_region:familyForm.address_region.trim(),address_country_code:familyForm.address_country_code.trim().toUpperCase()};const row=await api(`/family-settings/?family=${encodeURIComponent(familyId)}`,{method:'PATCH',body:JSON.stringify(payload)});setFamilyData(row);setFamilyForm(row);await onChanged?.();toast(t('profileUi.familySaved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.familySaveFailed'),{type:'error'})}finally{setFamilyBusy(false)}}
 async function uploadFamilyImage(file){if(!file||!familyData.can_edit)return;setFamilyBusy(true);try{const body=new FormData();body.append('image',file);const row=await api(`/family-settings/image/?family=${encodeURIComponent(familyId)}`,{method:'POST',body});setFamilyData(row);setFamilyForm(current=>({...current,image_url:row.image_url}));await onChanged?.();toast(t('profileUi.familyPhotoSaved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.familyPhotoFailed'),{type:'error'})}finally{setFamilyBusy(false)}}
 async function removeFamilyImage(){if(!familyData.can_edit)return;setFamilyBusy(true);try{const row=await api(`/family-settings/image/?family=${encodeURIComponent(familyId)}`,{method:'DELETE'});setFamilyData(row);setFamilyForm(current=>({...current,image_url:''}));await onChanged?.();toast(t('profileUi.familyPhotoRemoved'),{type:'success'})}catch(e){toast(e.message||t('profileUi.familyPhotoRemoveFailed'),{type:'error'})}finally{setFamilyBusy(false)}}
 const person={...profile,...form,avatar_url:profile.avatar_url};const canEditFamily=familyData.can_edit;
 if(loading)return <div className="smart-empty" role="status"><Icon name="refresh" size={30}/><strong>{t('profileUi.loading')}</strong></div>;
 return <section className="profile-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{family?.name}</small><h1>{t('profileUi.title')}</h1></div></div>
  <section className="card profile-hero"><MemberAvatar person={person} size={112}/><div className="profile-identity"><strong>{form.display_name||profile.username}</strong><span>@{profile.username} · {profile.role}</span></div><div className="file-drop-zone-grid profile-photo-dropzones"><FileDropZone className="compact" accept="image/jpeg,image/png,image/webp" disabled={busy} icon="upload" title={t('profileUi.choose')} hint={t('profileUi.photoHint')} onFiles={files=>upload(files[0])}/><FileDropZone className="compact" accept="image/*" capture="user" disabled={busy} icon="camera" title={t('profileUi.camera')} hint={t('profileUi.photoHint')} onFiles={files=>upload(files[0])}/></div>{profile.avatar_url&&<button className="ghost-danger compact profile-photo-remove" type="button" onClick={removeAvatar} disabled={busy}><Icon name="delete"/> {t('profileUi.remove')}</button>}<small className="profile-photo-note">{t('profileUi.photoHint')}</small></section>
  <form className="card profile-form" onSubmit={save}><label>{t('profileUi.name')}<input value={form.display_name||''} maxLength={80} onChange={e=>setForm(v=>({...v,display_name:e.target.value}))}/></label><fieldset><legend>{t('profileUi.birthday')}</legend><div className="profile-birthday-grid"><label>{t('profileUi.day')}<input inputMode="numeric" type="number" min="1" max="31" value={form.birth_day} onChange={e=>setForm(v=>({...v,birth_day:e.target.value}))} placeholder="TT"/></label><label>{t('profileUi.month')}<input inputMode="numeric" type="number" min="1" max="12" value={form.birth_month} onChange={e=>setForm(v=>({...v,birth_month:e.target.value}))} placeholder="MM"/></label><label>{t('profileUi.year')}<span>{t('profileUi.optional')}</span><input inputMode="numeric" type="number" min="1900" max={new Date().getFullYear()} value={form.birth_year} onChange={e=>setForm(v=>({...v,birth_year:e.target.value}))} placeholder="JJJJ"/></label></div><small>{t('profileUi.dateHint')}</small></fieldset><label>{t('profileUi.visibility',{family:family?.name})}<select value={form.birthday_visibility} onChange={e=>setForm(v=>({...v,birthday_visibility:e.target.value}))}><option value="hidden">{t('profileUi.hidden')}</option><option value="day_month">{t('profileUi.dayMonth')}</option><option value="full_date">{t('profileUi.fullDate')}</option></select></label><div className="profile-privacy-note"><Icon name="info"/><span>{t('profileUi.privacy')}</span></div><button className="primary" disabled={busy}>{t(busy?'saving':'save')}</button></form>
  <section className="card family-master-card" data-testid="family-master-data"><div className="family-master-head"><div><small>{t('profileUi.familyMasterEyebrow')}</small><h2>{t('profileUi.familyMasterTitle')}</h2><p>{t(canEditFamily?'profileUi.familyMasterOwnerHint':'profileUi.familyMasterReadOnly')}</p></div>{familyData.image_url?<img className="family-master-image" src={familyData.image_url} alt={t('profileUi.familyPhotoAlt',{family:familyForm.name||family?.name})}/>:<div className="family-master-image family-master-image-empty" aria-hidden="true"><Icon name="members" size={30}/></div>}</div>{canEditFamily&&<div className="family-master-photo-actions"><FileDropZone className="compact" accept="image/jpeg,image/png,image/webp" disabled={familyBusy} icon="upload" title={t('profileUi.familyPhotoChoose')} hint={t('profileUi.familyPhotoHint')} onFiles={files=>uploadFamilyImage(files[0])}/>{familyData.image_url&&<button className="ghost-danger compact" type="button" onClick={removeFamilyImage} disabled={familyBusy}><Icon name="delete"/> {t('profileUi.familyPhotoRemove')}</button>}</div>}
   <form className="family-master-form" onSubmit={saveFamily}><label>{t('profileUi.familyName')}<input value={familyForm.name||''} maxLength={120} disabled={!canEditFamily||familyBusy} required onChange={e=>setFamilyForm(v=>({...v,name:e.target.value}))}/><small>{t('profileUi.familyNameHint')}</small></label><fieldset><legend>{t('profileUi.familyAddress')}</legend><div className="family-address-grid"><label className="family-address-street">{t('profileUi.street')}<input value={familyForm.address_street||''} maxLength={160} disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_street:e.target.value}))}/></label><label>{t('profileUi.houseNumber')}<input value={familyForm.address_house_number||''} maxLength={32} disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_house_number:e.target.value}))}/></label><label>{t('profileUi.postalCode')}<input value={familyForm.address_postal_code||''} maxLength={32} disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_postal_code:e.target.value}))}/></label><label className="family-address-city">{t('profileUi.city')}<input value={familyForm.address_city||''} maxLength={120} disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_city:e.target.value}))}/></label><label>{t('profileUi.region')}<input value={familyForm.address_region||''} maxLength={120} disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_region:e.target.value}))}/></label><label>{t('profileUi.countryCode')}<input value={familyForm.address_country_code||''} maxLength={2} autoCapitalize="characters" disabled={!canEditFamily||familyBusy} onChange={e=>setFamilyForm(v=>({...v,address_country_code:e.target.value.toUpperCase()}))}/></label></div></fieldset><div className="family-location-note"><Icon name="info"/><span>{t('profileUi.locationFutureHint')}</span></div><div className="family-slug-note"><span>{t('profileUi.technicalSlug')}</span><code>{familyData.slug}</code><small>{t('profileUi.technicalSlugHint')}</small></div>{canEditFamily&&<button className="primary" disabled={familyBusy}>{t(familyBusy?'saving':'profileUi.familySave')}</button>}</form>
  </section>
 </section>;
}
