import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {toast} from './feedback';
import RoutineEditor from './RoutineEditor';
import './routine-i18n';
import './routines.css';

export default function RoutinesHub({family,userId,onChanged}){
 const {t,i18n}=useTranslation();const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [edit,setEdit]=useState(null);const [filter,setFilter]=useState('active');const [search,setSearch]=useState('');const [busy,setBusy]=useState({});const pending=useRef(new Set());
 const date=value=>new Date(value).toLocaleString(i18n.language,{dateStyle:'medium',timeStyle:'short'});
 async function load(){if(!family?.id)return;setError('');try{let next=`/routines/?family=${encodeURIComponent(family.id)}`;const result=[];while(next){const response=await api(next);result.push(...(Array.isArray(response)?response:response.results||[]));if(response.next){const url=new URL(response.next,location.origin);next=url.pathname.replace(/^\/api/,'')+url.search}else next=null}setRows(result);const id=new URLSearchParams(location.search).get('routine');if(id)setEdit(result.find(x=>String(x.id)===id)||null)}catch(e){setError(e.message||t('routineUi.loadFailed'))}finally{setLoading(false)}}
 useEffect(()=>{load();const refresh=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',refresh);window.addEventListener('popstate',load);return()=>{document.removeEventListener('visibilitychange',refresh);window.removeEventListener('popstate',load)}},[family?.id]);
 async function record(row){if(pending.current.has(row.id))return;pending.current.add(row.id);setBusy(v=>({...v,[row.id]:true}));try{const log=await api(`/routines/${row.id}/done/`,{method:'POST',body:JSON.stringify({request_id:crypto.randomUUID()})});await load();onChanged?.();toast(t('routineUi.recorded',{name:row.name}),{type:'success',actionLabel:t('routineUi.undo'),onAction:async()=>{try{await api(`/routines/${row.id}/logs/${log.id}/`,{method:'DELETE'});await load();onChanged?.()}catch(e){toast(e.message,{type:'error'})}}})}catch(e){toast(e.message,{type:'error'})}finally{pending.current.delete(row.id);setBusy(v=>({...v,[row.id]:false}))}}
 function close(){setEdit(null);const url=new URL(location.href);url.searchParams.delete('routine');history.replaceState(history.state,'',url.pathname+url.search)}
 const visible=rows.filter(x=>(filter==='all'||(filter==='active'?x.active:!x.active))&&x.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>{const rank=x=>!x.active?3:['due','overdue'].includes(x.prediction?.status)?0:x.prediction?.expected_at?1:2;return rank(a)-rank(b)||a.name.localeCompare(b.name,i18n.language)});
 return <section className="routines-page"><div className="page-head"><div className="grow"><h1>{t('routineUi.title')}</h1><p>{t('routineUi.hint')}</p></div><button className="primary compact" onClick={()=>setEdit({})}><Icon name="plus"/>{t('routineUi.add')}</button></div><div className="routine-filters"><label className="grow"><span className="sr-only">{t('routineUi.search')}</span><input type="search" value={search} placeholder={t('routineUi.search')} onChange={e=>setSearch(e.target.value)}/></label><select aria-label={t('routineUi.title')} value={filter} onChange={e=>setFilter(e.target.value)}>{['active','paused','all'].map(key=><option key={key} value={key}>{t(`routineUi.${key}`)}</option>)}</select></div>{error&&<div role="alert">{error}<button onClick={load}>{t('routineUi.reload')}</button></div>}{loading&&<p role="status">{t('loading')}</p>}<div className="stack">{visible.map(row=><article className="card routine-card" key={row.id}><div className="row"><Icon name="history"/><button className="grow row-main-button" onClick={()=>setEdit(row)}><strong>{row.name}</strong><span>{row.last_done_at?t('routineUi.last',{date:date(row.last_done_at)}):t('routineUi.never')}</span></button><button className="routine-done" aria-label={t('routineUi.record',{name:row.name})} disabled={!row.active||busy[row.id]} onClick={()=>record(row)}><Icon name="check"/></button></div><div className="routine-summary">{row.target_count&&<span>{t('routineUi.goalSummary',{count:row.target_count,days:row.target_period_days})} · {t('routineUi.goalProgress',{count:row.period_count||0,days:row.target_period_days})}</span>}{row.active&&<span>{['due','overdue'].includes(row.prediction?.status)?t(`routineUi.${row.prediction.status}`):row.prediction?.expected_at?t('routineUi.next',{date:date(row.prediction.expected_at)}):t('routineUi.learning')}</span>}</div></article>)}</div>{!loading&&!visible.length&&!error&&<div className="smart-empty"><Icon name="history"/><strong>{t('routineUi.empty')}</strong><button onClick={()=>setEdit({})}>{t('routineUi.add')}</button></div>}{edit&&<RoutineEditor family={family} userId={userId} routine={edit.id?edit:null} onClose={close} onSaved={async()=>{close();await load();await onChanged?.()}}/>}</section>
}
