import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';

export default function RoutineEditor({family,routine=null,onClose,onSaved}){
 const {t}=useTranslation();const isNew=!routine?.id;
 const [edit,setEdit]=useState(routine?{...routine}:{name:'',suggested_interval_days:7,icon:'history',active:true});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={family:family.id,name:edit.name.trim(),suggested_interval_days:Number(edit.suggested_interval_days)||null,icon:edit.icon||'history',active:edit.active};const saved=await api(isNew?'/routines/':`/routines/${routine.id}/`,{method:isNew?'POST':'PATCH',body:JSON.stringify(payload)});toast(isNew?t('addRoutine'):t('save'),{type:'success'});await onSaved(saved)}catch(err){setError(err.message);toast(err.message||t('saveFailed'),{type:'error'});setBusy(false)}}
 async function remove(){if(isNew)return;const ok=await confirmAction({title:t('deleteRoutineConfirm'),message:edit.name||'',confirmLabel:t('delete'),danger:true});if(!ok)return;setBusy(true);try{await api(`/routines/${routine.id}/`,{method:'DELETE'});toast(t('delete'),{type:'success'});await onSaved(null,{deleted:true})}catch(err){setError(err.message);toast(err.message||t('saveFailed'),{type:'error'});setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><h2>{isNew?t('addRoutine'):t('editRoutine')}</h2><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>{t('name')}<input value={edit.name} onChange={e=>setEdit(v=>({...v,name:e.target.value}))} required autoFocus/></label><label>{t('intervalDays')}<input type="number" min="1" value={edit.suggested_interval_days||''} onChange={e=>setEdit(v=>({...v,suggested_interval_days:e.target.value}))}/></label><label className="toggle-label"><input type="checkbox" checked={edit.active} onChange={e=>setEdit(v=>({...v,active:e.target.checked}))}/>{t('enabled')}</label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!edit.name.trim()}><Icon name="check"/>{busy?t('pleaseWait'):t('save')}</button>{!isNew&&<button type="button" className="ghost-danger destructive-wide" onClick={remove} disabled={busy}><Icon name="delete"/>{t('delete')}</button>}</form></section></div>
}
