import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {confirmAction,toast} from './feedback';

export default function RoutineEditor({family,routine=null,onClose,onSaved}){
 const {t,i18n}=useTranslation();const isNew=!routine?.id;const de=i18n.language.startsWith('de');
 const [edit,setEdit]=useState(routine?{...routine}:{name:'',icon:'history',active:true});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const prediction=routine?.prediction;
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={family:family.id,name:edit.name.trim(),icon:edit.icon||'history',active:edit.active};const saved=await api(isNew?'/routines/':`/routines/${routine.id}/`,{method:isNew?'POST':'PATCH',body:JSON.stringify(payload)});toast(isNew?t('addRoutine'):t('save'),{type:'success'});await onSaved(saved)}catch(err){setError(err.message);toast(err.message||t('saveFailed'),{type:'error'});setBusy(false)}}
 async function remove(){if(isNew)return;const ok=await confirmAction({title:t('deleteRoutineConfirm'),message:edit.name||'',confirmLabel:t('delete'),danger:true});if(!ok)return;setBusy(true);try{await api(`/routines/${routine.id}/`,{method:'DELETE'});toast(t('delete'),{type:'success'});await onSaved(null,{deleted:true})}catch(err){setError(err.message);toast(err.message||t('saveFailed'),{type:'error'});setBusy(false)}}
 const learning=isNew||!prediction||prediction.status==='not_enough_data'||prediction.status==='learning';const learned=!learning&&prediction.expected_interval_days;
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><h2>{isNew?t('addRoutine'):t('editRoutine')}</h2><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>{t('name')}<input value={edit.name} onChange={e=>setEdit(v=>({...v,name:e.target.value}))} required autoFocus/></label><div className="integration-notice" role="status"><Icon name="history"/><div><strong>{learning?(de?'FamilyOS lernt den Rhythmus':'FamilyOS is learning the rhythm'):(de?`Meist etwa alle ${Math.round(prediction.expected_interval_days)} Tage`:`Usually about every ${Math.round(prediction.expected_interval_days)} days`)}</strong><span>{learned?(de?`${Math.round(prediction.confidence*100)} % Sicherheit aus ${prediction.sample_count} Erledigungen`:`${Math.round(prediction.confidence*100)}% confidence from ${prediction.sample_count} completions`):(de?'Kein Intervall nötig – FamilyOS lernt aus euren tatsächlichen Erledigungen.':'No interval needed — FamilyOS learns from your actual completions.')}</span></div></div><label className="toggle-label"><input type="checkbox" checked={edit.active} onChange={e=>setEdit(v=>({...v,active:e.target.checked}))}/>{t('enabled')}</label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!edit.name.trim()}><Icon name="check"/>{busy?t('pleaseWait'):t('save')}</button>{!isNew&&<button type="button" className="ghost-danger destructive-wide" onClick={remove} disabled={busy}><Icon name="delete"/>{t('delete')}</button>}</form></section></div>
}
