import {useState} from 'react';
import {api} from './api';
import {Icon} from './icons';

function localDateTime(value){if(!value)return'';const d=new Date(value);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

export function TaskEditor({task,lists,members,onClose,onSaved}){
 const [v,setV]=useState({title:task.title||'',notes:task.notes||'',task_list:task.task_list||'',due_at:localDateTime(task.due_at),priority:task.priority||'normal',estimate_minutes:task.estimate_minutes||'',assignee:task.assignee||''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,x)=>setV(s=>({...s,[k]:x}));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/tasks/${task.id}/`,{method:'PATCH',body:JSON.stringify({title:v.title.trim(),notes:v.notes,task_list:v.task_list||null,due_at:v.due_at?new Date(v.due_at).toISOString():null,priority:v.priority,estimate_minutes:v.estimate_minutes?Number(v.estimate_minutes):null,assignee:v.assignee||null})});await onSaved()}catch(e){setError(e.message);setBusy(false)}}
 return <div className="sheet-backdrop"><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>Aufgabe</small><h2>{task.title}</h2></div><button className="sheet-close" onClick={onClose}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>Titel<input value={v.title} onChange={e=>set('title',e.target.value)} required autoFocus/></label><label>Liste<select value={v.task_list} onChange={e=>set('task_list',e.target.value)}>{lists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="form-grid"><label>Fällig<input type="datetime-local" value={v.due_at} onChange={e=>set('due_at',e.target.value)}/></label><label>Priorität<select value={v.priority} onChange={e=>set('priority',e.target.value)}><option value="low">Niedrig</option><option value="normal">Normal</option><option value="high">Hoch</option></select></label></div><div className="form-grid"><label>Dauer (Min.)<input type="number" min="1" value={v.estimate_minutes} onChange={e=>set('estimate_minutes',e.target.value)}/></label><label>Zuständig<select value={v.assignee} onChange={e=>set('assignee',e.target.value)}><option value="">Niemand</option>{members.map(m=><option key={m.user} value={m.user}>{m.display_name||m.username}</option>)}</select></label></div><label>Notizen<textarea rows="3" value={v.notes} onChange={e=>set('notes',e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy||!v.title.trim()}><Icon name="check"/>{busy?'Speichere …':'Speichern'}</button></form></section></div>
}

export function ShoppingEditor({item,onClose,onSaved}){
 const [v,setV]=useState({name:item.name||'',quantity:item.quantity||'',category:item.category||'',aisle:item.aisle||'',note:item.note||'',favorite:!!item.favorite});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,x)=>setV(s=>({...s,[k]:x}));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/shopping-items/${item.id}/`,{method:'PATCH',body:JSON.stringify(v)});await onSaved()}catch(e){setError(e.message);setBusy(false)}}
 return <div className="sheet-backdrop"><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>Einkaufsartikel</small><h2>{item.name}</h2></div><button className="sheet-close" onClick={onClose}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>Artikel<input value={v.name} onChange={e=>set('name',e.target.value)} required autoFocus/></label><div className="form-grid"><label>Menge<input value={v.quantity} onChange={e=>set('quantity',e.target.value)} placeholder="2 × 500 g"/></label><label>Kategorie<input value={v.category} onChange={e=>set('category',e.target.value)} placeholder="Obst & Gemüse"/></label></div><label>Regal / Bereich<input value={v.aisle} onChange={e=>set('aisle',e.target.value)} placeholder="z. B. Kühlung"/></label><label>Notiz<textarea rows="2" value={v.note} onChange={e=>set('note',e.target.value)}/></label><label className="toggle-label"><input type="checkbox" checked={v.favorite} onChange={e=>set('favorite',e.target.checked)}/><span><Icon name="favorite"/> Favorit – schnell wiederfinden</span></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy||!v.name.trim()}><Icon name="check"/>{busy?'Speichere …':'Speichern'}</button></form></section></div>
}
