import {useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Icon} from './icons';

const unwrap=x=>x?.results||x||[];
const fmt=d=>d?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'';

function SmartInput({family,type,placeholder,onCreate}){
  const [q,setQ]=useState('');const [suggestions,setSuggestions]=useState([]);const [busy,setBusy]=useState(false);const [selected,setSelected]=useState(null);
  useEffect(()=>{if(!family||q.trim().length<1){setSuggestions([]);return}const id=setTimeout(()=>api(`/${type==='task'?'tasks':'shopping-items'}/suggestions/?family=${family.id}&q=${encodeURIComponent(q)}`).then(setSuggestions).catch(()=>setSuggestions([])),160);return()=>clearTimeout(id)},[q,family,type]);
  async function submit(e){e.preventDefault();if(!q.trim()||busy)return;setBusy(true);try{await onCreate({name:q.trim(),suggestion:selected});setQ('');setSelected(null);setSuggestions([])}finally{setBusy(false)}}
  function choose(s){setQ(s.name);setSelected(s);setSuggestions([])}
  return <div className="smart-input-wrap"><form className="smart-input" onSubmit={submit}><Icon name="search"/><input value={q} onChange={e=>{setQ(e.target.value);setSelected(null)}} placeholder={placeholder}/>{selected&&<span className="smart-memory"><Icon name="robot"/> gemerkt</span>}<button disabled={!q.trim()||busy}><Icon name="plus"/> Hinzufügen</button></form>{suggestions.length>0&&<div className="smart-suggestions">{suggestions.map(s=><button key={s.name} onClick={()=>choose(s)}><span className="suggest-icon"><Icon name={type==='task'?'tasks':'shopping'}/></span><span><strong>{s.name}</strong><small>{type==='task'?[s.priority,s.estimate_minutes?`${s.estimate_minutes} min`:null,s.notes].filter(Boolean).join(' · '):[s.quantity,s.category,s.aisle].filter(Boolean).join(' · ')}</small></span><em><Icon name="history"/> {s.count}×</em></button>)}</div>}</div>
}

export function SmartTasks({family,onChanged}){
  const [lists,setLists]=useState([]);const [tasks,setTasks]=useState([]);const [active,setActive]=useState('all');const [showDone,setShowDone]=useState(false);const [newList,setNewList]=useState('');
  const load=async()=>{if(!family)return;const [l,t]=await Promise.all([api('/task-lists/'),api('/tasks/')]);setLists(unwrap(l).filter(x=>x.family===family.id));setTasks(unwrap(t).filter(x=>x.family===family.id))};useEffect(()=>{load()},[family?.id]);
  const filtered=useMemo(()=>tasks.filter(x=>(active==='all'||x.task_list===active)&&(showDone||!x.completed_at)),[tasks,active,showDone]);
  const open=tasks.filter(x=>!x.completed_at);const dueToday=open.filter(x=>x.due_at&&new Date(x.due_at).toDateString()===new Date().toDateString()).length;const high=open.filter(x=>x.priority==='high').length;
  async function create({name,suggestion}){let list=active!=='all'?active:(lists[0]?.id||null);await api('/tasks/',{method:'POST',body:JSON.stringify({family:family.id,task_list:list,title:name,notes:suggestion?.notes||'',priority:suggestion?.priority||'normal',estimate_minutes:suggestion?.estimate_minutes||null})});await load();onChanged?.()}
  async function toggle(x){await api(`/tasks/${x.id}/toggle/`,{method:'POST'});await load();onChanged?.()}
  async function remove(x){await api(`/tasks/${x.id}/`,{method:'DELETE'});await load();onChanged?.()}
  async function addList(e){e.preventDefault();if(!newList.trim())return;await api('/task-lists/',{method:'POST',body:JSON.stringify({family:family.id,name:newList.trim(),icon:'list-check'})});setNewList('');await load()}
  return <div className="smart-page"><div className="smart-head"><div><small>Familienaufgaben</small><h1>Aufgaben</h1></div><div className="metric-row"><span><b>{open.length}</b> offen</span><span className={dueToday?'warn':''}><b>{dueToday}</b> heute</span><span className={high?'danger':''}><b>{high}</b> wichtig</span></div></div><SmartInput family={family} type="task" placeholder="Aufgabe suchen oder hinzufügen …" onCreate={create}/><div className="list-tabs"><button className={active==='all'?'active':''} onClick={()=>setActive('all')}><Icon name="lists"/> Alle <b>{open.length}</b></button>{lists.map(l=><button key={l.id} className={active===l.id?'active':''} onClick={()=>setActive(l.id)}><Icon name={l.icon==='house'?'home':'tasks'}/>{l.name}<b>{l.open_count}</b></button>)}<form onSubmit={addList} className="inline-list-add"><input value={newList} onChange={e=>setNewList(e.target.value)} placeholder="Neue Liste"/><button><Icon name="plus"/></button></form></div><div className="smart-toolbar"><button onClick={()=>setShowDone(!showDone)} className={showDone?'active':''}><Icon name="doneAll"/> Erledigte {showDone?'ausblenden':'anzeigen'}</button></div><section className="smart-card-list">{filtered.length?filtered.map(x=><article key={x.id} className={`smart-row ${x.completed_at?'done':''}`}><button className={`smart-check ${x.completed_at?'checked':''}`} onClick={()=>toggle(x)}><Icon name="check"/></button><div className="smart-row-main"><div className="smart-title"><strong>{x.title}</strong>{x.priority==='high'&&<span className="priority-high"><Icon name="priority"/> wichtig</span>}</div><div className="smart-meta">{x.list_name&&<span><Icon name="lists"/>{x.list_name}</span>}{x.due_at&&<span><Icon name="clock"/>{fmt(x.due_at)}</span>}{x.assignee_name&&<span><Icon name="user"/>{x.assignee_name}</span>}{x.estimate_minutes&&<span><Icon name="progress"/>{x.estimate_minutes} min</span>}</div>{x.notes&&<p>{x.notes}</p>}</div><button className="row-action danger-text" onClick={()=>remove(x)} title="Löschen"><Icon name="delete"/></button></article>):<div className="smart-empty"><Icon name="doneAll" size={34}/><strong>Alles erledigt</strong><span>Tippe oben, um eine Aufgabe hinzuzufügen.</span></div>}</section></div>
}

export function SmartShopping({family,onChanged}){
  const [lists,setLists]=useState([]);const [active,setActive]=useState(null);const [newList,setNewList]=useState('');
  const load=async()=>{if(!family)return;const l=unwrap(await api('/shopping-lists/')).filter(x=>x.family===family.id&&!x.archived);setLists(l);if(!active&&l[0])setActive(l[0].id)};useEffect(()=>{load()},[family?.id]);
  const list=lists.find(x=>x.id===active)||lists[0];const items=list?.items||[];const open=items.filter(x=>!x.checked);const checked=items.filter(x=>x.checked);
  const groups=useMemo(()=>{const out={};open.forEach(x=>{const k=x.category||'Sonstiges';(out[k]||(out[k]=[])).push(x)});return out},[open]);
  async function create({name,suggestion}){let target=list;if(!target){target=await api('/shopping-lists/',{method:'POST',body:JSON.stringify({family:family.id,name:'Einkauf',icon:'cart-shopping'})})}await api('/shopping-items/',{method:'POST',body:JSON.stringify({shopping_list:target.id,name,quantity:suggestion?.quantity||'',category:suggestion?.category||'',aisle:suggestion?.aisle||'',note:suggestion?.note||''})});await load();onChanged?.()}
  async function toggle(x){await api(`/shopping-items/${x.id}/toggle/`,{method:'POST'});await load();onChanged?.()}
  async function remove(x){await api(`/shopping-items/${x.id}/`,{method:'DELETE'});await load();onChanged?.()}
  async function addList(e){e.preventDefault();if(!newList.trim())return;const l=await api('/shopping-lists/',{method:'POST',body:JSON.stringify({family:family.id,name:newList.trim(),icon:'cart-shopping'})});setNewList('');await load();setActive(l.id)}
  return <div className="smart-page"><div className="smart-head"><div><small>Gemeinsam einkaufen</small><h1>Einkauf</h1></div><div className="metric-row"><span><b>{open.length}</b> offen</span><span><b>{checked.length}</b> erledigt</span>{list?.store&&<span><Icon name="store"/>{list.store}</span>}</div></div><SmartInput family={family} type="shopping" placeholder="Artikel suchen oder hinzufügen …" onCreate={create}/><div className="list-tabs">{lists.map(l=><button key={l.id} className={(list?.id===l.id)?'active':''} onClick={()=>setActive(l.id)}><Icon name="shopping"/>{l.name}<b>{l.open_count}</b></button>)}<form onSubmit={addList} className="inline-list-add"><input value={newList} onChange={e=>setNewList(e.target.value)} placeholder="Neue Liste"/><button><Icon name="plus"/></button></form></div><section className="shopping-groups">{Object.entries(groups).map(([category,rows])=><div className="shopping-group" key={category}><h3>{category}<span>{rows.length}</span></h3>{rows.map(x=><article className="smart-row" key={x.id}><button className="smart-check" onClick={()=>toggle(x)}><Icon name="check"/></button><div className="smart-row-main"><strong>{x.name}</strong><div className="smart-meta">{x.quantity&&<span>{x.quantity}</span>}{x.aisle&&<span><Icon name="location"/>{x.aisle}</span>}{x.added_by_name&&<span><Icon name="user"/>{x.added_by_name}</span>}</div>{x.note&&<p>{x.note}</p>}</div>{x.favorite&&<Icon name="favorite" className="favorite"/>}<button className="row-action danger-text" onClick={()=>remove(x)}><Icon name="delete"/></button></article>)}</div>)}{!open.length&&<div className="smart-empty"><Icon name="doneAll" size={34}/><strong>Liste leer</strong><span>Fam-uh-le merkt sich frühere Artikel und schlägt sie beim Tippen vor.</span></div>}</section>{checked.length>0&&<details className="done-items"><summary><Icon name="doneAll"/> {checked.length} erledigt</summary>{checked.map(x=><button key={x.id} onClick={()=>toggle(x)}><Icon name="check"/><span>{x.name}</span><small>{x.quantity}</small></button>)}</details>}</div>
}
