import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {useDirtyForm} from './dirty-state';

function localDateTime(value){if(!value)return'';const d=new Date(value);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

export function TaskEditor({task=null,family,lists=[],members=[],defaultListId='',onClose,onSaved,onDelete}){
 const {t}=useTranslation();const isNew=!task?.id;const initial=task||{};
 const initialValues={title:initial.title||'',notes:initial.notes||'',task_list:initial.task_list||defaultListId||lists[0]?.id||'',due_at:localDateTime(initial.due_at),priority:initial.priority||'normal',estimate_minutes:initial.estimate_minutes||'',assignee:initial.assignee||''};
 const [v,setV]=useState(initialValues);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,x)=>setV(s=>({...s,[k]:x}));
 useDirtyForm(JSON.stringify(v)!==JSON.stringify(initialValues));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={title:v.title.trim(),notes:v.notes,task_list:v.task_list||null,due_at:v.due_at?new Date(v.due_at).toISOString():null,priority:v.priority,estimate_minutes:v.estimate_minutes?Number(v.estimate_minutes):null,assignee:v.assignee||null};if(isNew)payload.family=family?.id;const saved=await api(isNew?'/tasks/':`/tasks/${task.id}/`,{method:isNew?'POST':'PATCH',body:JSON.stringify(payload)});await onSaved(saved)}catch(e){setError(e.message);setBusy(false)}}
 async function remove(){if(!onDelete)return;setBusy(true);try{await onDelete()}finally{setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('taskTitle')}</small><h2>{isNew?t('addTask'):task.title}</h2></div><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}><label>{t('title')}<input value={v.title} onChange={e=>set('title',e.target.value)} required autoFocus/></label>{lists.length>0&&<label>{t('taskList')}<select value={v.task_list} onChange={e=>set('task_list',e.target.value)}><option value="">{t('all')}</option>{lists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="form-grid"><label>{t('due')}<input type="datetime-local" value={v.due_at} onChange={e=>set('due_at',e.target.value)}/></label><label>{t('priority')}<select value={v.priority} onChange={e=>set('priority',e.target.value)}><option value="low">{t('low')}</option><option value="normal">{t('normal')}</option><option value="high">{t('high')}</option></select></label></div><details className="editor-details"><summary><Icon name="settings"/> {t('moreDetails')}</summary><div className="editor-details-body"><div className="form-grid"><label>{t('durationMinutes')}<input type="number" min="1" value={v.estimate_minutes} onChange={e=>set('estimate_minutes',e.target.value)}/></label><label>{t('assignee')}<select value={v.assignee} onChange={e=>set('assignee',e.target.value)}><option value="">{t('nobody')}</option>{members.map(m=><option key={m.user} value={m.user}>{m.display_name||m.username}</option>)}</select></label></div><label>{t('notes')}<textarea rows="3" value={v.notes} onChange={e=>set('notes',e.target.value)}/></label></div></details>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!v.title.trim()}><Icon name="check"/>{busy?t('saving'):t('save')}</button>{!isNew&&onDelete&&<button type="button" className="ghost-danger destructive-wide" onClick={remove} disabled={busy}><Icon name="delete"/> {t('deleteTask')}</button>}</form></section></div>
}

export function ShoppingEditor({item=null,shoppingList=null,lists=[],onClose,onSaved,onDelete,onSubmit}){
 const {t}=useTranslation();const isNew=!item?.id;const initial=item||{};const defaultList=shoppingList?.id||shoppingList||initial.shopping_list||lists[0]?.id||'';
 const initialValues={shopping_list:defaultList,name:initial.name||'',quantity:initial.quantity||'',category:initial.category||'',aisle:initial.aisle||'',note:initial.note||'',favorite:!!initial.favorite};
 const [v,setV]=useState(initialValues);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const set=(k,x)=>setV(s=>({...s,[k]:x}));
 useDirtyForm(JSON.stringify(v)!==JSON.stringify(initialValues));
 async function save(e){e.preventDefault();if(isNew&&!v.shopping_list)return;setBusy(true);setError('');try{const payload={name:v.name.trim(),quantity:v.quantity,category:v.category,aisle:v.aisle,note:v.note,favorite:v.favorite};if(isNew)payload.shopping_list=v.shopping_list;const saved=onSubmit?await onSubmit(payload,{isNew,item}):await api(isNew?'/shopping-items/':`/shopping-items/${item.id}/`,{method:isNew?'POST':'PATCH',body:JSON.stringify(payload)});await onSaved(saved)}catch(e){setError(e.message);setBusy(false)}}
 async function remove(){if(!onDelete)return;setBusy(true);try{await onDelete()}finally{setBusy(false)}}
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="quick-sheet" role="dialog" aria-modal="true"><div className="sheet-handle"/><div className="sheet-head"><div><small>{t('shoppingItem')}</small><h2>{isNew?t('addAction'):item.name}</h2></div><button className="sheet-close" onClick={onClose} disabled={busy} aria-label={t('close')}><Icon name="close"/></button></div><form className="quick-form" onSubmit={save}>{isNew&&lists.length>1&&<label>{t('shoppingList')}<select value={v.shopping_list} onChange={e=>set('shopping_list',e.target.value)} required><option value="">—</option>{lists.map(list=><option value={list.id} key={list.id}>{list.name}</option>)}</select></label>}<label>{t('item')}<input value={v.name} onChange={e=>set('name',e.target.value)} required autoFocus/></label><div className="form-grid"><label>{t('quantity')}<input value={v.quantity} onChange={e=>set('quantity',e.target.value)} placeholder="2 × 500 g"/></label><label>{t('category')}<input value={v.category} onChange={e=>set('category',e.target.value)} placeholder={t('categoryPlaceholder')}/></label></div><label>{t('aisle')}<input value={v.aisle} onChange={e=>set('aisle',e.target.value)} placeholder={t('aislePlaceholder')}/></label><label>{t('note')}<textarea rows="2" value={v.note} onChange={e=>set('note',e.target.value)}/></label><label className="toggle-label"><input type="checkbox" checked={v.favorite} onChange={e=>set('favorite',e.target.checked)}/><span><Icon name="favorite"/> {t('favoriteHint')}</span></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!v.name.trim()||(isNew&&!v.shopping_list)}><Icon name="check"/>{busy?t('saving'):t('save')}</button>{!isNew&&onDelete&&<button type="button" className="ghost-danger destructive-wide" onClick={remove} disabled={busy}><Icon name="delete"/> {t('deleteShoppingItem')}</button>}</form></section></div>
}
