import {useEffect,useState} from 'react';
import TodayLayout from './TodayLayout';
import './birthday-i18n';
import './birthdays.css';
import './loyalty-i18n';
import i18n from './i18n';
import './calendar-i18n';
import {api} from './api';
import {formatDateTime} from './locale';
import {Icon} from './icons';
import OnboardingCard from './OnboardingCard';
import {requestCreate} from './create-request';
import {weatherLabel} from './weather-ui';
import {isWasteEvent,wasteClass,wasteKind,wasteKindLabel} from './waste-ui';
import './onboarding.css';

const unwrap=x=>x?.results||x||[];
const isWarning=e=>e?.type?.includes('warning');
const isCurrentWeather=e=>e?.type==='weather.current';
const isToday=date=>date&&new Date(date).toDateString()===new Date().toDateString();
const isOverdue=task=>task?.due_at&&!task.completed_at&&new Date(task.due_at)<new Date()&&!isToday(task.due_at);
const timeValue=e=>e?.starts_at?new Date(e.starts_at).getTime():Number.MAX_SAFE_INTEGER;
function isUpcomingTodayEvent(event){if(!event?.starts_at)return true;if(isWasteEvent(event)){const floor=new Date();floor.setHours(0,0,0,0);return new Date(event.starts_at).getTime()>=floor.getTime()}return new Date(event.starts_at).getTime()>=Date.now()-3600000}
function formatEventDate(value,t,language){if(!value)return '';const date=new Date(value);if(isToday(value))return `${t('today')} · ${formatDateTime(language,date,{timeStyle:'short'})}`;return formatDateTime(language,date,{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function formatWasteDate(value,t,language){if(!value)return '';const target=new Date(value);const today=new Date();today.setHours(0,0,0,0);target.setHours(0,0,0,0);const days=Math.round((target.getTime()-today.getTime())/86400000);if(days===0)return t('today');return new Intl.RelativeTimeFormat(language.startsWith('de')?'de':'en',{numeric:'auto'}).format(days,'day')}
function taskDueLabel(task,t,language){if(!task.due_at)return '';const date=new Date(task.due_at);if(isOverdue(task))return `${t('due')} · ${formatDateTime(language,date,{dateStyle:'short'})}`;if(isToday(task.due_at))return `${t('today')} ${formatDateTime(language,date,{timeStyle:'short'})}`;return formatDateTime(language,date,{dateStyle:'medium'})}
function currentWeatherMeta(event,language){const payload=event?.payload||{};const de=language?.startsWith('de');const parts=[];if(payload.weather_code!==null&&payload.weather_code!==undefined)parts.push(weatherLabel(Number(payload.weather_code),language));if(payload.apparent_temperature!==null&&payload.apparent_temperature!==undefined)parts.push(`${de?'Gefühlt':'Feels like'} ${payload.apparent_temperature} °C`);if(payload.wind_speed!==null&&payload.wind_speed!==undefined)parts.push(`Wind ${payload.wind_speed} km/h`);if(payload.provider)parts.push(payload.provider);return parts.join(' · ')}
function routineIsDue(routine){if(routine.active===false)return false;const prediction=routine.prediction;if(!prediction||['not_enough_data','learning'].includes(prediction.status))return false;if(['due','overdue'].includes(prediction.status))return true;if(prediction.status!=='upcoming'||!prediction.preparation_start)return false;return new Date(prediction.preparation_start).getTime()<=Date.now()}
function EventIcon({event}){const waste=isWasteEvent(event);const name=isWarning(event)?'warning':event.type?.includes('weather')?'weather':event.type?.includes('transit')?'transit':event.type?.includes('school')?'school':waste?'waste':'calendar';return <span className={`today-event-icon ${isWarning(event)?'warning':''} ${waste?wasteClass(event):''}`}><Icon name={name}/></span>}
function TaskRow({task,onTask,t,language}){const due=taskDueLabel(task,t,language);return <div className={`today-task-row ${isOverdue(task)?'overdue':''}`}><button className="today-check" onClick={()=>onTask(task)} aria-label={`${task.title} · ${t('processed')}`}><Icon name="check"/></button><div className="grow"><strong>{task.title}</strong><div className="today-meta">{due&&<span className={isOverdue(task)?'danger-text':''}><Icon name="clock"/>{due}</span>}{task.assignee_name&&<span><span className="today-avatar" aria-hidden="true">{task.assignee_name.slice(0,1).toUpperCase()}</span>{task.assignee_name}</span>}</div></div>{task.priority==='high'&&<span className="today-priority"><Icon name="priority"/> {t('high')}</span>}</div>}
function zonedToday(timeZone){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timeZone||'UTC',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const read=type=>Number(parts.find(part=>part.type===type)?.value||0);return {year:read('year'),month:read('month'),day:read('day'),hour:read('hour')}}
function weekFor(timeZone){const today=zonedToday(timeZone);const date=new Date(Date.UTC(today.year,today.month-1,today.day,12));const mondayOffset=(date.getUTCDay()+6)%7;const monday=new Date(date);monday.setUTCDate(date.getUTCDate()-mondayOffset);return Array.from({length:7},(_,index)=>{const value=new Date(monday);value.setUTCDate(monday.getUTCDate()+index);return {value,current:value.getUTCFullYear()===today.year&&value.getUTCMonth()===today.month-1&&value.getUTCDate()===today.day}})}
function greeting(family,language){const de=language.startsWith('de');const hour=zonedToday(family?.timezone).hour;const part=hour<12?(de?'Guten Morgen':'Good morning'):hour<18?(de?'Guten Tag':'Good afternoon'):(de?'Guten Abend':'Good evening');return `${part}, ${family?.name||(de?'Familie':'family')}!`}
function WeekStrip({family,language}){const locale=language.startsWith('de')?'de-DE':'en-US';const fmt=new Intl.DateTimeFormat(locale,{timeZone:'UTC',weekday:'short',day:'numeric'});return <ol className="today-week" aria-label={language.startsWith('de')?'Diese Woche':'This week'}>{weekFor(family?.timezone).map(({value,current})=>{const parts=fmt.formatToParts(value);const weekday=parts.find(part=>part.type==='weekday')?.value?.replace('.','')||'';const day=parts.find(part=>part.type==='day')?.value||'';return <li key={value.toISOString()} aria-current={current?'date':undefined} className={current?'current':''}><span>{weekday}</span><strong>{day}</strong></li>})}</ol>}
function relativeInboxTime(value,language){if(!value)return '';const delta=new Date(value).getTime()-Date.now();const abs=Math.abs(delta);const rtf=new Intl.RelativeTimeFormat(language.startsWith('de')?'de':'en',{numeric:'auto'});if(abs<3600000)return rtf.format(Math.round(delta/60000),'minute');if(abs<86400000)return rtf.format(Math.round(delta/3600000),'hour');return rtf.format(Math.round(delta/86400000),'day')}

export default function TodayHome({data,family,t,onTask,open}){
 const language=i18n.language;const de=language.startsWith('de');const openTasks=(data.tasks||[]).filter(x=>!x.completed_at);const shopping=(data.shopping_lists||[]).flatMap(x=>x.items||[]).filter(x=>!x.checked);const contract=data.weather?.current;const inboxRows=(data.inbox||[]).filter(row=>!row.withdrawn_at).sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).slice(0,4);const inboxCount=Number(data.inbox_count||inboxRows.filter(row=>row.unread||row.status==='new').length||0);
 const [loyaltyCards,setLoyaltyCards]=useState([]);
 useEffect(()=>{let active=true;setLoyaltyCards([]);api(`/loyalty-cards/sync/?family=${encodeURIComponent(family.id)}`).then(response=>{if(!active)return;const rows=[...unwrap(response)].sort((a,b)=>Number(Boolean(b.favorite))-Number(Boolean(a.favorite))||String(a.name||'').localeCompare(String(b.name||''),language));setLoyaltyCards(rows.slice(0,4))}).catch(()=>{if(active)setLoyaltyCards([])});return()=>{active=false}},[family.id,language]);
 const currentWeather=contract?{type:'weather.current',title:contract.temperature===null||contract.temperature===undefined?t('weather'):`${contract.temperature} °C`,starts_at:contract.observed_at,payload:{provider:'Open-Meteo',...contract}}:(data.events||[]).find(isCurrentWeather);
 const events=[...(data.events||[])].filter(e=>!isCurrentWeather(e)&&isUpcomingTodayEvent(e)).sort((a,b)=>timeValue(a)-timeValue(b));const warnings=events.filter(isWarning).slice(0,2);const wasteEvents=events.filter(isWasteEvent).slice(0,2);const urgentTasks=openTasks.filter(x=>isOverdue(x)||x.priority==='high').slice(0,4);const urgentCount=warnings.length+urgentTasks.length;const nextEvent=events.find(e=>!isWarning(e)&&!isWasteEvent(e));const contextEvent=warnings[0]||wasteEvents[0]||nextEvent;const todayTasks=[...openTasks].sort((a,b)=>Number(isOverdue(b))-Number(isOverdue(a))||Number(b.priority==='high')-Number(a.priority==='high')||timeValue({starts_at:a.due_at})-timeValue({starts_at:b.due_at})).slice(0,5);const routineRows=(data.routines||[]).filter(r=>r.active!==false).sort((a,b)=>new Date(b.last_done_at||0)-new Date(a.last_done_at||0)).slice(0,4);const birthdayRows=(data.birthdays||[]).slice(0,2);
 const contextLabel=contextEvent?(isWarning(contextEvent)?(de?'Warnung':'Warning'):isWasteEvent(contextEvent)?(de?'Nächste Abholung':'Next collection'):t('nextUp')):t('nextUp');
 const widgets={
  priority:(urgentCount>0&&<section className="today-section today-important"><div className="today-section-head"><div><small>{t('priority').toUpperCase()}</small><h2>{de?'Wichtig heute':'Important today'}</h2></div><span>{urgentCount}</span></div><div className="today-important-grid">{warnings.map(event=><button key={`event-${event.id}`} className="today-important-card warning" onClick={()=>open('calendar')}><EventIcon event={event}/><div><small>{event.type==='public.warning'?t('publicWarning'):t('weatherWarning')}</small><strong>{event.title}</strong><span>{formatEventDate(event.starts_at,t,language)}</span></div><Icon name="next"/></button>)}{urgentTasks.map(task=><div key={`task-${task.id}`} className="today-important-card task"><span className="today-event-icon danger"><Icon name="priority"/></span><div><small>{isOverdue(task)?t('due').toUpperCase():t('priority').toUpperCase()}</small><strong>{task.title}</strong><span>{[taskDueLabel(task,t,language),task.assignee_name].filter(Boolean).join(' · ')}</span></div><button className="today-check" onClick={()=>onTask(task)} aria-label={`${task.title} · ${t('processed')}`}><Icon name="check"/></button></div>)}</div></section>),
  next:(<section className="today-section today-context-card" data-testid="today-context"><div className="today-section-head"><div><small>{de?'Heute':'Today'}</small><h2>{contextLabel}</h2></div><button className="today-add-link" onClick={()=>requestCreate('event',{source:'todayContext'})}><Icon name="plus"/> {de?'Termin':'Event'}</button></div>{contextEvent?<button className="today-next-event" onClick={()=>open('calendar')}><EventIcon event={contextEvent}/><div className="grow"><strong>{contextEvent.title}</strong><span>{isWasteEvent(contextEvent)?formatWasteDate(contextEvent.starts_at,t,language):formatEventDate(contextEvent.starts_at,t,language)}{contextEvent.payload?.location?` · ${contextEvent.payload.location}`:''}</span><small>{isWasteEvent(contextEvent)?wasteKindLabel(wasteKind(contextEvent),language):(contextEvent.payload?.provider||contextEvent.type)}</small></div><Icon name="next"/></button>:<button className="today-calm today-context-empty" onClick={()=>requestCreate('event',{source:'todayContextEmpty'})}><Icon name="calendar"/><span>{de?'Termin hinzufügen':'Add an event'}</span></button>}</section>),
  weather:(currentWeather&&<section className="today-section today-weather-card" data-testid="current-weather"><div className="today-section-head"><h2>{t('weather')}</h2><button className="today-link" onClick={()=>open('weather')}>{de?'7 Tage':'7 days'} <Icon name="next"/></button></div><button className="today-weather-summary" onClick={()=>open('weather')}><span className="today-weather-icon"><Icon name="weather"/></span><strong>{currentWeather.title}</strong><span>{currentWeatherMeta(currentWeather,language)}</span></button></section>),
  tasks:(<section className="today-section today-module"><div className="today-section-head"><div><h2>{t('tasks')}</h2><small>{openTasks.length} {t('open')}</small></div><button className="today-link" onClick={()=>open('tasks')}>{t('all')} <Icon name="next"/></button></div><div className="today-panel">{todayTasks.length?todayTasks.map(task=><TaskRow task={task} onTask={onTask} t={t} language={language} key={task.id}/>):<div className="today-calm"><Icon name="doneAll"/><strong>{t('onboarding.emptyTaskTitle')}</strong><span>{t('onboarding.emptyTaskHint')}</span></div>}<button className="today-module-add" onClick={()=>requestCreate('task',{source:'todayModule'})}><Icon name="plus"/> {de?'Aufgabe hinzufügen':'Add task'}</button></div></section>),
  shopping:(<section className="today-section today-module"><div className="today-section-head"><div><h2>{de?'Einkaufsliste':t('shopping')}</h2><small>{shopping.length} · {t('shoppingItems')}</small></div><button className="today-link" onClick={()=>open('shopping')}>{t('all')} <Icon name="next"/></button></div><div className="today-panel today-shopping-list">{shopping.length?shopping.slice(0,5).map(item=><button className="today-shopping-row" key={item.id} onClick={()=>open('shopping')}><span className="today-shopping-check"><Icon name="shopping"/></span><span className="grow"><strong>{item.name}</strong><small>{[item.quantity,item.category].filter(Boolean).join(' · ')}</small></span><Icon name="next"/></button>):<div className="today-calm"><Icon name="shopping"/><strong>{t('onboarding.emptyShoppingTitle')}</strong><span>{t('onboarding.emptyShoppingHint')}</span></div>}<button className="today-module-add" onClick={()=>requestCreate('shoppingItem',{source:'todayModule'})}><Icon name="plus"/> {de?'Artikel hinzufügen':'Add item'}</button></div></section>),
  routines:(<section className="today-section today-secondary" data-testid="today-routines"><div className="today-section-head"><div><h2>{de?'Zuletzt gemacht':'Recently done'}</h2><small>{t('routineUi.title')}</small></div><button className="today-link" onClick={()=>open('routines')}>{t('all')} <Icon name="next"/></button></div>{routineRows.length?<div className="today-routines">{routineRows.map(r=>{const due=routineIsDue(r);const days=r.last_done_at?Math.max(0,Math.floor((Date.now()-new Date(r.last_done_at).getTime())/86400000)):null;return <button key={r.id} onClick={()=>open('routines')}><span><Icon name="history"/></span><strong>{r.name}</strong><small>{r.last_done_at?(days===0?t('todayLower'):t('daysAgo',{count:days})):(due?t('dueSoon'):t('never'))}</small></button>})}</div>:<button className="today-calm today-routine-empty" onClick={()=>open('routines')}><Icon name="history"/><strong>{t('routineUi.title')}</strong><span>{t('noData')}</span></button>}</section>),
  waste:(<section className="today-section" data-testid="next-waste"><div className="today-section-head"><h2>{t('calendarUi.nextWaste')}</h2><button className="today-link" onClick={()=>open('calendar')}>{t('calendar')} <Icon name="next"/></button></div>{wasteEvents.length?<div className="today-waste-list">{wasteEvents.map(event=><button key={`waste-${event.id}`} className="today-next-event today-waste-event" onClick={()=>open('calendar')}><EventIcon event={event}/><div className="grow"><strong>{event.title}</strong><span>{formatWasteDate(event.starts_at,t,language)}</span><small>{wasteKindLabel(wasteKind(event),language)}</small></div><Icon name="next"/></button>)}</div>:<button className="today-calm today-waste-empty" onClick={()=>open('calendar')}><Icon name="waste"/><span>{de?'Keine Abholung geplant':'No collection scheduled'}</span></button>}</section>),
  inbox:(<section className="today-section today-inbox" data-testid="today-inbox"><div className="today-section-head"><div><h2>{de?'Familien-Inbox':'Family inbox'}</h2><small>{inboxCount?`${inboxCount} ${de?'ungelesen':'unread'}`:(de?'Alles gelesen':'All caught up')}</small></div><button className="today-link" onClick={()=>open('inbox')}>{t('all')} <Icon name="next"/></button></div>{inboxRows.length?<div className="today-inbox-list">{inboxRows.map(item=>{const unread=item.unread||item.status==='new';return <button key={item.id} onClick={()=>window.location.assign(`/?page=inbox&message=${encodeURIComponent(item.id)}`)}><span className={`today-inbox-icon ${unread?'unread':''}`}><Icon name={item.source==='manual_message'?'members':'inbox'}/></span><span className="grow"><strong>{item.title||item.body||item.source}</strong><small>{[item.created_by_name,relativeInboxTime(item.created_at,language)].filter(Boolean).join(' · ')}</small></span>{unread&&<i aria-label={de?'Ungelesen':'Unread'}/>}<Icon name="next"/></button>})}</div>:<button className="today-calm today-inbox-empty" onClick={()=>open('inbox')}><Icon name="inbox"/><strong>{de?'Keine neuen Mitteilungen':'No new messages'}</strong><span>{de?'Posteingang öffnen':'Open inbox'}</span></button>}</section>),
  birthdays:(birthdayRows.length>0&&<div>{birthdayRows.map(row=><div className="today-birthday" key={row.key}><a href={`/?page=birthdays&birthday=${encodeURIComponent(row.key)}`}><Icon name="calendar"/><span><strong>{t(row.days_until===0?'birthdayUi.today':'birthdayUi.inDays',{name:row.name,count:row.days_until})}</strong>{row.can_plan&&row.days_until>0&&<small> · {t(['ready','given'].includes(row.gift_status)?'birthdayUi.ready':'birthdayUi.prepare')}</small>}</span><Icon name="next"/></a></div>)}</div>),
  notes:(<section className="today-section"><button className="today-notes-link" onClick={()=>open('notes')}><Icon name="lists"/><strong>{de?'Notizzettel':'Notes'}</strong><Icon name="next"/></button></section>),
  loyalty:(loyaltyCards.length>0&&<section className="today-section today-secondary" data-testid="today-loyalty"><div className="today-section-head"><div><h2>{t('loyaltyUi.title')}</h2><small>{de?'Favoriten & geteilte Karten':'Favorites & shared cards'}</small></div><button className="today-link" onClick={()=>open('loyalty')}>{t('all')} <Icon name="next"/></button></div><div className="today-routines">{loyaltyCards.map(card=><button key={card.id} onClick={()=>window.location.assign(`/?page=loyalty&card=${encodeURIComponent(card.id)}`)} aria-label={`${card.name} · ${t('loyaltyUi.title')}`}><span><Icon name={card.favorite?'favorite':'store'}/></span><strong>{card.name}</strong><small>{card.holder_display||card.holder_name||(card.favorite?(de?'Favorit':'Favorite'):'')}</small></button>)}</div></section>)
 };
 return <TodayLayout family={family} header={<header className="today-hero"><div className="today-greeting"><p>{formatDateTime(language,new Date(),{weekday:'long',day:'numeric',month:'long'})}</p><h1>{greeting(family,language)}</h1><span>{urgentCount?`${urgentCount} · ${de?'heute wichtig':'important today'}`:t('allDone')}</span></div><WeekStrip family={family} language={language}/></header>} onboarding={<OnboardingCard family={family} data={data} open={open}/>} widgets={widgets}/>;
}