import {cloneElement,isValidElement,useEffect,useState,useRef} from 'react';
import {api} from './api';
import i18n from './i18n';
import {WeekCompassWidget,PinboardTodayWidget} from './TodayContextWidgets';
import './today-layout.css';

const legacyIds=['weather','priority','waste','next','tasks','shopping','routines','birthdays','notes'];
const prePinboardIds=[...legacyIds,'loyalty','inbox'];
const ids=[...prePinboardIds,'trip','week','pinboard'];
const squareIds=new Set(['trip','next','weather','routines','waste','inbox','birthdays','notes','loyalty']);
const weekSettings=()=>({events:true,waste:true,holidays:true,special:true});
const defaultOrder=['week','priority','trip','next','pinboard','weather','tasks','shopping','routines','waste','inbox','birthdays','notes','loyalty'];
const defaults=()=>defaultOrder.map(id=>({id,visible:true,size:'full',...(id==='week'?{settings:weekSettings()}:{})}));
function cleanWidget(widget){const row={...widget};if(row.id==='week')row.settings={...weekSettings(),...(row.settings||{})};else delete row.settings;return row}
function normalizeLayout(value){
 if(value?.version!==1||!Number.isInteger(value.revision)||value.revision<0||!Array.isArray(value.widgets))return null;
 const widgets=[];const seen=new Set();
 for(const raw of value.widgets){
  if(!raw||typeof raw!=='object')return null;
  const widget=cleanWidget(raw);const allowed=widget.id==='week'?['id','visible','size','settings']:['id','visible','size'];
  if(Object.keys(raw).some(key=>!allowed.includes(key))||!ids.includes(widget.id)||seen.has(widget.id)||typeof widget.visible!=='boolean'||!['full','compact','square'].includes(widget.size)||(widget.size==='square'&&!squareIds.has(widget.id)))return null;
  if(widget.id==='week'&&(typeof widget.settings!=='object'||Object.keys(weekSettings()).some(key=>typeof widget.settings[key]!=='boolean')))return null;
  seen.add(widget.id);widgets.push(widget);
 }
 if(legacyIds.some(id=>!seen.has(id)))return null;
 if(!seen.has('week')){widgets.unshift({id:'week',visible:true,size:'full',settings:weekSettings()});seen.add('week')}
 if(!seen.has('trip')){const index=widgets.findIndex(widget=>widget.id==='priority');widgets.splice(index>=0?index+1:1,0,{id:'trip',visible:true,size:'full'});seen.add('trip')}
 if(!seen.has('pinboard')){const index=widgets.findIndex(widget=>widget.id==='next');widgets.splice(index>=0?index+1:Math.min(5,widgets.length),0,{id:'pinboard',visible:true,size:'full'});seen.add('pinboard')}
 prePinboardIds.forEach(id=>{if(!seen.has(id)){widgets.push({id,visible:false,size:'full'});seen.add(id)}});
 return {...value,widgets};
}
const strings={de:{edit:'Raster bearbeiten',heading:'Dein Heute-Raster',hint:'Ordne Widgets, blende sie ein oder aus und wähle die passende Größe. Geeignete Widgets können halbbreit als Quadrat nebeneinander stehen.',save:'Speichern',cancel:'Abbrechen',reset:'Standard wiederherstellen',up:'Nach oben',down:'Nach unten',compact:'Kompakt',full:'Ausführlich',square:'Quadrat',size:'Größe',visible:'Anzeigen',empty:'Alle Widgets sind ausgeblendet. Bearbeite das Raster, um sie einzublenden.',error:'Das Raster konnte nicht gespeichert werden. Dein Entwurf bleibt erhalten.',loadError:'Dein gespeichertes Raster konnte nicht geladen werden.',reload:'Erneut laden',conflict:'Das Raster wurde auf einem anderen Gerät geändert. Lade es erneut, bevor du weiter bearbeitest.',preview:'Vorschau',week:'Wochenkompass',pinboard:'Pinnwand',trip:'Reise',waste:'Müllabfuhr',weather:'Wetter',priority:'Prioritäten',next:'Als Nächstes',tasks:'Aufgaben',shopping:'Einkauf',routines:'Zuletzt gemacht',birthdays:'Geburtstage',notes:'Notizzettel',loyalty:'Bonuskarten',inbox:'Familien-Inbox',weekEvents:'Normale Termine',weekWaste:'Müllabfuhr',weekHolidays:'Ferien',weekSpecial:'Weitere Spezialereignisse'},en:{edit:'Edit grid',heading:'Your Today grid',hint:'Reorder widgets, show or hide them, and choose the right size. Suitable widgets can sit side by side as half-width squares.',save:'Save',cancel:'Cancel',reset:'Restore defaults',up:'Move up',down:'Move down',compact:'Compact',full:'Detailed',square:'Square',size:'Size',visible:'Show',empty:'All widgets are hidden. Edit the grid to show them.',error:'Could not save your grid. Your draft has been kept.',loadError:'Your saved grid could not be loaded.',reload:'Reload',conflict:'This grid changed on another device. Reload it before continuing to edit.',preview:'Preview',week:'Week compass',pinboard:'Pinboard',trip:'Trip',waste:'Waste collection',weather:'Weather',priority:'Priorities',next:'Up next',tasks:'Tasks',shopping:'Shopping',routines:'Recently done',birthdays:'Birthdays',notes:'Notes',loyalty:'Loyalty cards',inbox:'Family inbox',weekEvents:'Regular events',weekWaste:'Waste collection',weekHolidays:'School holidays',weekSpecial:'Other special events'}};
export default function TodayLayout({family,header,onboarding,widgets}){
 const language=i18n.language;const s=strings[language.startsWith('de')?'de':'en'];
 const availableWidgets=widgets||{};
 const editButton=useRef(null);const editorHeading=useRef(null);
 const [saved,setSaved]=useState({version:1,revision:0,widgets:defaults()});const [draft,setDraft]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [loaded,setLoaded]=useState(false);const [conflict,setConflict]=useState(false);
 const load=async()=>{setBusy(true);try{const result=normalizeLayout(await api(`/today-layout/?family=${family.id}`));if(!result)throw new Error('layout');setSaved(result);setDraft(null);setError('');setConflict(false);setLoaded(true)}catch{setError(s.loadError);setLoaded(false)}finally{setBusy(false)}};
 useEffect(()=>{let current=true;setLoaded(false);setDraft(null);setError('');setSaved({version:1,revision:0,widgets:defaults()});api(`/today-layout/?family=${family.id}`).then(result=>{if(current){const normalized=normalizeLayout(result);if(!normalized)throw new Error('layout');setSaved(normalized);setLoaded(true)}}).catch(()=>{if(current)setError(s.loadError)});return()=>{current=false}},[family.id]);
 useEffect(()=>{if(draft)editorHeading.current?.focus()},[Boolean(draft)]);
 const finish=()=>{setDraft(null);editButton.current?.focus()};
 const change=(index,patch)=>setDraft(draft.map((widget,i)=>i===index?{...widget,...patch}:widget));
 const changeWeek=(index,key,value)=>setDraft(draft.map((widget,i)=>i===index?{...widget,settings:{...weekSettings(),...(widget.settings||{}),[key]:value}}:widget));
 const move=(index,delta)=>{const next=[...draft];[next[index],next[index+delta]]=[next[index+delta],next[index]];setDraft(next)};
 const save=async()=>{setBusy(true);setError('');try{const result=normalizeLayout(await api(`/today-layout/?family=${family.id}`,{method:'PUT',body:JSON.stringify({...saved,widgets:draft})}));if(!result)throw new Error('layout');setSaved(result);finish()}catch(e){const stale=e.message.includes('another device');setConflict(stale);setError(stale?s.conflict:s.error)}finally{setBusy(false)}};
 const builtin=id=>id==='week'||id==='pinboard';
 const active=(draft||saved.widgets).filter(widget=>widget.visible&&(builtin(widget.id)||availableWidgets[widget.id]));
 const content=widget=>widget.id==='week'?<WeekCompassWidget family={family} language={language} settings={widget.settings||weekSettings()} compact={widget.size==='compact'}/>:widget.id==='pinboard'?<PinboardTodayWidget family={family} language={language} compact={widget.size==='compact'}/>:availableWidgets[widget.id];
 const render=widget=>{const value=content(widget);if(isValidElement(value)&&value.type?.todayWidgetSelfManaged)return cloneElement(value,{key:widget.id,widgetSize:widget.size});return <div key={widget.id} data-today-widget={widget.id} data-widget-size={widget.size} className={`app-widget today-widget today-widget-${widget.size}`}>{value}</div>};
 return <div className="today-page">{header}<div className="today-layout-toolbar"><button ref={editButton} className="ghost" disabled={busy||!loaded||Boolean(draft)} onClick={()=>{setDraft(saved.widgets.map(cleanWidget));setError('')}}>{s.edit}</button></div>{error&&<div className="today-layout-error" role="alert">{error}{(!loaded||conflict)&&<button onClick={load} disabled={busy}>{s.reload}</button>}</div>}{onboarding}{draft&&<section className="today-layout-editor" aria-label={s.edit}><h2 ref={editorHeading} tabIndex={-1}>{s.heading}</h2><p>{s.hint}</p><ol>{draft.map((widget,index)=><li key={widget.id} className={widget.id==='week'?'today-layout-week-row':''}><div className="today-layout-widget-main"><label><input type="checkbox" checked={widget.visible} onChange={event=>change(index,{visible:event.target.checked})} disabled={busy}/><span>{s[widget.id]}</span></label><div className="today-layout-controls"><select aria-label={`${s[widget.id]} · ${s.size}`} value={widget.size} onChange={event=>change(index,{size:event.target.value})} disabled={busy}><option value="full">{s.full}</option><option value="compact">{s.compact}</option>{squareIds.has(widget.id)&&<option value="square">{s.square}</option>}</select><button aria-label={`${s[widget.id]} · ${s.up}`} onClick={()=>move(index,-1)} disabled={busy||index===0}>↑</button><button aria-label={`${s[widget.id]} · ${s.down}`} onClick={()=>move(index,1)} disabled={busy||index===draft.length-1}>↓</button></div></div>{widget.id==='week'&&widget.visible&&<fieldset className="today-week-settings"><legend>{s.week}</legend>{[['events','weekEvents'],['waste','weekWaste'],['holidays','weekHolidays'],['special','weekSpecial']].map(([key,label])=><label key={key}><input type="checkbox" checked={widget.settings?.[key]!==false} onChange={event=>changeWeek(index,key,event.target.checked)} disabled={busy}/><span>{s[label]}</span></label>)}</fieldset>}</li>)}</ol><div className="today-layout-actions"><button disabled={busy} onClick={()=>setDraft(defaults())}>{s.reset}</button><button disabled={busy} onClick={()=>{finish();setError('');setConflict(false)}}>{s.cancel}</button><button className="primary" disabled={busy||conflict} onClick={save}>{s.save}</button></div><h3>{s.preview}</h3></section>}{active.length>0?<div className="app-widget-grid today-widget-grid">{active.map(render)}</div>:<p className="today-calm">{s.empty}</p>}</div>
}