import {useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import {useFamilyPermissions} from './family-permissions';
import {confirmAction} from './feedback';
import FileDropZone from './FileDropZone';
import './travel.css';

const DAY=86400000;
function dateKey(value){
 if(!value)return null;
 const [y,m,d]=String(value).slice(0,10).split('-').map(Number);
 return Date.UTC(y,m-1,d);
}
function todayKey(){const now=new Date();return Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())}
function countdown(row,w){
 const today=todayKey(),start=dateKey(row.starts_on),end=dateKey(row.ends_on);
 if(start==null||end==null)return '';
 const until=Math.round((start-today)/DAY);
 if(until>1)return w.inDays.replace('{{count}}',until);
 if(until===1)return w.tomorrow;
 if(until===0)return w.today;
 if(today<=end){const day=Math.round((today-start)/DAY)+1,total=Math.round((end-start)/DAY)+1;return w.tripDay.replace('{{day}}',day).replace('{{total}}',total)}
 return w.finished;
}
function displayDate(value,locale){
 if(!value)return '–';
 const [y,m,d]=String(value).split('-').map(Number);
 return new Date(y,m-1,d).toLocaleDateString(locale,{day:'2-digit',month:'short',year:'numeric'});
}

export default function TravelHub({family,onBack,onOpen}){
 const {i18n}=useTranslation();const en=i18n.language.startsWith('en');
 const w=en?{
  title:'Trips',hint:'Plan family trips, keep the countdown visible and collect private photos together.',newTrip:'Plan trip',editTrip:'Edit trip',tripTitle:'Trip name',destination:'Destination',start:'From',end:'To',notes:'Notes',save:'Save',cancel:'Cancel',delete:'Delete trip',deleteConfirm:'Delete this trip and its private album?',empty:'No trips planned yet.',open:'Open',archive:'Archived',inDays:'{{count}} days to go',tomorrow:'Leaving tomorrow',today:'Leaving today',tripDay:'Day {{day}} of {{total}}',finished:'Trip finished',photos:'Private album',addPhotos:'Add photos',photoHint:'JPEG, PNG or WebP. Photos are resized and metadata including GPS is removed on the server.',caption:'Caption for this upload (optional)',removePhoto:'Delete photo',loading:'Loading …',failed:'Could not load trips.',retry:'Try again',calendar:'Calendar',tasks:'Tasks / packing',shopping:'Shopping',expenses:'Expenses',planning:'Continue planning in FamilyOS',dateError:'End date must not be before start date.',archived:'Archived',active:'Active trip',back:'Back'
 }:{
  title:'Reisen',hint:'Familienreisen planen, Countdown im Blick behalten und private Fotos gemeinsam sammeln.',newTrip:'Reise planen',editTrip:'Reise bearbeiten',tripTitle:'Reisename',destination:'Ziel',start:'Von',end:'Bis',notes:'Notizen',save:'Speichern',cancel:'Abbrechen',delete:'Reise löschen',deleteConfirm:'Diese Reise und ihr privates Album löschen?',empty:'Noch keine Reise geplant.',open:'Öffnen',archive:'Archiviert',inDays:'Noch {{count}} Tage',tomorrow:'Morgen geht es los',today:'Heute geht es los',tripDay:'Tag {{day}} von {{total}}',finished:'Reise beendet',photos:'Privates Fotoalbum',addPhotos:'Fotos hinzufügen',photoHint:'JPEG, PNG oder WebP. Fotos werden verkleinert und Metadaten inklusive GPS serverseitig entfernt.',caption:'Bildunterschrift für diesen Upload (optional)',removePhoto:'Foto löschen',loading:'Wird geladen …',failed:'Reisen konnten nicht geladen werden.',retry:'Erneut versuchen',calendar:'Kalender',tasks:'Aufgaben / Packen',shopping:'Einkauf',expenses:'Ausgaben',planning:'In FamilyOS weiterplanen',dateError:'Das Enddatum darf nicht vor dem Startdatum liegen.',archived:'Archiviert',active:'Aktive Reise',back:'Zurück'
 };
 const familyId=family?.id;const {role}=useFamilyPermissions(family);const canManage=role==='owner'||role==='adult';
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[selectedId,setSelectedId]=useState(null),[busy,setBusy]=useState(false),[caption,setCaption]=useState('');
 const emptyForm={title:'',destination:'',starts_on:'',ends_on:'',notes:'',archived:false};const [form,setForm]=useState(emptyForm);
 const selected=useMemo(()=>rows.find(row=>String(row.id)===String(selectedId))||null,[rows,selectedId]);
 async function load(){if(!familyId)return;setLoading(true);setError('');try{const data=await api(`/trips/?family=${encodeURIComponent(familyId)}`);const next=data.results||data||[];setRows(next);if(selectedId&&!next.some(row=>String(row.id)===String(selectedId)))setSelectedId(null)}catch(e){setError(e.message||w.failed)}finally{setLoading(false)}}
 useEffect(()=>{load()},[familyId]);
 function beginCreate(){setEditing('new');setForm(emptyForm);setError('')}
 function beginEdit(row){setEditing(row.id);setForm({title:row.title,destination:row.destination||'',starts_on:row.starts_on,ends_on:row.ends_on,notes:row.notes||'',archived:!!row.archived});setError('')}
 function closeEditor(){setEditing(null);setForm(emptyForm)}
 async function save(e){e.preventDefault();if(form.ends_on<form.starts_on){setError(w.dateError);return}setBusy(true);setError('');try{const payload={...form,family:familyId};if(editing==='new')await api('/trips/',{method:'POST',body:JSON.stringify(payload)});else await api(`/trips/${editing}/`,{method:'PATCH',body:JSON.stringify(payload)});closeEditor();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removeTrip(row){if(!await confirmAction({title:w.deleteConfirm,confirmLabel:w.delete,cancelLabel:w.cancel,danger:true}))return;setBusy(true);try{await api(`/trips/${row.id}/`,{method:'DELETE'});if(String(selectedId)===String(row.id))setSelectedId(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function uploadPhotos(files){if(!selected||!files?.length)return;setBusy(true);setError('');try{const body=new FormData();files.forEach(file=>body.append('images',file));if(caption.trim())body.append('caption',caption.trim());const updated=await api(`/trips/${selected.id}/photos/`,{method:'POST',body});setRows(old=>old.map(row=>row.id===updated.id?updated:row));setCaption('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removePhoto(photo){if(!await confirmAction({title:w.removePhoto,confirmLabel:w.removePhoto,cancelLabel:w.cancel,danger:true}))return;setBusy(true);try{await api(`/trip-photos/${photo.id}/`,{method:'DELETE'});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const locale=en?'en-GB':'de-DE';
 if(selected)return <section className="travel-hub"><header className="page-head"><button className="icon-btn" aria-label={w.back} onClick={()=>setSelectedId(null)}><Icon name="back"/></button><div><h1>{selected.title}</h1><p>{selected.destination||w.title}</p></div></header><section className="card travel-hero"><div><strong>{countdown(selected,w)}</strong><span>{displayDate(selected.starts_on,locale)} – {displayDate(selected.ends_on,locale)}</span></div>{selected.archived&&<span className="travel-badge">{w.archived}</span>}</section>{selected.notes&&<section className="card travel-notes"><p>{selected.notes}</p></section>}<section className="card"><h2>{w.planning}</h2><div className="travel-links"><button className="secondary" onClick={()=>onOpen('calendar')}><Icon name="calendar"/>{w.calendar}</button><button className="secondary" onClick={()=>onOpen('tasks')}><Icon name="tasks"/>{w.tasks}</button><button className="secondary" onClick={()=>onOpen('shopping')}><Icon name="shopping"/>{w.shopping}</button><button className="secondary" onClick={()=>onOpen('expenses')}><Icon name="receipt"/>{w.expenses}</button></div></section><section className="card travel-album"><h2>{w.photos}</h2>{selected.can_add_photos&&<><label>{w.caption}<input maxLength={240} value={caption} onChange={e=>setCaption(e.target.value)}/></label><FileDropZone multiple accept="image/jpeg,image/png,image/webp" disabled={busy} icon="camera" title={w.addPhotos} hint={w.photoHint} onFiles={uploadPhotos}/></>}{selected.photos?.length?<div className="travel-photos">{selected.photos.map((photo,index)=><figure key={photo.id}><a href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} width={photo.width} height={photo.height} loading="lazy" alt={`${selected.title} · ${index+1}`}/></a>{photo.caption&&<figcaption>{photo.caption}</figcaption>}{photo.can_delete&&<button className="ghost-danger compact" disabled={busy} onClick={()=>removePhoto(photo)}>{w.removePhoto}</button>}</figure>)}</div>:<p className="travel-muted">{w.addPhotos}</p>}</section>{selected.can_manage&&<div className="travel-detail-actions"><button className="secondary" onClick={()=>beginEdit(selected)}>{w.editTrip}</button><button className="ghost-danger" disabled={busy} onClick={()=>removeTrip(selected)}>{w.delete}</button></div>}{editing&&<TripEditor w={w} form={form} setForm={setForm} save={save} close={closeEditor} busy={busy}/>}</section>;
 return <section className="travel-hub"><header className="page-head"><button className="icon-btn" aria-label={w.back} onClick={onBack}><Icon name="back"/></button><div><h1>{w.title}</h1><p>{w.hint}</p></div></header>{canManage&&!editing&&<button className="primary travel-new" onClick={beginCreate}><Icon name="plus"/>{w.newTrip}</button>}{error&&<div className="card travel-error" role="alert">{error} {!editing&&<button onClick={load}>{w.retry}</button>}</div>}{editing&&<TripEditor w={w} form={form} setForm={setForm} save={save} close={closeEditor} busy={busy}/>}<div className="travel-list">{rows.map(row=><article className={`card travel-card ${row.archived?'is-archived':''}`} key={row.id}><div className="travel-card-main"><span className="travel-countdown">{countdown(row,w)}</span><h2>{row.title}</h2>{row.destination&&<p><Icon name="location" size={14}/>{row.destination}</p>}<small>{displayDate(row.starts_on,locale)} – {displayDate(row.ends_on,locale)}</small>{row.archived&&<span className="travel-badge">{w.archive}</span>}</div><div className="travel-card-actions"><button className="primary compact" onClick={()=>setSelectedId(row.id)}>{w.open}</button>{row.can_manage&&<button className="secondary compact" onClick={()=>beginEdit(row)}>{w.editTrip}</button>}</div></article>)}</div>{loading&&<p role="status">{w.loading}</p>}{!loading&&!rows.length&&!error&&!editing&&<div className="card travel-empty"><Icon name="route" size={34}/><strong>{w.empty}</strong>{canManage&&<button className="primary" onClick={beginCreate}>{w.newTrip}</button>}</div>}</section>
}

function TripEditor({w,form,setForm,save,close,busy}){return <form className="card travel-editor" onSubmit={save}><h2>{form.title?w.editTrip:w.newTrip}</h2><label>{w.tripTitle}<input required maxLength={160} value={form.title} onChange={e=>setForm(old=>({...old,title:e.target.value}))}/></label><label>{w.destination}<input maxLength={160} value={form.destination} onChange={e=>setForm(old=>({...old,destination:e.target.value}))}/></label><div className="travel-date-grid"><label>{w.start}<input required type="date" value={form.starts_on} onChange={e=>setForm(old=>({...old,starts_on:e.target.value}))}/></label><label>{w.end}<input required type="date" min={form.starts_on||undefined} value={form.ends_on} onChange={e=>setForm(old=>({...old,ends_on:e.target.value}))}/></label></div><label>{w.notes}<textarea rows={4} maxLength={10000} value={form.notes} onChange={e=>setForm(old=>({...old,notes:e.target.value}))}/></label>{form.title&&<label className="travel-checkbox"><input type="checkbox" checked={form.archived} onChange={e=>setForm(old=>({...old,archived:e.target.checked}))}/>{w.archive}</label>}<div className="travel-editor-actions"><button type="button" className="secondary" onClick={close} disabled={busy}>{w.cancel}</button><button className="primary" disabled={busy}>{w.save}</button></div></form>}
