import {useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {Icon} from './icons';
import './weather-i18n';
import './weather.css';
import {dayLabel,localTime,millimeters,percent,speed,temperature,weatherCondition,weatherDescription} from './weather-ui';

const emptyWeather={source:{provider:'',stale:false,last_success_at:null,last_sync_status:'missing',last_sync_error:'',location:{}},current:null,days:[],alerts:[]};

function AlertCard({alert,t,language}){
 const level=Number(alert.level||0);const valid=alert.ends_at?new Intl.DateTimeFormat(language==='en'?'en-GB':'de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(alert.ends_at)):'';
 return <article className={`weather-alert level-${Math.min(4,Math.max(1,level||1))}`}>
   <div className="weather-alert-icon" aria-hidden="true"><Icon name="warning" size={20}/></div>
   <div className="weather-alert-copy"><div className="weather-alert-head"><strong>{alert.title}</strong>{level>0&&<span className="weather-alert-level">{level}</span>}</div>
   {(alert.region||valid)&&<p className="weather-alert-meta">{alert.region}{alert.region&&valid?' · ':''}{valid&&t('weatherUi.validUntil',{value:valid})}</p>}
   {alert.description&&<p>{alert.description}</p>}{alert.instruction&&<p className="weather-alert-action">{alert.instruction}</p>}</div>
 </article>
}

function Metric({label,value}){return <div className="weather-metric"><span>{label}</span><strong>{value}</strong></div>}

export default function WeatherView({family,onBack,onOpenIntegrations}){
 const {t,i18n}=useTranslation();const language=(i18n.resolvedLanguage||i18n.language||'de').slice(0,2);const [data,setData]=useState(emptyWeather);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState(0);
 async function load(){if(!family?.id)return;setLoading(true);setError('');try{const response=await api(`/weather/?family=${encodeURIComponent(family.id)}`);setData(response||emptyWeather);setSelected(0)}catch(err){setError(err.message||'weather_failed')}finally{setLoading(false)}}
 useEffect(()=>{load()},[family?.id]);
 const days=(data.days||[]).slice(0,7);const chosen=days[Math.min(selected,Math.max(0,days.length-1))]||null;const today=days[0]||null;const current=data.current;const condition=weatherCondition(current?.weather_code);const source=data.source||emptyWeather.source;
 const lastUpdated=useMemo(()=>{if(!source.last_success_at)return '';try{return new Intl.DateTimeFormat(language==='en'?'en-GB':'de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(source.last_success_at))}catch{return ''}},[source.last_success_at,language]);
 if(loading)return <main className="weather-page content-page" aria-busy="true"><header className="page-head"><button className="icon-btn" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div><h1>{t('weatherUi.title')}</h1><p>{t('weatherUi.subtitle')}</p></div></header><section className="weather-loading card"><span className="skeleton-line wide"/><span className="skeleton-line"/></section></main>;
 if(error&&!current&&!days.length)return <main className="weather-page content-page"><header className="page-head"><button className="icon-btn" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div><h1>{t('weatherUi.title')}</h1><p>{t('weatherUi.subtitle')}</p></div></header><section className="empty-state card"><Icon name="weather" size={34}/><h2>{t('weatherUi.noData')}</h2><p>{t('weatherUi.noDataHint')}</p><button className="primary compact" onClick={onOpenIntegrations}>{t('weatherUi.openIntegrations')}</button></section></main>;
 return <main className="weather-page content-page">
   <header className="page-head weather-page-head"><button className="icon-btn" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div><h1>{t('weatherUi.title')}</h1><p>{t('weatherUi.subtitle')}</p></div>{source.location?.label&&<span className="weather-location"><Icon name="location" size={14}/>{source.location.label}</span>}</header>
   {(data.alerts||[]).length>0&&<section className="weather-section" aria-labelledby="weather-alerts-title"><div className="section-title-row"><div><small>{t('weatherWarning')}</small><h2 id="weather-alerts-title">{t('weatherUi.alerts')}</h2></div></div><div className="weather-alerts">{data.alerts.map(alert=><AlertCard key={alert.id} alert={alert} t={t} language={language}/>)}</div></section>}
   {source.stale&&<aside className="weather-stale" role="status"><Icon name="warning" size={18}/><div><strong>{t('weatherUi.notCurrent')}</strong><span>{t('weatherUi.staleHint')}</span>{lastUpdated&&<small>{t('weatherUi.updated',{value:lastUpdated})}</small>}</div></aside>}
   {current?<section className="weather-current-card card" data-testid="weather-current-detail"><div className="weather-current-main"><span className="weather-current-icon" aria-label={weatherDescription(current.weather_code,t)}><Icon name={condition.icon} size={48}/></span><div><small>{t('weatherUi.current')}</small><div className="weather-temperature">{temperature(current.temperature)}</div><strong>{weatherDescription(current.weather_code,t)}</strong><p>{current.apparent_temperature!=null?t('weatherUi.feelsLike',{value:temperature(current.apparent_temperature)}):''}</p></div></div><div className="weather-current-metrics"><Metric label={t('weatherUi.highLow')} value={`${temperature(today?.temp_min)} / ${temperature(today?.temp_max)}`}/><Metric label={t('weatherUi.precipProbability')} value={percent(today?.precipitation_probability)}/><Metric label={t('weatherUi.wind')} value={speed(current.wind_speed)}/><Metric label={t('weatherUi.humidity')} value={percent(current.humidity)}/></div><footer>{source.provider&&<span>{source.provider}</span>}{lastUpdated&&<span>{t('weatherUi.updated',{value:lastUpdated})}</span>}</footer></section>:null}
   {days.length?<section className="weather-section" aria-labelledby="forecast-title"><div className="section-title-row"><div><small>{t('forecast')}</small><h2 id="forecast-title">{t('weatherUi.forecast')}</h2></div></div><div className="weather-days" data-testid="weather-days">{days.map((day,index)=>{const c=weatherCondition(day.weather_code);const active=index===selected;return <button key={`${day.date}-${index}`} className={`weather-day ${active?'active':''}`} type="button" aria-pressed={active} onClick={()=>setSelected(index)} data-testid="weather-day"><strong>{dayLabel(day.date,language,t('weatherUi.today'))}</strong><span className="weather-day-icon" aria-label={weatherDescription(day.weather_code,t)}><Icon name={c.icon} size={24}/></span><span className="weather-day-condition">{weatherDescription(day.weather_code,t)}</span><span className="weather-day-temp"><b>{temperature(day.temp_max)}</b><span>{temperature(day.temp_min)}</span></span><span className="weather-day-rain"><Icon name="rain" size={13}/>{percent(day.precipitation_probability)}</span></button>})}</div>{chosen&&<article className="weather-detail card" data-testid="weather-day-detail"><div><small>{t('weatherUi.details')}</small><h3>{dayLabel(chosen.date,language,t('weatherUi.today'))} · {weatherDescription(chosen.weather_code,t)}</h3></div><div className="weather-detail-grid"><Metric label={t('weatherUi.precipitation')} value={millimeters(chosen.precipitation_sum)}/><Metric label={t('weatherUi.wind')} value={speed(chosen.wind_max)}/><Metric label={t('weatherUi.gusts')} value={speed(chosen.wind_gust_max)}/><Metric label={t('weatherUi.sunrise')} value={localTime(chosen.sunrise,language)}/><Metric label={t('weatherUi.sunset')} value={localTime(chosen.sunset,language)}/><Metric label={t('weatherUi.uv')} value={chosen.uv_index_max==null?'–':Number(chosen.uv_index_max).toLocaleString(language==='en'?'en-GB':'de-DE',{maximumFractionDigits:1})}/></div></article>}</section>:<section className="empty-state card"><h2>{t('weatherUi.noData')}</h2><p>{t('weatherUi.noDataHint')}</p><button className="secondary" onClick={onOpenIntegrations}>{t('weatherUi.openIntegrations')}</button></section>}
   {error&&<p className="weather-inline-error" role="status">{t('weatherUi.retryHint')}</p>}
 </main>;
}
