import {useEffect,useState} from 'react';
import {api} from './api';
import i18n from './i18n';
import {Icon} from './icons';
import {formatDateTime} from './locale';
import {toast} from './feedback';
import {value,weatherGlyph,weatherLabel} from './weather-ui';
import './weather-hub.css';

export default function WeatherHub({family,onBack,t}){
 const [data,setData]=useState(null);const [openDay,setOpenDay]=useState(null);const language=i18n.language;const de=language.startsWith('de');
 async function load(){try{setData(await api(`/weather/?family=${encodeURIComponent(family.id)}`))}catch(e){toast(e.message||t('saveFailed'),{type:'error'})}}
 useEffect(()=>{load()},[family?.id]);
 if(!data)return <div className="smart-empty" role="status"><Icon name="refresh" size={34}/><strong>{de?'Wetter wird geladen':'Loading weather'}</strong></div>;
 const current=data.current,days=data.days||[],alerts=data.alerts||[],source=data.source||{};
 return <div className="weather-page"><div className="page-head"><button className="back-button" onClick={onBack} aria-label={t('back')}><Icon name="back"/></button><div className="grow"><small>{source.location?.label||'Open-Meteo'}</small><h1>{t('weather')}</h1></div></div>
 {source.stale&&<div className="weather-stale" role="status"><Icon name="warning"/><span><strong>{de?'Nicht aktuell':'Not current'}</strong>{source.last_success_at&&` · ${de?'Zuletzt aktualisiert':'Last updated'} ${formatDateTime(language,source.last_success_at,{dateStyle:'short',timeStyle:'short'})}`}</span></div>}
 {alerts.map(alert=><section className="weather-alert" key={alert.id}><Icon name="warning"/><div><small>{alert.provider} · {alert.region||''}</small><strong>{alert.title}</strong>{alert.description&&<span>{alert.description}</span>}{alert.instruction&&<p>{alert.instruction}</p>}</div></section>)}
 {current?<section className="weather-current"><span className="weather-glyph" role="img" aria-label={weatherLabel(current.weather_code,language)}>{weatherGlyph(current.weather_code)}</span><div className="weather-current-main"><small>{de?'Aktuell':'Now'}</small><strong>{value(current.temperature,' °C')}</strong><span>{weatherLabel(current.weather_code,language)}</span></div><div className="weather-current-stats"><span><b>{value(current.apparent_temperature,' °C')}</b>{de?'Gefühlt':'Feels like'}</span><span><b>{value(current.humidity,' %')}</b>{de?'Feuchte':'Humidity'}</span><span><b>{value(current.wind_speed,' km/h')}</b>{de?'Wind':'Wind'}</span><span><b>{value(current.precipitation,' mm')}</b>{de?'Niederschlag':'Precipitation'}</span></div></section>:<div className="smart-empty"><Icon name="weather" size={34}/><strong>{de?'Noch keine Wetterdaten':'No weather data yet'}</strong><span>{de?'Prüfe die Wetterintegration und synchronisiere sie erneut.':'Check the weather integration and sync it again.'}</span></div>}
 <section className="weather-forecast"><div className="weather-section-head"><div><small>{de?'VORHERSAGE':'FORECAST'}</small><h2>{de?'7 Tage':'7 days'}</h2></div><span>{days.length}/7</span></div><div className="weather-days">{days.map((day,index)=>{const expanded=openDay===day.date;return <article className={`weather-day ${index===0?'today':''}`} key={day.date}><button aria-expanded={expanded} onClick={()=>setOpenDay(expanded?null:day.date)}><span className="weather-day-name">{index===0?(de?'Heute':'Today'):formatDateTime(language,`${day.date}T12:00:00`,{weekday:'short'})}</span><span className="weather-day-glyph" role="img" aria-label={weatherLabel(day.weather_code,language)}>{weatherGlyph(day.weather_code)}</span><span className="weather-day-condition">{weatherLabel(day.weather_code,language)}</span><span className="weather-temps"><b>{value(day.temp_max,'°')}</b><span>{value(day.temp_min,'°')}</span></span><span className="weather-rain">💧 {value(day.precipitation_probability,'%')}</span><Icon name={expanded?'up':'next'}/></button>{expanded&&<div className="weather-day-details"><span><b>{value(day.precipitation_sum,' mm')}</b>{de?'Niederschlag':'Precipitation'}</span><span><b>{value(day.wind_max,' km/h')}</b>{de?'Wind max.':'Max wind'}</span><span><b>{value(day.wind_gust_max,' km/h')}</b>{de?'Böen':'Gusts'}</span><span><b>{value(day.uv_index_max)}</b>UV</span><span><b>{day.sunrise?formatDateTime(language,day.sunrise,{timeStyle:'short'}):'–'}</b>{de?'Sonnenaufgang':'Sunrise'}</span><span><b>{day.sunset?formatDateTime(language,day.sunset,{timeStyle:'short'}):'–'}</b>{de?'Sonnenuntergang':'Sunset'}</span></div>}</article>})}</div></section>
 <p className="weather-provider">Open-Meteo · {source.last_success_at&&`${de?'aktualisiert':'updated'} ${formatDateTime(language,source.last_success_at,{dateStyle:'short',timeStyle:'short'})}`}</p></div>
}
