import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
import {toast} from './feedback';
import './workflow-i18n';

export default function WorkflowSettings({list,onChanged}){
 const {t}=useTranslation();const [columns,setColumns]=useState((list.workflow_columns||[]).filter(x=>!x.archived));const [name,setName]=useState('');const [busy,setBusy]=useState(false);
 async function patch(column,values){setBusy(true);try{const saved=await api(`/task-workflow-columns/${column.id}/`,{method:'PATCH',body:JSON.stringify(values)});setColumns(rows=>rows.map(x=>x.id===column.id?saved:x).filter(x=>!x.archived).sort((a,b)=>a.position-b.position));await onChanged?.()}catch(e){toast(e.message,{type:'error'})}finally{setBusy(false)}}
 async function reorder(index,direction){const other=columns[index+direction];if(!other)return;const column=columns[index];setBusy(true);try{await api(`/task-workflow-columns/${column.id}/`,{method:'PATCH',body:JSON.stringify({position:other.position})});await api(`/task-workflow-columns/${other.id}/`,{method:'PATCH',body:JSON.stringify({position:column.position})});setColumns(rows=>rows.map(x=>x.id===column.id?{...x,position:other.position}:x.id===other.id?{...x,position:column.position}:x).sort((a,b)=>a.position-b.position));await onChanged?.()}catch(e){toast(e.message,{type:'error'})}finally{setBusy(false)}}
 async function add(){if(!name.trim())return;setBusy(true);try{const column=await api(`/task-lists/${list.id}/workflow-columns/`,{method:'POST',body:JSON.stringify({name:name.trim(),kind:'waiting',position:Math.max(0,...columns.map(x=>x.position))+1,is_terminal:false})});setColumns(rows=>[...rows,column]);setName('');await onChanged?.()}catch(e){toast(e.message,{type:'error'})}finally{setBusy(false)}}
 return <fieldset className="workflow-settings"><legend>{t('workflowUi.status')}</legend>{columns.map((column,index)=><div className="workflow-column-setting" key={column.id}><input aria-label={`${t('workflowUi.columnName')} ${column.name}`} defaultValue={column.name} maxLength={80} onBlur={e=>{const value=e.target.value.trim();if(value&&value!==column.name)void patch(column,{name:value})}} disabled={busy}/><button type="button" aria-label={`${column.name}: ${t('workflowUi.sortUp')}`} disabled={busy||index===0} onClick={()=>reorder(index,-1)}>↑</button><button type="button" aria-label={`${column.name}: ${t('workflowUi.sortDown')}`} disabled={busy||index===columns.length-1} onClick={()=>reorder(index,1)}>↓</button><button type="button" disabled={busy} onClick={()=>patch(column,{archived:true})}>{t('workflowUi.archiveColumn')}</button></div>)}{columns.length<8&&<div className="workflow-column-setting"><input value={name} onChange={e=>setName(e.target.value)} aria-label={t('workflowUi.newColumn')} maxLength={80}/><button type="button" onClick={add} disabled={busy||!name.trim()}>{t('workflowUi.addColumn')}</button></div>}</fieldset>
}
