import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api';

const starterNames=['Bad putzen','Bettwäsche wechseln','Kühlschrank reinigen','Wasserfilter wechseln'];

async function boot(page){
 const state=await installApiMocks(page,{dismissOnboarding:true});
 const rows=Array.from({length:12},(_,i)=>({id:`routine-${i}`,family:state.family.id,name:starterNames[i]||`Routine ${i}`,icon:i===0?'sparkles':i===1?'bed':i===2?'snowflake':i===3?'droplets':'history',active:true,target_count:i===0?1:null,target_period_days:7,reminder_enabled:true,logs:[],log_count:0,period_count:0,last_done_at:null,prediction:i===0?{status:'overdue',expected_at:new Date(Date.now()-86400000).toISOString()}:i===1?{status:'due',expected_at:new Date().toISOString()}:{status:'not_enough_data'}}));
 const requests=[];
 await page.route('**/api/routines/**',async route=>{
  const req=route.request();const path=new URL(req.url()).pathname;let body={};try{body=req.postDataJSON()||{}}catch{}
  if(req.method()==='GET')return route.fulfill({json:{results:rows,next:null}});
  if(path.endsWith('/done/')){const row=rows.find(x=>path.includes(`/${x.id}/`));row.logs.unshift({id:`log-${Date.now()}`,done_at:new Date().toISOString(),done_by:1,done_by_name:'Alex'});row.last_done_at=row.logs[0].done_at;row.log_count++;row.period_count++;row.prediction={status:'upcoming',expected_at:new Date(Date.now()+7*86400000).toISOString()};requests.push(body);return route.fulfill({status:201,json:row.logs[0]})}
  if(path.includes('/logs/')&&req.method()==='DELETE'){const row=rows.find(x=>path.includes(`/${x.id}/`));row.logs=[];row.log_count=0;row.period_count=0;row.last_done_at=null;return route.fulfill({status:204,body:''})}
  if(path.endsWith('/snooze/')&&req.method()==='POST'){const row=rows.find(x=>path.includes(`/${x.id}/`));row.snoozed_until=body.hours?new Date(Date.now()+body.hours*3600000).toISOString():null;return route.fulfill({json:{snoozed_until:row.snoozed_until}})}
  if(req.method()==='DELETE'){const index=rows.findIndex(x=>path.includes(`/${x.id}/`));if(index>=0)rows.splice(index,1);return route.fulfill({status:204,body:''})}
  if(req.method()==='POST'){const row={...body,id:'routine-new',logs:[],log_count:0,period_count:0,last_done_at:null,prediction:{status:'not_enough_data'}};rows.push(row);requests.push(body);return route.fulfill({status:201,json:row})}
  if(req.method()==='PATCH'){const row=rows.find(x=>path.includes(`/${x.id}/`));Object.assign(row,body);return route.fulfill({json:row})}
  return route.fallback()
 });
 await page.goto('/?page=routines');await page.waitForLoadState('networkidle');return{rows,requests}
}

test('routines · all entries visible, record, Undo and optional goal',async({page})=>{const state=await boot(page);await expect(page.locator('.routine-card')).toHaveCount(12);await expect(page.getByText('2',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Bad putzen jetzt erledigt',exact:true}).click();await expect(page.locator('.routine-card').filter({hasText:'Bad putzen'})).toContainText('Zuletzt:');expect(state.requests[0].request_id).toBeTruthy();await page.getByRole('button',{name:'Rückgängig',exact:true}).click();await expect.poll(()=>state.rows[0].log_count).toBe(0);await page.locator('.page-head').getByRole('button',{name:'Routine anlegen',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Lüften');await dialog.getByLabel('Häufigkeitsziel verwenden').check();await dialog.getByLabel('Wie oft?',{exact:true}).fill('3');await dialog.getByLabel('Innerhalb von wie vielen Tagen?').fill('1');await dialog.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByText('Lüften',{exact:true})).toBeVisible();expect(state.rows.at(-1).target_count).toBe(3);await page.reload();await expect(page.getByText('Lüften',{exact:true})).toBeVisible()});

test('routines · starter routine is editable and deletable like every other routine',async({page})=>{const state=await boot(page);const card=page.locator('.routine-card').filter({hasText:'Bettwäsche wechseln'});await card.getByRole('button',{name:'Routine bearbeiten: Bettwäsche wechseln'}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Bettwäsche frisch beziehen');await dialog.getByLabel('Symbol').selectOption('house');await dialog.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByText('Bettwäsche frisch beziehen',{exact:true})).toBeVisible();expect(state.rows.find(row=>row.id==='routine-1')?.name).toBe('Bettwäsche frisch beziehen');await page.locator('.routine-card').filter({hasText:'Bettwäsche frisch beziehen'}).getByRole('button',{name:'Routine bearbeiten: Bettwäsche frisch beziehen'}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Routine löschen',exact:true}).click();const confirm=page.getByRole('alertdialog');await expect(confirm).toBeVisible();await confirm.getByRole('button',{name:'Löschen',exact:true}).click();await expect(page.getByText('Bettwäsche frisch beziehen',{exact:true})).toHaveCount(0);expect(state.rows.some(row=>row.id==='routine-1')).toBe(false)});

test('routines · filters surface due work and mobile has no horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);await page.getByRole('button',{name:'Fällig',exact:true}).last().click();await expect(page.locator('.routine-card')).toHaveCount(2);await expect(page.locator('.routine-card').first()).toContainText('Bad putzen');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('.bottom-nav').getByRole('button',{name:'Mehr',exact:true}).click();await page.locator('.menu-row').filter({hasText:'Routinen'}).click();await expect(page.getByRole('heading',{name:'Routinen',exact:true})).toBeVisible()});
