import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api.js';

async function boot(page,{count=8,categories=4,path='/?page=shopping'}={}){
 const state=await installApiMocks(page,{dismissOnboarding:true});state.shoppingLists[0].items=Array.from({length:count},(_,index)=>({id:`density-${index}`,shopping_list:'shop-1',name:`Artikel ${index+1}`,quantity:'2×',category:`Kategorie ${index%categories+1}`,aisle:'',checked:false,note:'Notiz',favorite:false}));
 await page.goto(path);await page.waitForLoadState('networkidle');if(!path.includes('mode=store'))await page.getByRole('button',{name:/Im Laden/}).click();await expect(page.locator('.store-focus')).toBeVisible();return state;
}

for(const config of [{count:8,categories:4},{count:12,categories:2}])test(`store · ${config.count} items in ${config.categories} categories fit at 390×844`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page,config);const rows=page.locator('.store-row');await expect(rows).toHaveCount(config.count);const footer=await page.locator('.store-footer').boundingBox();for(const row of await rows.all()){const box=await row.boundingBox();expect(box.height).toBeGreaterThanOrEqual(48);expect(box.y+box.height).toBeLessThanOrEqual(footer.y+1)}await expect(page.locator('.topbar')).toBeHidden();await expect(page.locator('.global-create-fab')).toBeHidden();
});
test('store · checked items stay visible, details edit and Undo restores exactly that item',async({page})=>{
 const state=await boot(page);const row=page.locator('.store-row').filter({hasText:'Artikel 1'}).first();await row.locator('.store-details').click();await expect(page.getByRole('dialog').getByRole('heading',{name:'Artikel 1',exact:true})).toBeVisible();expect(state.shoppingLists[0].items[0].checked).toBe(false);await page.keyboard.press('Escape');await row.locator('.store-check').click();await expect(row).toHaveClass(/store-checked/);await expect(row).toBeVisible();await expect(page.getByRole('button',{name:'1 im Wagen'})).toBeVisible();await expect(page.locator('.store-row')).toHaveCount(8);await page.getByRole('button',{name:'Rückgängig',exact:true}).click();await expect(page.locator('.store-row')).toHaveCount(8);await expect(row).not.toHaveClass(/store-checked/);await expect.poll(()=>state.shoppingLists[0].items[0].checked).toBe(false);
});
test('store · keyboard, add sheet, reload-safe list and browser Back',async({page})=>{
 const state=await boot(page,{path:'/?page=shopping&list=shop-1&mode=store'});await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.store-check').first().focus();await page.keyboard.press('Space');await expect(page.getByRole('button',{name:'1 im Wagen'})).toBeVisible();await expect(page.locator('.store-row')).toHaveCount(8);await page.locator('.store-header').getByRole('button',{name:'Artikel hinzufügen'}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('input')).toBeFocused();await dialog.locator('input').fill('Vergessen');await dialog.locator('input').press('Enter');await expect(dialog).toHaveCount(0);await expect(page.getByText('Vergessen',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('.store-focus')).toBeVisible();await page.getByRole('button',{name:'Zur Planung'}).click();await expect(page.locator('.shopping-page')).toBeVisible();await page.goBack();await expect(page.locator('.store-focus')).toBeVisible();expect(state.shoppingLists[0].items.some(x=>x.name==='Vergessen')).toBe(true);
});
test('store · visible remote refresh retains local pending changes',async({page,context})=>{
 const state=await boot(page);await context.setOffline(true);await page.locator('.store-check').first().click();await expect(page.getByRole('button',{name:'1 im Wagen'})).toBeVisible();await expect(page.locator('.store-row')).toHaveCount(8);await page.getByRole('button',{name:'Rückgängig',exact:true}).click();await expect(page.getByRole('button',{name:'0 im Wagen'})).toBeVisible();state.shoppingLists[0].items.push({id:'remote-item',name:'Von Zuhause',checked:false,category:'Kategorie 1',shopping_list:'shop-1'});await context.setOffline(false);await page.getByRole('button',{name:'Liste aktualisieren'}).click();await expect(page.getByText('Von Zuhause',{exact:true})).toBeVisible();await expect.poll(()=>state.shoppingLists[0].items[0].checked).toBe(false);
});
