import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});

test('superadmin creates tenant, owner registers from invite and lands only in that family',async({page})=>{
 await installApiMocks(page);page.on('dialog',dialog=>dialog.dismiss());let mode='superadmin';let family=null;
 await page.route('**/api/auth/session/',route=>json(route,{authenticated:true,user:mode==='superadmin'?{id:99,username:'root',email:'root@example.test',is_superadmin:true}:{id:7,username:'pat-owner',email:'pat@example.test',is_superadmin:false}}));
 await page.route('**/api/families/',route=>json(route,mode==='owner'&&family?[family]:[]));
 await page.route('**/api/superadmin/families/**',async route=>{const url=new URL(route.request().url());const method=route.request().method();if(url.pathname==='/api/superadmin/families/'&&method==='GET')return json(route,family?[family]:[]);if(url.pathname==='/api/superadmin/families/'&&method==='POST'){const body=route.request().postDataJSON();family={id:'tenant-2',name:body.name,slug:'familie-zwei',locale:body.locale,timezone:body.timezone,status:'active',member_count:0,owners:[],memberships:[],pending_owner_invites:[{token:'invite-owner',email:body.owner_email,display_name:body.owner_name}]};return json(route,{family,invite_token:'invite-owner'},201)}return json(route,{detail:'not found'},404)});
 await page.route('**/api/invite/invite-owner/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/api/invite/invite-owner/'&&route.request().method()==='GET')return json(route,{family_id:'tenant-2',family_name:'Familie Zwei',role:'owner',email_hint:'pat@example.test',display_name:'Pat',expires_at:'2099-01-01T00:00:00Z',active:true});if(url.pathname==='/api/invite/invite-owner/register/'&&route.request().method()==='POST'){mode='owner';family={...family,member_count:1,owners:[{username:'pat-owner',email:'pat@example.test',display_name:'Pat'}],memberships:[{id:'membership-owner',role:'owner',display_name:'Pat',username:'pat-owner'}],pending_owner_invites:[]};return json(route,{family,membership:family.memberships[0]},201)}return json(route,{detail:'not found'},404)});

 await page.goto('/');await expect(page.getByText('Superadmin',{exact:true})).toBeVisible();await page.getByLabel('Familienname').fill('Familie Zwei');await page.getByLabel('Owner-Name').fill('Pat');await page.getByLabel('Owner-E-Mail').fill('pat@example.test');await page.getByRole('button',{name:/Familie anlegen/}).click();await expect(page.getByRole('heading',{name:'Familie Zwei'})).toBeVisible();await expect(page.getByText(/offene Owner-Einladung/)).toBeVisible();

 await page.evaluate(()=>localStorage.removeItem('famuhle-session'));await page.goto('/invite/invite-owner');await expect(page.getByText('Einladung zu FamilyOS')).toBeVisible();await expect(page.getByText('Inhaber',{exact:true})).toBeVisible();await page.getByLabel('Benutzername').fill('pat-owner');await page.getByLabel('Passwort').fill('owner-password-123');await page.getByRole('button',{name:'Konto erstellen & beitreten'}).click();

 await expect(page.getByRole('heading',{name:/Hallo Familie/})).toBeVisible();await expect(page.getByText('Superadmin',{exact:true})).toHaveCount(0);await page.locator('.bottom-nav').getByRole('button',{name:'Mehr'}).click();await expect(page.getByText('Familie Zwei · Europe/Berlin',{exact:true})).toBeVisible();
});
