import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});

test('superadmin creates tenant, owner registers from invite and lands only in that family',async({page,context})=>{
 await installApiMocks(page);page.on('dialog',dialog=>dialog.dismiss());let family=null;
 await page.route('**/api/auth/session/',route=>json(route,{authenticated:true,user:{id:99,username:'root',email:'root@example.test',is_superadmin:true}}));
 await page.route('**/api/superadmin/families/**',async route=>{const url=new URL(route.request().url());const method=route.request().method();if(url.pathname==='/api/superadmin/families/'&&method==='GET')return json(route,family?[family]:[]);if(url.pathname==='/api/superadmin/families/'&&method==='POST'){const body=route.request().postDataJSON();family={id:'tenant-2',name:body.name,slug:'familie-zwei',locale:body.locale,timezone:body.timezone,status:'active',member_count:0,owners:[],memberships:[],pending_owner_invites:[{token:'invite-owner',email:body.owner_email,display_name:body.owner_name}]};return json(route,{family,invite_token:'invite-owner'},201)}return json(route,{detail:'not found'},404)});
 await page.goto('/');await expect(page.getByText('Superadmin',{exact:true})).toBeVisible();await page.getByLabel('Familienname').fill('Familie Zwei');await page.getByLabel('Owner-Name').fill('Pat');await page.getByLabel('Owner-E-Mail').fill('pat@example.test');await page.getByRole('button',{name:/Familie anlegen/}).click();await expect(page.getByRole('heading',{name:'Familie Zwei'})).toBeVisible();await expect(page.getByText(/offene Owner-Einladung/)).toBeVisible();

 const ownerPage=await context.newPage();let ownerRegistered=false;
 await ownerPage.addInitScript(()=>{localStorage.setItem('famuhle-language','de');if(sessionStorage.getItem('owner-registered')==='1')localStorage.setItem('famuhle-session','1');else localStorage.removeItem('famuhle-session')});
 await ownerPage.route('**/api/invite/invite-owner/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/api/invite/invite-owner/'&&route.request().method()==='GET')return json(route,{family_id:'tenant-2',family_name:'Familie Zwei',role:'owner',email_hint:'pat@example.test',display_name:'Pat',expires_at:'2099-01-01T00:00:00Z',active:true});if(url.pathname==='/api/invite/invite-owner/register/'&&route.request().method()==='POST'){ownerRegistered=true;family={...family,member_count:1,owners:[{username:'pat-owner',email:'pat@example.test',display_name:'Pat'}],memberships:[{id:'membership-owner',role:'owner',display_name:'Pat',username:'pat-owner'}],pending_owner_invites:[]};await ownerPage.evaluate(()=>sessionStorage.setItem('owner-registered','1'));return json(route,{family,membership:family.memberships[0]},201)}return json(route,{detail:'not found'},404)});
 await ownerPage.route('**/api/auth/session/',route=>json(route,{authenticated:true,user:{id:7,username:'pat-owner',email:'pat@example.test',is_superadmin:false}}));
 await ownerPage.route('**/api/families/',route=>json(route,ownerRegistered?[family]:[]));
 await ownerPage.route('**/api/dashboard/**',route=>json(route,{tasks:[],task_lists:[],events:[],routines:[],shopping_lists:[],inbox_count:0,automation_count:0}));
 await ownerPage.route('**/api/inbox/',route=>json(route,[]));await ownerPage.route('**/api/automation-rules/',route=>json(route,[]));
 await ownerPage.goto('/invite/invite-owner');await expect(ownerPage.getByText('Einladung zu FamilyOS')).toBeVisible();await expect(ownerPage.getByText('Inhaber',{exact:true})).toBeVisible();await ownerPage.getByLabel('Benutzername').fill('pat-owner');await ownerPage.getByLabel('Passwort').fill('owner-password-123');await ownerPage.getByRole('button',{name:'Konto erstellen & beitreten'}).click();
 await expect(ownerPage.getByRole('heading',{name:/Familie Zwei/})).toBeVisible();await expect(ownerPage.getByText('Superadmin',{exact:true})).toHaveCount(0);await ownerPage.locator('.bottom-nav').getByRole('button',{name:'Mehr'}).click();await expect(ownerPage.getByText('Familie Zwei · Europe/Berlin',{exact:true})).toBeVisible();
});