import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api.js';

async function boot(page,{enabled=false}={}){
 const state=await installApiMocks(page,{dismissOnboarding:true});const columns=[{id:'col-open',name:'Offen',kind:'open',position:0,is_terminal:false},{id:'col-active',name:'In Arbeit',kind:'active',position:1,is_terminal:false},{id:'col-done',name:'Erledigt',kind:'done',position:2,is_terminal:true}];state.taskLists[0].workflow_enabled=enabled;state.taskLists[0].workflow_columns=columns;state.tasks[0].workflow_column=enabled?'col-open':null;state.tasks[0].workflow_position='1024';const events=[];
 await page.route('**/api/task-lists/**',async route=>{const request=route.request();const path=new URL(request.url()).pathname;const body=request.postDataJSON()||{};if(request.method()==='PATCH'){Object.assign(state.taskLists[0],body);if(body.workflow_enabled)for(const task of state.tasks)task.workflow_column=task.completed_at?'col-done':'col-open';return route.fulfill({json:state.taskLists[0]})}if(path==='/api/task-lists/')return route.fulfill({json:state.taskLists.map(list=>({...list,open_count:state.tasks.filter(x=>!x.completed_at).length,done_count:state.tasks.filter(x=>x.completed_at).length}))});return route.fallback()});
 await page.route('**/api/tasks/**',async route=>{const request=route.request();const path=new URL(request.url()).pathname;if(path.endsWith('/move/')){const body=request.postDataJSON();const task=state.tasks.find(x=>path.includes(`/${x.id}/`));const column=columns.find(x=>x.id===body.column_id);events.push({id:`history-${events.length}`,from:columns.find(x=>x.id===task.workflow_column)?.name,to:column.name,changed_by:'Alex',changed_at:new Date().toISOString()});Object.assign(task,{workflow_column:column.id,workflow_status:column.name,completed_at:column.is_terminal?new Date().toISOString():null});return route.fulfill({json:task})}if(path.endsWith('/status-history/'))return route.fulfill({json:{results:events}});if(path.endsWith('/toggle/')){const task=state.tasks.find(x=>path.includes(`/${x.id}/`));task.completed_at=task.completed_at?null:new Date().toISOString();task.workflow_column=task.completed_at?'col-done':'col-open';return route.fulfill({json:task})}return route.fallback()});
 await page.goto('/?page=tasks');await page.waitForLoadState('networkidle');return state;
}
test('workflow · simple lists stay simple and owner can opt in',async({page})=>{
 await boot(page);await expect(page.getByRole('button',{name:'Board',exact:true})).toHaveCount(0);await page.getByRole('button',{name:/Alltag/}).click();await page.getByRole('button',{name:'Liste bearbeiten',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Erweiterter Aufgabenmodus').check();await dialog.getByRole('button',{name:'Speichern',exact:true}).click();await page.getByRole('button',{name:'Board',exact:true}).click();await expect(page.locator('.board-card')).toHaveCount(1);
});
test('workflow · list/board, keyboard status, completion, history and reload',async({page})=>{
 const state=await boot(page,{enabled:true});await page.getByRole('button',{name:/Alltag/}).click();await page.getByRole('button',{name:'Board',exact:true}).click();await page.getByLabel('Status für Wäsche aufhängen').selectOption('col-active');await expect.poll(()=>state.tasks[0].workflow_column).toBe('col-active');if(await page.locator('.board-status-tabs').isVisible())await page.locator('.board-status-tabs').getByRole('button',{name:/In Arbeit/}).click();await page.getByLabel('Status für Wäsche aufhängen').selectOption('col-done');await expect.poll(()=>state.tasks[0].completed_at).toBeTruthy();await page.reload();await page.getByRole('button',{name:/Alltag/}).click();await expect(page.getByRole('button',{name:'Board',exact:true})).toHaveClass(/active/);if(await page.locator('.board-status-tabs').isVisible())await page.locator('.board-status-tabs').getByRole('button',{name:/Erledigt/}).click();await page.locator('.board-edit').click();await page.getByText('Statusverlauf',{exact:true}).click();await expect(page.getByText(/Alex: In Arbeit → Erledigt/)).toBeVisible();expect(state.tasks[0].assignee).toBe(1);expect(state.tasks[0].estimate_minutes).toBe(10);
});
test('workflow · desktop drag moves existing task',async({page})=>{
 await page.setViewportSize({width:1440,height:900});const state=await boot(page,{enabled:true});await page.getByRole('button',{name:/Alltag/}).click();await page.getByRole('button',{name:'Board',exact:true}).click();await page.locator('.board-card').dragTo(page.getByRole('region',{name:'In Arbeit',exact:true}));await expect.poll(()=>state.tasks[0].workflow_column).toBe('col-active');
});
