import {test,expect} from '@playwright/test';
import {installApiMocks} from './mock-api.js';
const json=(route,body)=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
const days=Array.from({length:7},(_,i)=>({date:`2026-10-${String(9+i).padStart(2,'0')}`,weather_code:i===2?61:2,temp_min:7+i,temp_max:14+i,apparent_temp_min:6+i,apparent_temp_max:13+i,precipitation_probability:i===2?70:20,precipitation_sum:i===2?5.2:0.4,wind_max:18,wind_gust_max:30,sunrise:`2026-10-${String(9+i).padStart(2,'0')}T07:30:00+02:00`,sunset:`2026-10-${String(9+i).padStart(2,'0')}T18:45:00+02:00`,uv_index_max:2.1}));

test('weather center shows current conditions, seven days, details, alerts and stale status',async({page})=>{
 await installApiMocks(page);await page.route('**/api/weather/**',route=>json(route,{source:{provider:'Open-Meteo',status:'error',stale:true,last_success_at:'2026-10-09T08:00:00Z',location:{label:'Kaiserslautern',latitude:49.44,longitude:7.77}},current:{observed_at:'2026-10-09T10:00:00+02:00',temperature:13.4,apparent_temperature:12.1,weather_code:3,humidity:74,precipitation:0,wind_speed:8.2},days,alerts:[{id:'warn-1',title:'Amtliche WARNUNG vor FROST',region:'Kaiserslautern',level:2,description:'Es tritt Frost auf.',instruction:'Frostschutz beachten.',provider:'DWD'}]}));
 await page.goto('/?page=weather');await expect(page.getByRole('heading',{name:'Wetter'})).toBeVisible();await expect(page.getByText('13.4 °C')).toBeVisible();await expect(page.getByText('7 Tage')).toBeVisible();await expect(page.locator('.weather-day')).toHaveCount(7);await expect(page.getByText('Nicht aktuell')).toBeVisible();await expect(page.getByText('Amtliche WARNUNG vor FROST')).toBeVisible();await page.locator('.weather-day').nth(2).getByRole('button').click();await expect(page.getByText('5.2 mm')).toBeVisible();await expect(page.getByText('30 km/h')).toBeVisible();
});

test('weather center stays inside a 390px phone viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await installApiMocks(page);await page.route('**/api/weather/**',route=>json(route,{source:{provider:'Open-Meteo',status:'success',stale:false,last_success_at:'2026-10-09T10:00:00Z',location:{label:'Kaiserslautern'}},current:{observed_at:'2026-10-09T10:00:00+02:00',temperature:13.4,apparent_temperature:12.1,weather_code:2,humidity:74,precipitation:0,wind_speed:8.2},days,alerts:[]}));await page.goto('/?page=weather');await expect(page.locator('.weather-day')).toHaveCount(7);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)});
